### ISSUE TITLE
关于caddy2里的配置

### ISSUE THREAD

**Issue by aptx17** [lxhao61/integrated-examples#1]
哥，请问caddy2 能不能禁止以ip方式访问网站？
比如192.168.16.116是我的服务器地址，域名是www.demo.com，我想只允许用户通过域名访问，而不允许用户通过ip访问，好像nginx可以设置，新的caddy2不知如何设置。

**Comment by lxhao61** [comment]
当然可以。匹配器限定域名（host）访问。

**Comment by aptx17** [comment]
wow！！真的可以了！！
是json配置，添加了你给的两组配置，ok！
特别感谢!
