### ISSUE TITLE
可否加servername host？

### ISSUE THREAD

**Issue by offferu** [lxhao61/integrated-examples#1]
针对 /v2ray(vless+tcp+tls)+caddy2/

"xtlsSettings": { //如启用xtls，tlsSettings必须改成xtlsSettings。
          "alpn":[
            "h2", //启用h2连接，web回落也需配置支持h2回落；否则不一致（裸奔），被墙探测出，从而被封。
            "http/1.1" //启用http/1.1连接，web回落也需配置支持http/1.1回落；否则不一致（裸奔），被墙探测出，从而被封。
          ],

请问可以加个servername吗？如下面这样
"xtlsSettings": {
               "serverName": "xxxxxx.com",
               "alpn": [
                  "h2",
                  "http/1.1"
               ],

问题2） h2是由h2c实现的吗？

问题3）android客户端上network是选"tcp"还是选“h2”呢？

非常感谢！

**Comment by lxhao61** [comment]
问题1：可以加servername，此参数一般不需要。除非你服务器与域名不一致。
问题2：h2回落是有h2c server实现的，因为经过v2ray 回落给web服务器，v2ray已经解tls,不带了tls了，那么h2解tls就是h2c。
问题2：选tcp。你是vless+tcp应用。
