### ISSUE TITLE
大佬能否出个x-ui加caddy+naiveproxy谢谢了

### ISSUE THREAD

**Issue by MINGERTAI** [lxhao61/integrated-examples#102]
希望能出个x-ui加caddy+naiveproxy谢谢了
    这样就能方便很多小白配置x-ui加caddy+naiveproxy，x-ui各种回落，路径的设置问题了

                                                                       麻烦大佬了，谢谢🙏

**Comment by MINGERTAI** [comment]
也就是说同时安装x-ui 与您的编译好caddy（加各种插件的caddy），x-ui回落，路径都由您编译的caddy来实现，加naiveproxy与trojan go 功能的caddy.json配置

**Comment by lxhao61** [comment]
根本无比要！x-ui就是Xray，你要实现那些功，直接替换即可。
