### ISSUE TITLE
关于Xray下的trojan-go与naiveproxy共存的问题，该怎么设置？求教

### ISSUE THREAD

**Issue by zhukady** [lxhao61/integrated-examples#105]
在Xray下的trojan-go + ws和trojan-go + gRPC，已写入Xray配置（直接在X-UI面板写入），套上CDN（使用CF自家证书），如果同时使用naiveproxy（不套CDN），可以通过一个IP两个域名（其中一个套CDN，一个不套）实现吗？如果可以的话，Caddy怎么配置呢？谢谢！

**Comment by lxhao61** [comment]
你参考那个示例方案，就按照示例配置即可。

**Comment by zhukady** [comment]
那么在Caddyfile这个文件中，trojan + gRPC套CDN，naiveproxy（不套CDN），这个会有两个:443, xx.yy这样吗？一个填入CF证书，一个（naiveproxy）填入邮箱自签？麻烦指导下，谢谢

**Comment by lxhao61** [comment]
caddy配置多个域名（不要超过五个）或配置通配符域名申请证书即可。都有介绍，仔细看。
