### ISSUE TITLE
H2C caddy反代 UDS转发示例中 *ray配置需要Listen中增加0666权限

### ISSUE THREAD

**Issue by SQLimit** [lxhao61/integrated-examples#112]
xray 1.6.0
caddy 2.6.2
debian 11
xray的配置文件listen部分须为 "listen": "/dev/shm/vh2c.sock,0666"
如果不加0666权限则不能工作，不知是否是bug

**Comment by SQLimit** [comment]
另外如果使用caddy有几个不影响使用但强迫症的地方：
1. 提示buffer size 不够，解决方法“sysctl -w net.core.rmem_max=2500000”，参考https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size
2. 提示Caddyfile input is not formatted，解决方法“caddy fmt --overwrite /etc/caddy/Caddyfile”，参考https://caddyserver.com/docs/command-line#caddy-fmt

**Comment by lxhao61** [comment]
> 
首先示例是针对Xray或v2ray（V4）通用配置的，UDS权限统一即可（通用）。而加0666权限仅Xray支持，而v2ray不支持。

**Comment by lxhao61** [comment]
> xray 1.6.0 caddy 2.6.2 debian 11 xray的配置文件listen部分须为 "listen": "/dev/shm/vh2c.sock,0666" 如果不加0666权限则不能工作，不知是否是bug

首先示例是针对Xray或v2ray（V4）通用配置的，UDS权限统一即可（通用）。而加0666权限仅Xray支持，而v2ray不支持。

**Comment by lxhao61** [comment]
> 另外如果使用caddy有几个不影响使用但强迫症的地方：
> 
> 1. 提示buffer size 不够，解决方法“sysctl -w net.core.rmem_max=2500000”，参考https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size
> 2. 提示Caddyfile input is not formatted，解决方法“caddy fmt --overwrite /etc/caddy/Caddyfile”，参考https://caddyserver.com/docs/command-line#caddy-fmt

使用者参考提示即可搞定。
1、第一个提示本示例考虑添加。
2、本示例严格按照Caddyfile格式编辑的，如若产生二个提示肯定是自己编译产生的格式错误，不影响使用；若一定要解决参考提示执行命令即可解决。

**Comment by SQLimit** [comment]
> > xray 1.6.0 caddy 2.6.2 debian 11 xray的配置文件listen部分须为 "listen": "/dev/shm/vh2c.sock,0666" 如果不加0666权限则不能工作，不知是否是bug
> 
> 首先示例是针对Xray或v2ray（V4）通用配置的，UDS权限统一即可（通用）。而加0666权限仅Xray支持，而v2ray不支持。

那如果不在listen中设置权限该怎么操作，不设置权限的话我目前的环境配置不通。

**Comment by SQLimit** [comment]
> > 另外如果使用caddy有几个不影响使用但强迫症的地方：
> > 
> > 1. 提示buffer size 不够，解决方法“sysctl -w net.core.rmem_max=2500000”，参考https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size
> > 2. 提示Caddyfile input is not formatted，解决方法“caddy fmt --overwrite /etc/caddy/Caddyfile”，参考https://caddyserver.com/docs/command-line#caddy-fmt
> 
> 使用者参考提示即可搞定。 1、第一个提示仅启用HTTP/3，即使用naiveproxy才需要。本示例考虑添加。 2、本示例严格按照Caddyfile格式编辑的，如若产生二个提示肯定是自己编译产生的格式错误，不影响使用；若一定要解决提示，使用者参考提示执行命令即可解决。

1.是的，这个是udp才涉及的，不过运行就会有这个提示，我有强迫症还是配置一下消掉了。

**Comment by lxhao61** [comment]
> 
方法：
1、最简单方法，Xray或v2ray与caddy都使用root用户。
2、Xray或v2ray与caddy使用同一组用户，分别赋予使用UDS权限。
3、Xray或v2ray与caddy使用nobody用户。赋予使用UDS权限。

**Comment by lxhao61** [comment]
> 方法：
> 1、最简单方法，Xray或v2ray与caddy都使用root用户。
> 2、Xray或v2ray与caddy使用同一组用户，分别赋予使用UDS权限。
> 3、Xray或v2ray与caddy使用nobody用户。赋予使用UDS权限。

方法：
1、最简单方法，Xray或v2ray与caddy都使用root用户。
2、Xray或v2ray与caddy使用nobody用户，赋予使用UDS权限。
3、Xray或v2ray与caddy使用同一组用户，分别赋予使用UDS权限。

**Comment by SQLimit** [comment]
> > 方法：
> > 1、最简单方法，Xray或v2ray与caddy都使用root用户。
> > 2、Xray或v2ray与caddy使用同一组用户，分别赋予使用UDS权限。
> > 3、Xray或v2ray与caddy使用nobody用户。赋予使用UDS权限。
> 
> 方法： 1、最简单方法，Xray或v2ray与caddy都使用root用户。 2、Xray或v2ray与caddy使用nobody用户，赋予使用UDS权限。 3、Xray或v2ray与caddy使用同一组用户，分别赋予使用UDS权限。

明白了，谢谢解答，是否考虑将这些加入示例中，因为直接按照示例copy配置用UDS是不通的。

**Comment by lxhao61** [comment]
> > > xray 1.6.0 caddy 2.6.2 debian 11 xray的配置文件listen部分须为 "listen": "/dev/shm/vh2c.sock,0666" 如果不加0666权限则不能工作，不知是否是bug
> > 
> > 
> > 首先示例是针对Xray或v2ray（V4）通用配置的，UDS权限统一即可（通用）。而加0666权限仅Xray支持，而v2ray不支持。
> 
> 那如果不在listen中设置权限该怎么操作，不设置权限的话我目前的环境配置不通。

方法：
1、Xray或v2ray与caddy都使用root用户。（最简单方法）
2、Xray或v2ray与caddy使用nobody用户，赋予使用UDS权限。（推荐办法）
3、Xray或v2ray与caddy使用同一组用户，分别赋予使用UDS权限。

**Comment by lxhao61** [comment]
> > 方法： 1、最简单方法，Xray或v2ray与caddy都使用root用户。 2、Xray或v2ray与caddy使用nobody用户，赋予使用UDS权限。 3、Xray或v2ray与caddy使用同一组用户，分别赋予使用UDS权限。
> 
> 明白了，谢谢解答，是否考虑将这些加入示例中，因为直接按照示例copy配置用UDS是不通的。

都是Linux基础知识呀！这个不考虑添加，无必要。

**Comment by SQLimit** [comment]
> > > 方法： 1、最简单方法，Xray或v2ray与caddy都使用root用户。 2、Xray或v2ray与caddy使用nobody用户，赋予使用UDS权限。 3、Xray或v2ray与caddy使用同一组用户，分别赋予使用UDS权限。
> > 
> > 
> > 明白了，谢谢解答，是否考虑将这些加入示例中，因为直接按照示例copy配置用UDS是不通的。
> 
> 都是Linux基础知识呀！这个不考虑添加，无必要。

大佬我知道，对于专业的肯定是基础知识，不过对于类似我这种只会软件安装与卸载、系统开关机的小白来说有些问题还是很有难度的，毕竟看你配置的不一定都是专业的。

**Comment by lxhao61** [comment]
是的，但使用UDS需要自己了解Linux基础知识，否则提示没完没了。

**Comment by SQLimit** [comment]
> > > > xray 1.6.0 caddy 2.6.2 debian 11 xray的配置文件listen部分须为 "listen": "/dev/shm/vh2c.sock,0666" 如果不加0666权限则不能工作，不知是否是bug
> > > 
> > > 
> > > 首先示例是针对Xray或v2ray（V4）通用配置的，UDS权限统一即可（通用）。而加0666权限仅Xray支持，而v2ray不支持。
> > 
> > 
> > 那如果不在listen中设置权限该怎么操作，不设置权限的话我目前的环境配置不通。
> 
> 方法： 1、Xray或v2ray与caddy都使用root用户。（最简单方法） 2、Xray或v2ray与caddy使用nobody用户，赋予使用UDS权限。（推荐办法） 3、Xray或v2ray与caddy使用同一组用户，分别赋予使用UDS权限。

更新到debian11之后使用nobody用户会提示不安全，虽然不影响使用，但又是强迫症跨不过去的坎，我用方法3解决了。属于是又菜又爱玩了。

**Comment by SQLimit** [comment]
> 是的，但使用UDS需要自己了解Linux基础知识，否则提示没完没了。

是的，感谢解答！
