### ISSUE TITLE
大佬，可以指点一下caddy的写法吗？

### ISSUE THREAD

**Issue by wclmgcd** [lxhao61/integrated-examples#116]
最近v2ray被识别，所以自己在vps上搭建了NaiveProxy ，用caddy，加上爱好rss，所以又搭建了一个FreshRSS，但里面的xExtension-ImageProxy插件要自己搭建代理网址，举例中只有nginx的，没有caddy的，大佬可以指点一下这个如何写吗？https://github.com/FreshRSS/Extensions/blob/master/xExtension-ImageProxy/README.md

**Comment by lxhao61** [comment]
不太明白代理FreshRSS，你可参考[reverse_proxy](https://caddy2.dengxiaolong.com/docs/caddyfile/directives/reverse_proxy)介绍，重点‘重写’与‘传输’配置。只有你自己折腾了。

**Comment by wclmgcd** [comment]
感谢大佬，已成功
