### ISSUE TITLE
caddy如何让SSL证书自动续期？ 

### ISSUE THREAD

**Issue by cary-sas** [lxhao61/integrated-examples#118]
不好意思，这个issue与项目无太大关系，我就是想让配置好的caddy 帮我进行SSL证书（**一定要zerossl RSA**）的自动续期，你知道应该怎么在Caddyfile里面配置吗？
我目前找了一个[例子](https://allinfa.com/trojan-caddy-auto-ssl-caddyfile.html)， 不大确定是否正确。

**Comment by lxhao61** [comment]
> 



> 不好意思，这个issue与项目无太大关系，我就是想让配置好的caddy 帮我进行SSL证书（**一定要zerossl RSA**）的自动续期，你知道应该怎么在Caddyfile里面配置吗？ 我目前找了一个[例子](https://allinfa.com/trojan-caddy-auto-ssl-caddyfile.html)， 不大确定是否正确。

知道，不推荐在Caddyfile里面配置。因为回落模式使用Caddyfile配置自动申请TLS证书，需要额外占用端口配置一个空站点，麻烦与冗余。

**Comment by lxhao61** [comment]
> 我试着改了一下 tls 的层级，caddy 能正常启动了，但是SSL 证书没有出现在预期的文件夹里
> 
> ![image](https://user-images.githubusercontent.com/61653855/198982066-be2f1c23-eb8a-43ea-8dbe-5d08349b75b2.png)

你这个配置对了。出现这个情况试试重启。另外注意证书文件目录是否有写入权限。

**Comment by lxhao61** [comment]
当前caddy从Let's Encrypt或ZeroSSL自动申请的SSL/TLS证书默认都为ECC证书。你要RSA证书，还需在TLS配置"policies"中加"key_type": "rsa2048",见如下：
```
    "tls": {
      "certificates": {
        "automate": ["$domain"]
      },
      "automation": {
        "policies": [{
          "issuers": [{
              "module": "zerossl", 
              "email": "my@example.com" 
          }],
          "key_type": "rsa2048"
        }]
      }
    }
  }
}
```

**Comment by lxhao61** [comment]
证书路径有错误。"root": "/usr/local/etc/xray/" 改为"root": "/usr/local/etc/xray"。另外你caddy用户必须对它有写入权限！

**Comment by lxhao61** [comment]
> > > 我试着改了一下 tls 的层级，caddy 能正常启动了，但是SSL 证书没有出现在预期的文件夹里
> > > ![image](https://user-images.githubusercontent.com/61653855/198982066-be2f1c23-eb8a-43ea-8dbe-5d08349b75b2.png)
> > 
> > 
> > 你这个配置对了。出现这个情况试试VPS重启（重新申请TLS证书与加载TLS证书）。另外注意caddy对证书文件目录是否有写入权限等。
> 
> 权限我设置了` chmod -R 747 /usr/local/etc/xray`

你这个是设置文件权限，跟设置用户权限基本无关。

**Comment by lxhao61** [comment]
> 我不确定caddy 有没有设置单独的用户组，我以为我这个VPS 只有一个root 用户， 我给你看一下我目前的文件夹权限 <img alt="image" width="347" src="https://user-images.githubusercontent.com/61653855/199042985-ea0894ca-c7ce-4202-9faf-8c8386dab0f5.png">

你Xray与Caddy都是root用户启动的？

**Comment by lxhao61** [comment]
看你Xray与Caddy的x.service配置

**Comment by lxhao61** [comment]
方法：
1、caddy用户及组都改为root。（最简单方法）
2、Xray与caddy使用nobody用户，赋予使用文件权限。（推荐办法）
3、Xray与caddy使用同一组用户，分别赋予使用文件权限。

**Comment by lxhao61** [comment]
> 我暂时先选择了方法1，我这样改了一下，然后重启VPS，还是没有出现证书啊 <img alt="image" width="507" src="https://user-images.githubusercontent.com/61653855/199048357-07d77fe0-c32c-4153-b668-8d5a6beba970.png">

你caddy.service的ExecReload有错误。

**Comment by lxhao61** [comment]
caddy.service修改对了。
不知道证书目录你改为/home/tls试没、

**Comment by lxhao61** [comment]
不需要。只要你填写你正确邮件即可。

**Comment by lxhao61** [comment]
邮箱本来就是一个选配项，主要接受申请申请信息。随便填一个你使用的邮箱即可。

**Comment by lxhao61** [comment]
若还是不成功，建议今天不要再折腾了。我好想在Telegram看到一个Let's Encrypt与ZeroSSL出故障链接，不知道修复没。

**Comment by lxhao61** [comment]
> 我改了邮箱，重新来一遍。还是一样啊

我一直没有问你怎么一样？现在证书目录中有什么？全是空？

**Comment by lxhao61** [comment]
> **我想问一下 caddy 申请并更新证书是自己定时的，还是即时更新的?** 我昨天后来什么都没做，早上起来发现证书已经申请好了，证书在` $HOME/tls/certificates/acme.zerossl.com-v2-dv90/$domain` , 时间是凌晨4点。**caddy申请证书 有debug log 啥的可以看吗？** ![image](https://user-images.githubusercontent.com/61653855/199155379-52a4c4d5-998a-4f73-87cf-e8431a07f3ef.png)
> 
> 关于你上面的问题，是这样的。 1，如果我把证书路径设在 /usr/local/etc/tls 这样的路径，则里面啥都没有,估计是没有权限。我需要研究一下 `2、Xray与caddy使用nobody用户，赋予使用文件权限。（推荐办法）` 怎么去实现。（有正确的指导教程吗？）。 2，如果我把证书路径设在 /root/tls, 重启VPS 后会有acme 这个文件夹，里面有[一些文件](https://user-images.githubusercontent.com/61653855/199053941-c7c5c440-796e-48d5-9a8b-cb3dd2eb8d46.png)，但没有certificates文件夹以及里面的证书。
> 
> 我不是通配符域名，就是简单的一个域名。

证书申请是即时申请，更新是定时申请（详细见本项目相关介绍）。证书凌晨4点才申请下来可能是ZeroSSL出故障修复了。可以调整日志级数及查询日志了解证书申请情况。

1、另外nobody用户赋予使用文件权限，你自己折腾了。参考官方Xray或v2ray赋予证书目录权限。
2、晕，你涂域名了影响没发现申请出错、锁定了。一个正常现象。

**Comment by lxhao61** [comment]
> 现在差不多可以解决问题了， 我修改了caddy 的user 和group 为root，证书位置放 $HOME/tls 下面， caddy会在后台自己申请证书到 `tls/certificates/acme.zerossl.com-v2-dv90/domain` 下面。 目前遗留的问题就是，caddy 申请证书的过程有点延迟，导致xray 启动时候找不到证书然后就启动失败了。怎样才能强制让caddy 马上去申请证书？ 一定要重启 VPS 吗？ 另外你觉得可以在 caddy.service里面加上`ExecStartPost=cp $HOME/tls/certificates/acme.zerossl.com-v2-dv90/$domain/$domain.* /usr/local/etc/xray/` 吗? 这样caddy 更新完证书后就可以自动copy 到 xray 的folder里面。

证书申请稍微延迟，无证书Xray出问题、重启VPS等本来就是正常情况。这个仅首次出现，以后你就不必担心及管它了。
不必拷贝，Xray直接引用Caddy自动申请的证书才能实现同步更新！
