### ISSUE TITLE
caddy 加 caddy-l4 插件定制编译的才可以实现 SNI 分流，目前仅支持使用 json 配置（不支持 Caddyfile 配置）

### ISSUE THREAD

**Issue by MINGERTAI** [lxhao61/integrated-examples#119]
# 分流layer4用于支持Caddyfile配置文件
###  --with github.com/RussellLuo/caddy-ext/layer4
https://github.com/RussellLuo/caddy-ext/tree/master/layer4

希望大佬加入，另外出个配置

**Comment by lxhao61** [comment]
你提供的项目是对caddy-l4插件Caddyfile配置来说是半残品，最核心是不支持layer4.matchers.tls模块；故不可能使用你提供的项目实现caddy-l4插件Caddyfile配置SNI分流。
