### ISSUE TITLE
`20221105`的更新还提供caddy的二进制文件吗？

### ISSUE THREAD

**Issue by 70599** [lxhao61/integrated-examples#124]
https://github.com/lxhao61/integrated-examples/tree/20221105
这次的更新没有caddy的二进制文件，还会提供吗？

**Comment by lxhao61** [comment]
计划在未来v2.6.3版中加入caddy-events-exec插件支持，此期间想使用master源码编译一个过渡版，结果发现master源码不支持caddy-events-exec及caddy-trojan插件编译（出错），目前只能等官方v2.6.3版出来后编译了。

**Comment by 70599** [comment]
好的，谢谢，明白了。
