### ISSUE TITLE
请问以后还提供Caddyflie配置文件吗？

### ISSUE THREAD

**Issue by crosspacific** [lxhao61/integrated-examples#126]
最近想更新一下Caddy和配置文件，发现很多示例里面的Caddyflie配置都没有了。请问： 1）以后还会提供Caddyflie配置文件吗？2）现在的caddy.json都是自动申请证书，如果要用自己的证书文件，应该怎么修改呢？谢谢。

**Comment by lxhao61** [comment]
caddy的优势之一是自动申请TLS证书，而以回落/分流为主的应用使用Caddyflie配置太冗余及麻烦；故删除。
1）以回落/分流为主的应用以后不会提供Caddyflie配置，除非以后Caddyflie有优化。
2）要用自己的TLS证书请参考‘caddy(other configuration) （Caddy的特殊应用配置方法。）’中对应介绍及对应配置示例。

**Comment by crosspacific** [comment]
感谢！
