### ISSUE TITLE
GRCP间歇性断开连，需要重启客户端或者caddy才能恢复。

### ISSUE THREAD

**Issue by hkthomas** [lxhao61/integrated-examples#129]
时间不等，有时候10几分钟，有时候几个小时。

使用XTLS没有出现过。

出现该问题的时候服务器是正常的，可以连接之类的。

下面是日志。sock给的666权限。

{"level":"error","ts":1669257628.648649,"logger":"http.log.error","msg":"dial unix /dev/shm/Xray-VLESS-gRPC.sock: connect: no such file or directory","request":{"remote_ip":"****","remote_port":"1734","proto":"HTTP/2.0","method":"POST","host":"***","uri":"/speedtest/Tun","headers":{"Content-Type":["application/grpc"],"User-Agent":["grpc-go/1.36.0"]},"tls":{"resumed":false,"version":772,"cipher_suite":4867,"proto":"h2","server_name":"***"}},"duration":0.000320216,"status":502,"err_id":"up0tg631m","err_trace":"reverseproxy.statusError (reverseproxy.go:1272)"}

**Comment by lxhao61** [comment]
信息太少，不明白你的具体情况。
不明白你到底参考的是那个框架示例，也不知道针对gRCP部分是否严格参考了示例配置。

**Comment by hkthomas** [comment]
[v2ray(vless\vmess+grpc)+caddy\nginx] > [2_Caddyfile] > [2_v2ray_vless_config.json] 

XRAY 是 v1.6.2

caddy v2.6.2

改动的话用的非443端口，手动指向了已有的证书。

**Comment by lxhao61** [comment]
原来是你呀。仔细看链接：https://github.com/lxhao61/integrated-examples/issues/106

**Comment by hkthomas** [comment]
TLS后面我发现这个问题并修正了，我目前用得就是这个配置。

我试下Local Loopback看看。

**Comment by hkthomas** [comment]
试了一下，用Local Loopback，问题还是这样，重启caddy立马可以恢复。

caddy log：
`{"level":"error","ts":1669373242.2175624,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 23; CANCEL"}
{"level":"error","ts":1669373242.2176318,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 23; CANCEL"}
{"level":"error","ts":1669373242.2176871,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 19; CANCEL"}
{"level":"error","ts":1669373242.2176955,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 19; CANCEL"}
{"level":"error","ts":1669373242.2177203,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 17; CANCEL"}
{"level":"error","ts":1669373242.217727,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 17; CANCEL"}
{"level":"error","ts":1669373242.2184389,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 21; CANCEL"}
{"level":"error","ts":1669373242.21846,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 21; CANCEL"}
{"level":"error","ts":1669373242.2184947,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 15; CANCEL"}
{"level":"error","ts":1669373242.2186604,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 15; CANCEL"}
{"level":"error","ts":1669373242.2187352,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 25; CANCEL"}
{"level":"error","ts":1669373242.218747,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 25; CANCEL"}
{"level":"error","ts":1669373244.8644328,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 67; CANCEL"}
{"level":"error","ts":1669373244.8645387,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 67; CANCEL"}
{"level":"error","ts":1669373246.4098234,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 69; CANCEL"}
{"level":"error","ts":1669373246.4098961,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 69; CANCEL"}
{"level":"error","ts":1669373246.409995,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 71; CANCEL"}
{"level":"error","ts":1669373246.4100122,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 71; CANCEL"}
{"level":"error","ts":1669373290.00331,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 9; CANCEL"}
{"level":"error","ts":1669373290.0033743,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 9; CANCEL"}
{"level":"error","ts":1669373292.099302,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 53; CANCEL"}
{"level":"error","ts":1669373292.099366,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 53; CANCEL"}`

caddy 配置：
`{
	order reverse_proxy before route
	admin off
	log {
		output file /root/caddylog/access.log
		level ERROR
	}
}

:443, *** {
	tls /root/xray/fullchain.crt /root/xray/private.key {
		ciphers TLS_AES_256_GCM_SHA384 TLS_AES_128_GCM_SHA256 TLS_CHACHA20_POLY1305_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
		curves x25519 secp521r1 secp384r1 secp256r1
	}

	@vgrpc {
		protocol grpc
		path /speedtest/*
	}
	reverse_proxy @vgrpc 127.0.0.1:2009 {
		transport http {
			versions h2c 2
		}
		flush_interval -1
		header_up X-Real-IP {remote_host}
	}

	@host {
		host **
	}
	route @host {
		header {
			Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		}
		file_server {
			root /www/html
		}
	}
}`

xray 配置：
`{
	"log": {
		"error": "/root/xray/xray_er.log",
		//"access": "/root/xray/xray_access.log",
		"loglevel": "warning"
	},
	"inbounds": [
		{
			"listen": "0.0.0.0",
			"port": 2009,
			"protocol": "vless",
			"settings": {
				"clients": [
					{
						"id": "***"
					}
				],
				"decryption": "none"
			},
			"streamSettings": {
				"network": "GRPC",
				"security": "none",
				"grpcSettings": {
					"alpn": [
						"h2"
					],
					"serviceName": "speedtest"
				}
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		}
	],
	"outbounds": [
		{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {}
		},
		{
			"tag": "blocked",
			"protocol": "blackhole",
			"settings": {}
		}
	],
	"routing": {
		"domainStrategy": "AsIs",
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:private"
				],
				"outboundTag": "blocked"
			},
			{
                "domain": [
                    "geosite:cn",
                    "geosite:geolocation-cn"
                ],
                "outboundTag": "blocked",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "blocked",
                "type": "field"
            }
		]
	}
}`

**Comment by hkthomas** [comment]
试了一下，用Local Loopback，问题还是这样，重启caddy立马可以恢复。

> caddy log：
{"level":"error","ts":1669373242.2175624,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 23; CANCEL"}
{"level":"error","ts":1669373242.2176318,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 23; CANCEL"}
{"level":"error","ts":1669373242.2176871,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 19; CANCEL"}
{"level":"error","ts":1669373242.2176955,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 19; CANCEL"}
{"level":"error","ts":1669373242.2177203,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 17; CANCEL"}
{"level":"error","ts":1669373242.217727,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 17; CANCEL"}
{"level":"error","ts":1669373242.2184389,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 21; CANCEL"}
{"level":"error","ts":1669373242.21846,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 21; CANCEL"}
{"level":"error","ts":1669373242.2184947,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 15; CANCEL"}
{"level":"error","ts":1669373242.2186604,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 15; CANCEL"}
{"level":"error","ts":1669373242.2187352,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 25; CANCEL"}
{"level":"error","ts":1669373242.218747,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 25; CANCEL"}
{"level":"error","ts":1669373244.8644328,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 67; CANCEL"}
{"level":"error","ts":1669373244.8645387,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 67; CANCEL"}
{"level":"error","ts":1669373246.4098234,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 69; CANCEL"}
{"level":"error","ts":1669373246.4098961,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 69; CANCEL"}
{"level":"error","ts":1669373246.409995,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 71; CANCEL"}
{"level":"error","ts":1669373246.4100122,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 71; CANCEL"}
{"level":"error","ts":1669373290.00331,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 9; CANCEL"}
{"level":"error","ts":1669373290.0033743,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 9; CANCEL"}
{"level":"error","ts":1669373292.099302,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 53; CANCEL"}
{"level":"error","ts":1669373292.099366,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 53; CANCEL"}

caddy 配置：
```
{
	order reverse_proxy before route
	admin off
	log {
		output file /root/caddylog/access.log
		level ERROR
	}

 }
:443, *** {
	tls /root/xray/fullchain.crt /root/xray/private.key {
		ciphers TLS_AES_256_GCM_SHA384 TLS_AES_128_GCM_SHA256 TLS_CHACHA20_POLY1305_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
		curves x25519 secp521r1 secp384r1 secp256r1
	}
	@vgrpc {
		protocol grpc
		path /speedtest/*
	}
	reverse_proxy @vgrpc 127.0.0.1:2009 {
		transport http {
			versions h2c 2
		}
		flush_interval -1
		header_up X-Real-IP {remote_host}

	}

	@host {
		host **
	}
	route @host {
		header {
			Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		}
		file_server {
			root /www/html
		}
	}
}
```
xray 配置：
````{
	"log": {
		"error": "/root/xray/xray_er.log",
		//"access": "/root/xray/xray_access.log",
		"loglevel": "warning"
	},
	"inbounds": [
		{
			"listen": "0.0.0.0",
			"port": 2009,
			"protocol": "vless",
			"settings": {
				"clients": [
					{
						"id": "***"
					}
				],
				"decryption": "none"
			},
			"streamSettings": {
				"network": "GRPC",
				"security": "none",
				"grpcSettings": {
					"alpn": [
						"h2"
					],
					"serviceName": "speedtest"
				}
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		}
	],
	"outbounds": [
		{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {}
		},
		{
			"tag": "blocked",
			"protocol": "blackhole",
			"settings": {}
		}
	],
	"routing": {
		"domainStrategy": "AsIs",
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:private"
				],
				"outboundTag": "blocked"
			},
			{
                "domain": [
                    "geosite:cn",
                    "geosite:geolocation-cn"
                ],
                "outboundTag": "blocked",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "blocked",
                "type": "field"
            }
		]
	}
}
````

**Comment by lxhao61** [comment]
无语，这么简单应用就这么多错误！请严格参考如下修改好的配置测试！
```caddy 配置：
{
	order reverse_proxy before route
	admin off
	log {
		output file /root/caddylog/access.log
		level ERROR
	}

 }
:443 {
	tls /root/xray/fullchain.crt /root/xray/private.key {
		ciphers TLS_AES_256_GCM_SHA384 TLS_AES_128_GCM_SHA256 TLS_CHACHA20_POLY1305_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
		curves x25519 secp521r1 secp384r1 secp256r1
	}
	@vgrpc {
		protocol grpc
		path /speedtest/*
	}
	reverse_proxy @vgrpc 127.0.0.1:2009 {
		transport http {
			versions h2c 2
		}
		flush_interval -1
		header_up X-Real-IP {remote_host}

	}

	@host {
		host **
	}
	route @host {
		header {
			Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		}
		file_server {
			root /www/html
		}
	}
}
```
```xray 配置：
	"log": {
		"error": "/root/xray/xray_er.log",
		//"access": "/root/xray/xray_access.log",
		"loglevel": "warning"
	},
	"inbounds": [
		{
			"listen": "127.0.0.1",
			"port": 2009,
			"protocol": "vless",
			"settings": {
				"clients": [
					{
						"id": "***"
					}
				],
				"decryption": "none"
			},
			"streamSettings": {
				"network": "grpc",
				"security": "none",
				"grpcSettings": {
					"serviceName": "speedtest"
				}
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		}
	],
	"outbounds": [
		{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {}
		},
		{
			"tag": "blocked",
			"protocol": "blackhole",
			"settings": {}
		}
	],
	"routing": {
		"domainStrategy": "IPIfNonMatch",
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:private"
				],
				"outboundTag": "blocked"
			},
			{
                "domain": [
                    "geosite:cn",
                    "geosite:geolocation-cn"
                ],
                "outboundTag": "blocked",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "blocked",
                "type": "field"
            }
		]
	}
}
```

**Comment by hkthomas** [comment]
应该是xray有问题，同配置我把服务端换成v2ray v4.45，目前为止没出现过该情况。。。
