### ISSUE TITLE
用了

### ISSUE THREAD

**Issue by offferu** [lxhao61/integrated-examples#13]
配置3 https://github.com/lxhao61/integrated-examples/blob/master/v2ray(complete%2Bh2c)%2Bnaiveproxy/3_caddy.json

将88改成h1h2c.sock后，我在浏览器中打不开自己的域名了，请问需要在/dev/shm/新建一个h1h2c.sock文件吗？

多谢！

**Comment by lxhao61** [comment]
若仅改端口回落为进程回落，不应该出现你说的情况！仔细检查进程路径与格式，v2ray进程与caddy2进程格式不同的。进程不需要新建，只要路径/dev/shm/存在即可。

**Comment by offferu** [comment]
照您模板抄的，仔细核对，没发现路径错误，但域名还是打不开，你们的都能打开吗？
换88就工作正常

**Comment by lxhao61** [comment]
什么信息都没有，你这个情况根本无法判定！此配置我专门测试过才分享的。
检查caddy2启动成功没？试试进入/dev/shm目录中，若有h1h2c.sock文件，删除后重新启动。
若还是不成功。提供如下信息：
1、caddy版本及插件是否符合。
2、caddy启动状态及日志。
3、v2ray或Xray版本及启动日志。
4、caddy配置、v2ray或Xray配置。

**Comment by offferu** [comment]
是因为xray user=nobody导致的吗？
[Warning] [3456389355] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to /dev/shm/h1h2c.sock > common/retry: [dial unix /dev/shm/h1h2c.sock: connect: permission denied] > common/retry: all retry attempts failed

**Comment by offferu** [comment]
给h1h2c.sock赋了777权限后搞定了，非常感谢！
