### ISSUE TITLE
请问如何启动trojan?

### ISSUE THREAD

**Issue by offferu** [lxhao61/integrated-examples#132]
在 https://github.com/lxhao61/integrated-examples/tree/main/V2Ray(E%2BB%2BD%2BG%2BA)%2BTrojan%2BCaddy(N) 中：

1）还需要专门安装trojan吗？我看caddy中包含了caddy-trojan了。

2）trojan配置文件放什么位置？

3）如何启动trojan?

**Comment by lxhao61** [comment]
1、你选用的示例是需要安装原版Trojan或Trojan-Go，非采用Caddy插件caddy-trojan实现Trojan或Trojan-Go。当然你也可以选用Caddy插件caddy-trojan实现Trojan或Trojan-Go示例。
2、Trojan配置文件放在那里，无严格要求（基本随你的方便，参考如下Service Configuration。）。
3、如何启动Trojan，详细见原版介绍。推荐使用systemd管理启动，参考 [Service Configuration](https://github.com/lxhao61/integrated-examples/tree/main/Service%20Configuration) 中对应文件。
