### ISSUE TITLE
如何让caddy 自动获取fullchain的证书啊

### ISSUE THREAD

**Issue by cary-sas** [lxhao61/integrated-examples#133]
如题，想接着这个之前的issue 再问个问题，
https://github.com/lxhao61/integrated-examples/issues/118

**Comment by lxhao61** [comment]
无厘头，骑马找马！

**Comment by lxhao61** [comment]
https://letsencrypt.org/zh-cn/docs/dst-root-ca-x3-expiration-september-2021/
https://letsencrypt.org/zh-cn/docs/certificate-compatibility/
