### ISSUE TITLE
使用"套娃方式实现VLESS回落/分流与Trojan回落共存为主的综合应用"报错不解

### ISSUE THREAD

**Issue by Pacio** [lxhao61/integrated-examples#137]
使用的配置：https://github.com/lxhao61/integrated-examples/blob/main/V2Ray(E%2BB%2BC%2BF%2BG%2BA)%2BNginx/2_v2ray_config.json
因为是docker部署的，已经把shadowsocks grpc监听地址修改为docker内对应的主机网关(127.0.0.1改为172.17.0.1),如图:
![image](https://user-images.githubusercontent.com/6836705/210779934-2767bbfd-75f0-4f2a-86f2-df885bb7cd78.png)
仍然报错如下：
![image](https://user-images.githubusercontent.com/6836705/210776950-3bf5e621-746a-4ef1-8e59-85e4eee16f95.png)

实测除了报错的这个shadowsocks+grpc+tls和kcp不通，其他套娃的协议都能正常通，这里还需要修改其他地方吗？

**Comment by lxhao61** [comment]
你使用的是Xray，还是V2ray？
另外能打开伪装网站不？特别是HTTP/2模式。

**Comment by lxhao61** [comment]
那你配置肯定有问题！数据无法达到伪装网站，而shadowsocks grpc是基于Nginx反代的。我对docker配置了解不多，只有你自己搞定了。

**Comment by Pacio** [comment]
我研究一下nginx的docker版吧~应该不能按你原版那么弄
