### ISSUE TITLE
求 VLESS-TCP-XTLS-Vision 的多合一搭配配置文件

### ISSUE THREAD

**Issue by cary-sas** [lxhao61/integrated-examples#138]
如题

**Comment by lxhao61** [comment]
XTLS-Vision不太稳定、XTLS仅作用自己，且目前不支持PROXY protocol传入（即SIN分流时，不能启用PROXY protocol应用。）。
若实在需要XTLS-Vision的多合一搭配配置文件，参考单一配置自行修改即可，很简单的。

**Comment by lxhao61** [comment]
推荐使用[RPRX刚提交的PR](https://github.com/XTLS/Xray-core/commit/6f61021f7a7337b2997c442495cb8654d145cf8f)而自动编译的[Xray文件](https://github.com/XTLS/Xray-core/actions/runs/3852942954)，好像除不支持PROXY protocol传入外，其它问题解决了。

**Comment by lxhao61** [comment]
[XTLS-Vision接收PROXY protocol](https://github.com/XTLS/Xray-core/commit/8c0d3c02570a73cd55f4f61025701bad7cb63c08#comments)也被RPRX大搞定了，暂时无版本v1.7.2，可临时使用自动编辑的[Xray文件](https://github.com/XTLS/Xray-core/actions/runs/3861770515)。
