### ISSUE TITLE
V2Ray(Trojan+WS)+Caddy 的cdn方案怎么配caddy.json？

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [lxhao61/integrated-examples#139]
之前你这里好象是有caddy.json方案吧，按照你设置的一切正常，不过当时没有开cdn和子域名。
请问下要在caddy.json里做改动支持cdn和多个子域名z1.xx.yy, z2.xx.yy, 应该怎么改。

我把之前的caddy.json文件里有域名出现的地方：
1. match-host 原来"xx.yy" 改成了 "*.xx.yy"
2. certificates-automate ["xx.yy"] 改成了 ["z1.xx.yy", "z2.xx.yy"]

目前症状是caddy并不生成z2.xx.yy的证书。只有第一个域名可以正常使用。

**Comment by lxhao61** [comment]
所有["xx.yy"] 改成了 "z1.xx.yy","z2.xx.yy"。

**Comment by GreatBigWhiteWorld** [comment]
> 
我先试的就是这样不行，后来改成了上面那个也不行，刚又试了下你说的还是不行，不能生成第二个证书。算了就用一个域名也能用，多谢。
