### ISSUE TITLE
haproxy 分流到sock, 是不是需要权限？ 

### ISSUE THREAD

**Issue by meziberry** [lxhao61/integrated-examples#14]
https://github.com/lxhao61/integrated-examples/tree/master/v2ray(complete%2Btrojan%2Bh2c)%2Bnaiveproxy%2Bhaproxy
这个配置，之前haproxy分流到端口是可用的。但改为分流到 sock 后，就不通了。提示`PR_END_OF_FILE_ERROR`.  是不是需要特殊权限？

**Comment by lxhao61** [comment]
程序必须有进程的路径执行权限。
另外注意haproxy屏蔽chroot，否则路径不一致。

**Comment by meziberry** [comment]
chroot 已屏蔽。 
以下是caddy和xray的sock文件。

```
srwxr-xr-x 1 root   root   0 Dec 24 12:03 caddy.sock
srwxr-xr-x 1 root   root   0 Dec 24 12:03 h1h2c.sock
srwxr-xr-x 1 nobody nobody 0 Dec 24 12:23 trojan.sock
-rw-r--r-- 1 nobody nobody 0 Dec 24 12:23 trojan.sock.lock
srwxr-xr-x 1 nobody nobody 0 Dec 24 12:23 vless.sock
-rw-r--r-- 1 nobody nobody 0 Dec 24 12:23 vless.sock.lock
```
other是不是少个些的权限？是动态产生的sock, 怎么修改权限呢？ 是不是又修改service文件才行？

**Comment by lxhao61** [comment]
两种方法解决：
1、v2ray或Xray用root用户运行（修改service文件）。
2、chown -R nobody:nobody /dev/shm/      （赋予nobody用户对进程路径执行权限）

**Comment by meziberry** [comment]
多谢指点，用了第二种方法。通畅了。
