### ISSUE TITLE
可否添加 Brook 回落到 Nginx / Caddy 配置？

### ISSUE THREAD

**Issue by samho1234567** [lxhao61/integrated-examples#14]
如题，可否添加 Brook 回落到 Nginx / Caddy 配置，如 wsserver，甚至与 v2ray、trojan 和 naiveproxy 等同时运行？

Brook: https://github.com/txthinking/brook

**Comment by lxhao61** [comment]
> 如题，可否添加 Brook 回落到 Nginx / Caddy 配置，如 wsserver，甚至与 v2ray、trojan 和 naiveproxy 等同时运行？
> 
> Brook: https://github.com/txthinking/brook

据我所知Brook不支持回落，无法实现。

**Comment by samho1234567** [comment]
那没办法了 :(
