### ISSUE TITLE
shadowtls 是否能套在caddy后面sni分流？

### ISSUE THREAD

**Issue by ixxmu** [lxhao61/integrated-examples#140]
如题，shadowTLS能否和其他协议一起放在caddy的同一端口，如443，在layer4上做sni分流？

谢谢大佬这么优秀的各种配置方案！

**Comment by lxhao61** [comment]
没试过，你可以自行测试。个人觉得shadowTLS只是TLS处理不同，跟SNI分流等应该无影响。

**Comment by ixxmu** [comment]
> 没试过，你可以自行参考相关示例测试。个人觉得TLS只是由shadowTLS提供而已，跟SNI分流等无关。

好吧，还是等等这个特性的xray落地吧，一把梭
