### ISSUE TITLE
改用新的Caddyfile后无法启动

### ISSUE THREAD

**Issue by cutemanworking** [lxhao61/integrated-examples#144]
小白问题一个, 使用之前的caddy json格式没问题, 转用新版本后启动报以下错误;　
INFO    using provided configuration    {"config_file": "./caddyfile", "config_adapter": ""}
Error: loading initial config: decoding request body: invalid character 'o' looking for beginning of object key string

用的是这个版本:
https://github.com/lxhao61/integrated-examples/blob/main/V2Ray(B%2BD%2BG%2BA)%2BCaddy(N%2BT)/1_Caddyfile

**Comment by lxhao61** [comment]
caddy-trojan插件配置在Caddy v2.6.0后有大幅度调整，下载最新Caddy程序文件再使用最新配置。

**Comment by lxhao61** [comment]
> caddy version v2.6.4 h1:2.......
> 
> 启动命令为: caddy run --environ --config /etc/caddy/caddyfile

Caddy文件使用的本人的？

**Comment by cutemanworking** [comment]
caddy是在这里下载的.　caddyfile如下

{
	order trojan before route
	order forward_proxy before trojan
	order reverse_proxy before forward_proxy
	admin off
	log {
		output file /var/log/caddy/error.log
		level ERROR
	} 
	email abc@abc.com

	servers :443 {
		listener_wrappers {
			trojan 
		}
	}
	trojan {
		caddy
		no_proxy
		users abcd
	}
}

:443, xx.yx.yz {
	tls {
		ciphers TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
		curves x25519 secp521r1 secp384r1 secp256r1
	}
    {
	    email abc@abc.com
	    acme_dns cloudflare lkjljlkj;lkj;kj; 
    }

	@vmws {
		path /xxxws
		header Connection *Upgrade*
		header Upgrade websocket
	}
	reverse_proxy @vmws unix/@vmessws 

	reverse_proxy /xxxh2 unix/@vlessh2c { 
		transport http {
			versions h2c 2
		}
	}

	@sgrpc {
		protocol grpc
		path /cdngrpc/* 
	}
	reverse_proxy @sgrpc 127.0.0.1:2011 {
		transport http {
			versions h2c 2
		}
		flush_interval -1
		header_up X-Real-IP {remote_host}
	}

	forward_proxy {
		basic_auth abc abc
		hide_ip
		hide_via
		probe_resistance
	}

	trojan {
		connect_method
		websocket
	} 


}

**Comment by cutemanworking** [comment]
./caddy version
v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=

**Comment by lxhao61** [comment]
> 

请严格参考示例！
除了申请证书部分错误，还有route部分配置的网站那里去了？

**Comment by lxhao61** [comment]
> 删掉申请证那部分,　还是同样的错误,　用之前很多层那个caddy.json版本倒是一直正常.　想改用新版,　主要还是原来的版本太多层,　看晕了.　^-^

你要使用caddy.json版本，可以参考[V2Ray(E+B+F+C+D+G+A)+Caddy(N)+Nginx\HAProxy](https://github.com/lxhao61/integrated-examples/tree/main/V2Ray(E%2BB%2BF%2BC%2BD%2BG%2BA)%2BCaddy(N)%2BNginx%5CHAProxy)中caddy.json修改。

**Comment by cutemanworking** [comment]
我再试试

**Comment by cutemanworking** [comment]
修改后可以跑起来了.　再次感谢这个优秀的项目.  :P
