### ISSUE TITLE
nginx 分流到naiveproxy 端口问题

### ISSUE THREAD

**Issue by qilinbar** [lxhao61/integrated-examples#145]
nginx sni域名分流V2Ray(E+B+D+G+A)+Trojan+Caddy(N)+Nginx\HAProxy/ 这个应用中，用json文件可以正常运行，但因为json搭设php实在不会，还想用Caddyfile，可是因为nginx已经在443的tcp和udp端口监听了，用实例中Caddyfile启动提示Error: loading initial config: loading new config: http app module: start: listen udp 127.0.0.1:443: bind: address already in use  请问哪里的问题呢，既然提供了Caddyfile就应该可以用吧，请问需要修改哪里呢。

**Comment by lxhao61** [comment]
明显你提示你在Caddyfile配置中使用了443端口，造成端口冲突。请严格参考示例，此应用的Caddyfile示例中可没有使用443端口！
另外你不严格参考示例，也不提供你详细配置，神仙也不知道怎么帮助你！

**Comment by qilinbar** [comment]
就是完全按照你的那个配置里面的Caddyfile 写的，基本没有改动，可是启动的时候提示udp的443被占用，我也知道文件里没使用udp443，才找不出问题所在。我贴下Caddyfile的。
root@yyvps:/etc/caddy# cat Caddyfile
{
	order forward_proxy before route
	order reverse_proxy before forward_proxy
	admin off
	log {
		output file /var/log/caddy/error.log
		level ERROR
	}
	storage file_system {
		root /home/vpstls
	}
	cert_issuer acme
	email your@email.com
	servers 127.0.0.1:88 {
		listener_wrappers {
			proxy_protocol
		}
		protocols h1 h2c
	}
	servers 127.0.0.1:8000 {
		listener_wrappers {
			proxy_protocol
			tls
		}
		protocols h1 h2 h3
	}
}

:80 {
	redir https://{host}{uri} permanent
}

:88 {
	bind 127.0.0.1
	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
	}
	root */var/www/nextcloud
	php_fastcgi unix//run/php/php8.1-fpm.sock php

	file_server {
	}
}

:8000 servicefish.top {
	bind 127.0.0.1

	tls {
		ciphers TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
		curves x25519 secp521r1 secp384r1 secp256r1
	}

	reverse_proxy /SeuW56Es 127.0.0.1:2005 {
		transport http {
			versions h2c 2
		}
	}

	@sgrpc {
		protocol grpc
		path /SALdGZ9k/*
	}
	reverse_proxy @sgrpc 127.0.0.1:2011 {
		transport http {
			versions h2c 2
		}
		flush_interval -1
		header_up X-Real-IP {remote_host}
	}

	forward_proxy {
		basic_auth USER PASS
		hide_ip
		hide_via
		probe_resistance
	}

	route {
		header {
			Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		}
		file_server {
			root /var/www/html
		}
	}
}


再贴一个nginx的，麻烦帮测试下。

nginx

error_log  /var/log/nginx/error.log;
events {
	worker_connections 768;
}
stream {
  # SNI识别，将一个个域名映射成一个配置名
  map $ssl_preread_server_name $stream_map {
    z1.top web;
    z2.top xtls;# 注意这里修改了
  }
 
  # upstream,也就是流量上游的配置
  upstream xtls {
    server 127.0.0.1:9443;
  }
  upstream web {
    server 127.0.0.1:8000;
  }

  # stream模块监听服务器公网IP443端口，并进行端口复用
  server {

    listen 443 reuseport;# 服务器公网ip
    proxy_pass      $stream_map;
    ssl_preread     on;
    proxy_protocol on; # 开启Proxy protocol
   
  }
   server {
        listen 443 udp;
    #    listen [::]:443 udp; #无IPv6，此项可以删除。
        proxy_pass 127.0.0.1:8000; #转给HTTPS server本地监听端口
    } #定向UDP转发配置
}

执行后显示：
root@yyvps:/etc/caddy# caddy run
2023/03/15 07:16:58.504	INFO	using adjacent Caddyfile
2023/03/15 07:16:58.511	INFO	redirected default logger	{"from": "stderr", "to": "/var/log/caddy/error.log"}
Error: loading initial config: loading new config: http app module: start: listen udp 127.0.0.1:443: bind: address already in use
