### ISSUE TITLE
从Xray(M+K+F+C+B+G+A)+Caddy(N)切换至Xray(M+K+F+C+B+G+A)+Caddy(N)+Nginx\HAProxy时，无法连通

### ISSUE THREAD

**Issue by jliveusa** [lxhao61/integrated-examples#147]
nginx version: nginx/1.22.1
built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
built with OpenSSL 1.1.1n  15 Mar 2022
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-g -O2 -ffile-prefix-map=/data/builder/debuild/nginx-1.22.1/debian/debuild-base/nginx-1.22.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'

使用的nginx版本如上，配置文件更改后，nginx、caddy、xray都成功运行，但无法连接上reality分流的相关协议~请问是nginx缺少组件吗？

**Comment by lxhao61** [comment]
你使用UDS连接是吧？注意连接路径名称。

**Comment by lxhao61** [comment]
Xray中VLESS+Vision+REALITY配置有错误：
"dest": "@https",
"xver": 2,
"serverNames": [
"xxx"
],

**Comment by lxhao61** [comment]
另外示例配置Trojan+TCP+TLS的UDS回落有个小错误，已更新，注意修改修改正确。

**Comment by jliveusa** [comment]
使用nginx UDS连接还是不通，暂时用回caddy了，没测试haproxy连通性
