### ISSUE TITLE
Caddy(N+T)/Caddyfile下， 再加入一个普通网页域名应该如何配置？

### ISSUE THREAD

**Issue by leungxt** [lxhao61/integrated-examples#148]
Caddy(N+T)/Caddyfile已配置好，trojan和naiveproxy都可以正常使用，非常感谢。但是服务器上还有其他业务要跑，须再加入一个普通网页域名，在配置最后加入代码如下：

xy.yy {
    gzip
    root /var/www/html
    tls your@gmail.com
}

但是，重启caddy报错。

 请问此种情况应该如何配置？

**Comment by lxhao61** [comment]
不明白你逻辑。此配置已经含网站配置，随便加域名参考CDN配置即可（普通证书不要超过五个）。

**Comment by lxhao61** [comment]
你参考不是最合理的，最优应该是 [V2Ray(B+D+G+A)+Caddy(N+T)](https://github.com/lxhao61/integrated-examples/tree/main/V2Ray(B%2BD%2BG%2BA)%2BCaddy(N%2BT)) 示例。

**Comment by leungxt** [comment]
经测试以下配置测试是可以用的，麻烦再看看有何优化空间？目前是只保留了vmess+tls+websocket，trojan，naiveproxy服务，伪装网站是1.com，另外有个正常网站2.com反代到docker服务的8080端口


{
	order trojan before route
	order forward_proxy before trojan
	order reverse_proxy before forward_proxy
	admin off
	log {
		output file /var/log/caddy/error.log
		level ERROR
	} #版本不小于v2.4.0才支持日志全局配置
	email your@email.com #修改为自己的电子邮箱（选配）

	servers :443 {
		listener_wrappers {
			trojan #caddy-trojan插件应用必须配置
		}
	}
	trojan {
		caddy
		no_proxy
		users password #修改为自己的密码。密码可多组，用空格隔开。
	}
}

:443, 1.com, 2.com { #1.com，2.com修改为自己的域名，可配置多个域名。注意：逗号与域名之间有一个空格。
	tls {
		ciphers TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
                curves x25519 secp521r1 secp384r1 secp256r1
	}

	@vmws {
	    host 1.com
		path /websocket #与VMess+WebSocket应用中path对应
		header Connection *Upgrade*
		header Upgrade websocket
	}
	reverse_proxy @vmws 127.0.0.1:2001 #转发给本机VMess+WebSocket监听端口

	forward_proxy {	    
		basic_auth user pass #NaiveProxy用户与密码，修改为自己的。
		hide_ip
		hide_via
		probe_resistance
	}

	trojan {
		connect_method
		websocket
	} #此部分配置为caddy-trojan插件的WebSocket应用，若删除就仅支持Trojan应用。

	@host1 {
		host 1.com #限定域名访问（禁止以IP方式访问网站），修改为自己的域名。
	}
	route @host1 {
		header {
			Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" #启用HSTS
		}
		file_server {
			root /var/www/html #修改为自己存放的WEB文件路径
		}
	}
	
	@host2 {
		host 2.com #限定域名访问（禁止以IP方式访问网站），修改为自己的域名。
	}
	route @host2 {
		header {
			Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" #启用HSTS
		}
		reverse_proxy 127.0.0.1:8080  #修改为自己需要反代的IP和端口
	}
}

**Comment by lxhao61** [comment]
若你不使用Caddy提供正常网站2.com，那就这样了。
