### ISSUE TITLE
大佬您好，新版怎么没打包alidns验证

### ISSUE THREAD

**Issue by weiyakeji** [lxhao61/integrated-examples#149]
大佬您好，新版怎么没打包alidns验证
2.6.3是有alidns验证的，后面的版本好像没打包alidns验证，大佬可否加上alidns验证

**Comment by lxhao61** [comment]
由alidns解析的域名必须需要实名认证是吧？

**Comment by lxhao61** [comment]
那这样，应该不会再集成alidns插件了。建议使用cloudflare、dnspodcn、duckdns插件实现DNS-01验证申请证书。若实在要alidns简析域名，也可以使用duckdns挑战委托模式间接搞定这个问题。
