### ISSUE TITLE
客户端怎么使用shadowssocks?

### ISSUE THREAD

**Issue by offferu** [lxhao61/integrated-examples#15]
请问这里的shadowsocks怎么用clash或者v2rayng使用？多谢！
https://github.com/lxhao61/integrated-examples/blob/master/v2ray(complete%2Bh2c)%2Bcaddy2%5Cnaiveproxy/3_v2ray_config.json

**Comment by lxhao61** [comment]
https://github.com/lxhao61/integrated-examples/tree/master/v2ray(SS%2Bv2ray-plugin)%2Bcaddy2%5Cnginx
它仅兼容 shadowsocks 客户端的 WebSocket 应用，即只能使用 shadowsocks 客户端配合 v2ray-plugin 插件使用。

你确定clash或者v2rayng支持shadowsocks 客户端的 WebSocket 应用（shadowsocks+v2ray-plugin）？不是仅支持shadowsocks。

**Comment by offferu** [comment]
看描述是支持的
  - name: "ss3"
    type: ss
    server: server
    port: 443
    cipher: chacha20-ietf-poly1305
    password: "password"
    plugin: v2ray-plugin
    plugin-opts:
      mode: websocket # no QUIC now
      # tls: true # wss
      # skip-cert-verify: true
      # host: bing.com
      # path: "/"
      # mux: true
      # headers:
      #   custom: value
SS3第3种类型，https://github.com/Dreamacro/clash/wiki/configuration 
我先改加密类型为chacha20-ietf-poly1305，然后测试下

**Comment by lxhao61** [comment]
嗯。客户端可参考如下链接：
https://github.com/lxhao61/integrated-examples/blob/master/client%20configuration/SS_v2ray-plugin_config.json

**Comment by offferu** [comment]
没测试成功，可能跟yaml格式的缩进有关。另想确认下path是/SS1v2ray 还是shadowsocks下面streamSettings里面的path？

**Comment by lxhao61** [comment]
> 没测试成功，可能跟yaml格式的缩进有关。另想确认下path是/SS1v2ray 还是shadowsocks下面streamSettings里面的path？

当然是dokodemo-door下边ws的path（/SS1v2ray）！v2ray(SS+v2ray-plugin)是多个配置复合实现的。
