### ISSUE TITLE
大佬 caddy(naiveproxy+trojan-go)启动失败

### ISSUE THREAD

**Issue by liaoweiliao521** [lxhao61/integrated-examples#15]
大佬  用naiveproxy单应用没问题  用caddy(naiveproxy+trojan-go)后caddy启动失败
caddy.service - Caddy
     Loaded: loaded (/etc/systemd/system/caddy.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2021-07-22 08:32:57 UTC; 10s ago
       Docs: https://caddyserver.com/docs/
    Process: 31868 ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/config.json (code=exited, status=1/FAILURE)
   Main PID: 31868 (code=exited, status=1/FAILURE)

Jul 22 08:32:57 xfly caddy[31868]: LOGNAME=root
Jul 22 08:32:57 xfly caddy[31868]: USER=root
Jul 22 08:32:57 xfly caddy[31868]: SHELL=/bin/sh
Jul 22 08:32:57 xfly caddy[31868]: INVOCATION_ID=9d22067f163344e9aa951920abb4309e
Jul 22 08:32:57 xfly caddy[31868]: JOURNAL_STREAM=8:239529
Jul 22 08:32:57 xfly caddy[31868]: {"level":"info","ts":1626942777.880168,"msg":"using provided configuration","config_file":"/etc/caddy/config.json","config_adapter":""}
Jul 22 08:32:57 xfly caddy[31868]: {"level":"info","ts":1626942777.880815,"msg":"redirected default logger","from":"stderr","to":"/var/log/caddy/access.log"}
Jul 22 08:32:57 xfly caddy[31868]: run: loading initial config: loading new config: loading http app module: provision http: server https: setting up route handlers: route 0: loading handler modules: position 1: loading module 'trojan': decoding module 'trojan': decoding module config: http.handlers.trojan: json: unknown field "trojan"
Jul 22 08:32:57 xfly systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Jul 22 08:32:57 xfly systemd[1]: caddy.service: Failed with result 'exit-code'.
查看状态显示这些  大佬您抽空看看

**Comment by lgj83** [comment]
你的caddy有caddy-trojan插件吗

**Comment by lxhao61** [comment]
同问。
下载本人最新定制编译的caddy文件才带caddy-trojan插件。

**Comment by liaoweiliao521** [comment]
我记得我昨天下载了您编译的插件

**Comment by lxhao61** [comment]
> 我记得我昨天下载了您编译的插件

那无道理了。建议仔细检查配置。

**Comment by liaoweiliao521** [comment]
我又重新下载了试了下还是不行  又试了试caddy+trojan-go也是那个提示

**Comment by lxhao61** [comment]
> 我又重新下载了试了下还是不行 又试了试caddy+trojan-go也是那个提示

你下载的那个文件？

**Comment by zjy7723** [comment]
是--with github.com/imgk/caddy-trojan 这个插件吗？我自己编译对照你的配置文件试试看可不可以走cdn.

**Comment by liaoweiliao521** [comment]
> > 我又重新下载了试了下还是不行 又试了试caddy+trojan-go也是那个提示
> 
> 你下载的那个文件？caddy_linux_amd64.tar.gz测试无问题；其它两个仅编译，无测试。

就是这个  arm的也试了 都是caddy无法启动  估计是vps的问题  谢谢大佬

**Comment by zjy7723** [comment]
经测试，lxhao61大佬编译的 caddy(naiveproxy+trojan-go)在我vps上trojan协议运行正常，只是我用clash客户端无法套cdn.谢谢大佬的折腾为我们提供了学习的模板。

**Comment by lxhao61** [comment]
> 是--with github.com/imgk/caddy-trojan 这个插件吗？我自己编译对照你的配置文件试试看可不可以走cdn.

是的。

**Comment by lxhao61** [comment]
> 经测试，lxhao61大佬编译的 caddy(naiveproxy+trojan-go)在我vps上trojan协议运行正常，只是我用clash客户端无法套cdn.谢谢大佬的折腾为我们提供了学习的模板。

你caddy使用自己编译的文件，还是使用我编译的文件？具体那种类型文件？以便确定我编译文件是否有错。

**Comment by lxhao61** [comment]
> > > 我又重新下载了试了下还是不行 又试了试caddy+trojan-go也是那个提示
> > 
> > 
> > 你下载的那个文件？caddy_linux_amd64.tar.gz测试无问题；其它两个仅编译，无测试。
> 
> 就是这个 arm的也试了 都是caddy无法启动 估计是vps的问题 谢谢大佬

我无arm环境，无法测试。

**Comment by zjy7723** [comment]
> > 经测试，lxhao61大佬编译的 caddy(naiveproxy+trojan-go)在我vps上trojan协议运行正常，只是我用clash客户端无法套cdn.谢谢大佬的折腾为我们提供了学习的模板。
> 
> 你caddy使用自己编译的文件，还是使用我编译的文件？具体那种类型文件？以便确定我编译文件是否有错。
测试时是用你编译的caddy_linux_amd64.tar.gz

**Comment by liaoweiliao521** [comment]
> > > > 我又重新下载了试了下还是不行 又试了试caddy+trojan-go也是那个提示
> > > 
> > > 
> > > 你下载的那个文件？caddy_linux_amd64.tar.gz测试无问题；其它两个仅编译，无测试。
> > 
> > 
> > 就是这个 arm的也试了 都是caddy无法启动 估计是vps的问题 谢谢大佬
> 
> 检查arm类型的caddy文件编译了trojan-go插件的。无arm环境，我无法实际运行这个测试。

大家都能运行 估计是我这里的问题我再试试  谢谢大佬

**Comment by liaoweiliao521** [comment]
大佬  我之前配置输入错了导致无法启动   已经测试了 amd arm版编译文件没有问题  谢谢大佬
