### ISSUE TITLE
Add vision without reality

### ISSUE THREAD

**Issue by rootergod** [lxhao61/integrated-examples#154]
Hi,
Is it possible to create a new category for vision without reality?
Because in my country, vision without reality works very well, but reality has problems.

**Comment by lxhao61** [comment]
[V2Ray(VLESS+TCP+TLS)+Nginx](https://github.com/lxhao61/integrated-examples/tree/main/V2Ray(VLESS%2BTCP%2BTLS)%2BNginx)、[V2Ray(VLESS+TCP+TLS)+Caddy](https://github.com/lxhao61/integrated-examples/tree/main/V2Ray(VLESS%2BTCP%2BTLS)%2BCaddy)、.......。
