### ISSUE TITLE
Caddy sni 分流后的reality不能正常使用

### ISSUE THREAD

**Issue by choicky** [lxhao61/integrated-examples#157]
不知是否有人尝试过 [Xray(M+K+F+C+B+G+A)+Caddy(N)（由Caddy兼顾SNI分流实现的综合应用。）](https://github.com/lxhao61/integrated-examples/tree/new/Xray(M%2BK%2BF%2BC%2BB%2BG%2BA)%2BCaddy(N))  ？
我今天按这套配置去尝试，reality 不正常，而ws 以及kcp 是正常的。

另外，这种模式下，reality 是不是只能用自己的证书了？否则客户端没办法填写域名给caddy sni 分流

**Comment by lxhao61** [comment]
配置2发现一个BUG，已经修复。若你是参考配置2，那么以更新后为准。
此种模式下当然最优使用自己的证书，否则无必要使用此模式。

**Comment by choicky** [comment]
> 发现配置2一个BUG，已经修复。若你是参考配置2，那么以已更新为准。 此种模式下当然最优使用自己的证书，否则无必要使用此模式。

对，我前两天就是尝试配置2的。
你修复后的版本，已经正常了。多谢。

我大概看了一下，本次修复主要是 caddy.json 中把 `zv.xx.yy` 域名增加进来，限定 `cipher_suites` 和 `curves` 。本次修复的原理是啥呢？

**Comment by lxhao61** [comment]
> > 发现配置2一个BUG，已经修复。若你是参考配置2，那么以已更新为准。 此种模式下当然最优使用自己的证书，否则无必要使用此模式。
> 
> 对，我前两天就是尝试配置2的。 你修复后的版本，已经正常了。多谢。
> 
> 我大概看了一下，本次修复主要是 caddy.json 中把 `zv.xx.yy` 域名增加进来，限定 `cipher_suites` 和 `curves` 。本次修复的原理是啥呢？

使用自己证书当然需要加上 `zv.xx.yy` 域名。`cipher_suites` 和 `curves` 是使用TLSv1.2或TLSv1.3下参数配置。reality配置只能使用TLSv1.3及HTTP/2配置。
