### ISSUE TITLE
好奇下，本项目为啥不显示每次commit具体的对应内容，而是每次commit都像重新创建？

### ISSUE THREAD

**Issue by choicky** [lxhao61/integrated-examples#158]
如题。

本项目更新比较频繁，有时候想看看手头使用的配置是不是要更新， 但因为看不到每次commit具体内容，所以也没办法看出来是否需要微调

**Comment by lxhao61** [comment]
原因：
1、新分支。
2、示例调整基本是整体更改，特别是综合示例个别应用加入及删除。
