### ISSUE TITLE
Caddyfile:87 - Error during parsing: Unexpected '{}' at end of line

### ISSUE THREAD

**Issue by houmie** [lxhao61/integrated-examples#161]
This line seems wrong:

https://github.com/lxhao61/integrated-examples/blob/55024b2deb80c98cfa0e57785e3d7c01cea6e55c/Xray(M%2BK%2BB%2BG%2BA)%2BCaddy(N%2BT)/1_caddy.json#L87

Caddy throws the error: `Caddyfile:87 - Error during parsing: Unexpected '{}' at end of line`

Caddy version: `v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=`

Thanks

**Comment by lxhao61** [comment]
你使用Caddy版本与对应配置不匹配！
你要么使用本项目Caddy v2.6.4对配置配置，要么使用本项目Caddy v2.6.5程序。

**Comment by houmie** [comment]
Thank you for your answer. Sorry, I'm using google translate to understand your message.

You are saying use Caddy v2.6.4 or v2.6.5, correct?
I am using v2.6.4 but it doesn't work.

This is what I have compiled it:
```xcaddy --with github.com/mastercactapus/caddy2-proxyprotocol --with github.com/imgk/caddy-trojan --with github.com/WeidiDeng/caddy-cloudflare-ip --with github.com/caddy-dns/cloudflare```

When I try this:
```xcaddy build v2.6.5 --with github.com/mastercactapus/caddy2-proxyprotocol --with github.com/imgk/caddy-trojan --with github.com/WeidiDeng/caddy-cloudflare-ip --with github.com/caddy-dns/cloudflare```

It throws an error. There is no v2.6.5.

The latest [release](https://github.com/caddyserver/caddy/releases/tag/v2.6.4) is still 2.6.4.

Can you advise please? Thanks

**Comment by lxhao61** [comment]
[本项目Caddy v2.6.5程序](ttps://github.com/lxhao61/integrated-examples/releases/tag/20230421)

**Comment by houmie** [comment]
There is no v2.6.5.

You mean v2.7.0-beta.1 ??

https://github.com/caddyserver/caddy/releases/tag/v2.7.0-beta.1

**Comment by lxhao61** [comment]
> There is no v2.6.5.
> 
> You mean v2.7.0-beta.1 ??
> 
> https://github.com/caddyserver/caddy/releases/tag/v2.7.0-beta.1

不是官方v2.6.5，是[本项目Caddy v2.6.5程序](https://github.com/lxhao61/integrated-examples/releases/tag/20230421)。

**Comment by houmie** [comment]
> 不是官方v2.6.5，是[本项目Caddy v2.6.5程序](https://github.com/lxhao61/integrated-examples/releases/tag/20230421)。

Now I understand. Thank you.

1) So your v2.6.5 already includes `caddy2-proxyprotocol`, `caddy-trojan`, `caddy-cloudflare-ip` and `caddy-dns/cloudflare`. Correct?

2) I don't need xcaddy to compile those plugins above?

3) What will happen in future? Will you merge your v2.6.5 with v2.7.0? Otherwise the two will diverge from each other. 

Thanks

**Comment by lxhao61** [comment]
是的。官方正式版v2.7.0出来后合并。
使用[本项目Caddy v2.6.5程序](https://github.com/lxhao61/integrated-examples/releases/tag/20230421)后，请使用JSON配置，且严格参考示例配置。

**Comment by houmie** [comment]
Do I have to do anything specific to enable JSON for Caddy?

I have simply inserted your JSON sample into /etc/caddy/Caddyfile.

This line fails:
```
"https": {
          "listen": ["127.0.0.1:7443"], 
          "listener_wrappers": [{
            "wrapper": "proxy_protocol"
          },
          {          // HERE IT FAILS !!!!!!!!!!!!!
            "wrapper": "tls" 
          },
          {
            "wrapper": "trojan" 
          }],
```

**Comment by lxhao61** [comment]
晕！！！！！！！
Caddyfile

> 我是否必须执行任何特定操作才能为 Caddy 启用 JSON？
> 
> 我只是将您的 JSON 示例插入到 /etc/caddy/Caddyfile 中。
> 
> 此行失败：
> 
> ```
> "https": {
>           "listen": ["127.0.0.1:7443"], 
>           "listener_wrappers": [{
>             "wrapper": "proxy_protocol"
>           },
>           {          // HERE IT FAILS !!!!!!!!!!!!!
>             "wrapper": "tls" 
>           },
>           {
>             "wrapper": "trojan" 
>           }],
> ```

晕！！！！！！！
Caddyfile配置能转化为JSON配置，但JSON配置不能转化为Caddyfile配置。

**Comment by houmie** [comment]
Mate,  This is your example:

https://github.com/lxhao61/integrated-examples/blob/55024b2deb80c98cfa0e57785e3d7c01cea6e55c/Xray(M%2BK%2BB%2BG%2BA)%2BCaddy(N%2BT)/1_caddy.json


It's called `1_caddy.json`.  So why is it in JSON if Caddy doesn't accept JSON. What are you doing?

**Comment by lxhao61** [comment]
> 伙计，这是你的例子：
> 
> https://github.com/lxhao61/integrated-examples/blob/55024b2deb80c98cfa0e57785e3d7c01cea6e55c/Xray(M%2BK%2BB%2BG%2BA)%2BCaddy(N%2BT)/1_caddy.json
> 
> 它被称为`1_caddy.json`。那么如果 Caddy 不接受 JSON，为什么它在 JSON 中呢？你在干什么？

Caddy使用JSON配置，怎么报错：Error: adapting config using caddyfile: /etc/caddy/Caddyfile:36 - Error during parsing: Unexpected '{' on a new line; did you mean to place the '{' on the previous line?
不可能出现/etc/caddy/Caddyfile，只能出现/etc/caddy/caddy.json！

**Comment by houmie** [comment]
Ahh ok. It's not hard if explained right.

```
mv /etc/caddy/Caddyfile /etc/caddy/caddy.json
vim /lib/systemd/system/caddy.service
-> ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/caddy.json
-> ExecReload=/usr/bin/caddy reload --config /etc/caddy/caddy.json --force
systemctl restart caddy
systemctl daemon-reload
systemctl restart caddy
systemctl status caddy
```

It works now. Thanks

**Comment by houmie** [comment]
Sorry, one more thing.

I managed to get only these two working on my Android phone with **v2rayNG**:
```
VLESS+Vision+REALITY
VMess+WebSocket+TLS
```

But these below didn't work:
```
VLESS+H2C+REALITY
Shadowsocks+gRPC+TLS
VLESS+mKCP+seed
NaiveProxy
Trojan-Go
```

Is there any client configuration for **v2rayNG** for each of these above?
Thanks

**Comment by houmie** [comment]
Never mind. I found them here: https://github.com/lxhao61/integrated-examples/blob/main/Client%20Configuration/xray_vless_h2_reality_config.json

But they are not compatible with the v2rayNG client on Android.  That's very frustrating.  Which Android Client have you used?

**Comment by houmie** [comment]
I understand. Thank you for the explanation. 

Can I ask you a question:


```
"trusted_proxies": {
  "source": "cloudflare",
  "interval": "12h",
  "timeout": "15s"
},
```

This section above is using ```caddy-cloudflare-ip```, but what does it do? If I want to use CDN I have to change Proxy Status --> Proxied.  Why do I need this plugin?

<img width="132" alt="Screenshot 2023-06-05 at 17 29 55" src="https://github.com/lxhao61/integrated-examples/assets/1832933/d3724dd3-fafd-4b8b-99d3-ab01138cd388">

And which protocols are compatible with CDN?
I think only:
```
VLESS+gRPC+TLS
VLESS+WS+TLS
Trojan+gRPC+TLS
VMess+WS+TLS
```
Is this correct?

**Comment by lxhao61** [comment]
晕！示例注释已经告知了呀。
是的。

**Comment by houmie** [comment]
晕！！！

No, the comments in the example are inadequate.  What is this comment:

启用了Cloudflare的CDN配置，需caddy-cloudflare-ip插件支持。???

I can enable CDN by enabling it on the Cloudflare dashboard for my domain. 
Explained [here](https://privacymelon.com/how-to-setup-v2ray-ws-tls-cdn/) and [here](https://samjmck.com/en/blog/using-caddy-with-cloudflare/). 

It is not clear why the plugin is needed, this is why I asked you, but you don't like explaining.  It's ok. LOL

**Comment by lxhao61** [comment]
> 我明白。谢谢你的解释。
> 
> 我可以问你一个问题吗：
> 
> ```
> "trusted_proxies": {
>   "source": "cloudflare",
>   "interval": "12h",
>   "timeout": "15s"
> },
> ```
> 
> 上面的这一部分正在使用`caddy-cloudflare-ip`，但它有什么作用？如果我想使用 CDN，我必须更改代理状态 --> 已代理。为什么我需要这个插件？
> 
> <img alt="屏幕截图 2023-06-05 at 17 29 55" width="132" src="https://user-images.githubusercontent.com/1832933/243415383-d3724dd3-fafd-4b8b-99d3-ab01138cd388.png">
> 哪些协议与 CDN 兼容？ 我认为只有：
> 
> ```
> VLESS+gRPC+TLS
> VLESS+WS+TLS
> Trojan+gRPC+TLS
> VMess+WS+TLS
> ```
> 
> 它是否正确？

你问的是上边"trusted_proxies"配置中`caddy-cloudflare-ip`作用。
仔细看注释：`配置可信CDN服务器的IP范围，实现访问者地址为真实客户端地址。若使用其它非Cloudflare CDN，需自己调整trusted_proxies配置。（可选配）`！难道没有清楚告知吗？
