### ISSUE TITLE
使用进程转发、进程回落\分流无法正常运行网站

### ISSUE THREAD

**Issue by gegehennb** [lxhao61/integrated-examples#17]
您好，我使用了v2ray(vless+tcp&ws+tls)+caddy2\naiveproxy这个配置，caddy2用的您编译的版本，在配置1：端口转发、端口回落\分流的配置下，在浏览器输出域名可以正常访问网页，配置2、3:进程转发、进程回落\分流的配置下，无法访问网页，但xray的ws和tcp模式都可以正常使用，网站都放在/var/www/html文件夹下面。请问您一下，这个问题应该如何解决。谢谢！

**Comment by lxhao61** [comment]
sock进程权限问题。v2ray与caddy2必须对进程有执行权限及读写权限。

**Comment by gegehennb** [comment]
解决了，非常感谢
