### ISSUE TITLE
Nginx reality sni

### ISSUE THREAD

**Issue by linehman** [lxhao61/integrated-examples#171]
Hi, Is it possible to have multiple vless reality inbounds with different destinations on all on the same port 443? I tried using sni routing but couldn't get this to work.

**Comment by lxhao61** [comment]
可以，但不推荐。REALITY自己本来就可多用户。

**Comment by linehman** [comment]
Can you point me to an example guide for this? All the examples that I saw on the main page are one single reality on port 443 with stealing your own domain name.
Also May I know why is it not recommanded?
Kind regards

**Comment by lxhao61** [comment]
参考 [Xray(M+F+B+G+A)+Nginx](https://github.com/lxhao61/integrated-examples/tree/main/Xray(M%2BF%2BB%2BG%2BA)%2BNginx) 示例。把其它的替换成 REALITY 即可。
不推荐原因：同一个服务器上启用多个 REALITY 应用还不如 REALITY 直接启用多个用户。
