### ISSUE TITLE
Trojan on Xray(M+B+D+G+A)+Caddy(N+T) doesn't work on CDN

### ISSUE THREAD

**Issue by houmie** [lxhao61/integrated-examples#173]
There is a problem with Trojan when connecting over z2.xx.yy.  
```
{
    "handle": [{
        "handler": "trojan",
        "connect_method": true,
        "websocket": true
    }]
},
```

It doesn't work.
z2.xx.yy is set to Proxied on CloudFlare:
<img width="134" alt="Screenshot 2023-08-09 at 08 24 43" src="https://github.com/lxhao61/integrated-examples/assets/1832933/426a0aba-adb2-4bae-9905-46512d9dfa4b">

I can see this error message in caddy log.

`
2023/08/09 07:09:57.326 ^[[31mERROR^[[0m        caddy.listeners.trojan  read prefix error, not io, rewind and let normal caddy deal with it: no server TLS configuration available for ClientHello: &{CipherSuites:[49195 49199 49196 49200 52393 52392 49161 49171 49162 49172 156 157 47 53 49170 10 4865 4866 4867] ServerName: SupportedCurves:[X25519 CurveP256 CurveP384 CurveP521] SupportedPoints:[0] SignatureSchemes:[PSSWithSHA256 ECDSAWithP256AndSHA256 Ed25519 PSSWithSHA384 PSSWithSHA512 PKCS1WithSHA256 PKCS1WithSHA384 PKCS1WithSHA512 ECDSAWithP384AndSHA384 ECDSAWithP521AndSHA512 PKCS1WithSHA1 ECDSAWithSHA1] SupportedProtos:[] SupportedVersions:[772 771 770 769] Conn:0xc0004fdf40 config:0xc00030d500 ctx:0xc0006f5c70}
`

Maybe the cipher is incompatible with cloudflare? So how can I do Trojan/Websocket via CDN?

```
"cipher_suites": ["TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256","TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"], "curves": ["x25519","secp521r1","secp384r1","secp256r1"]
```

Afterwards I tried to connect as z3.xx.yy and it works.  So it must have something to do with the cipher on z2.xx.yy that is incompatible with Cloudflare proxy.

**Comment by houmie** [comment]
I have an update.  I made a mistake in client config and was connecting with TCP instead of WS.
Now it works with Trojan-WS-TLS-CDN on z2.xx.yy
And it works with Trojan-TCP-TLS on z3.xx.yy

1) However I still get these TLS errors, should I be worried?

`
2023/08/09 18:42:48.547 ^[[31mERROR^[[0m        caddy.listeners.trojan  read prefix error, not io, rewind and let normal caddy deal with it: no server TLS configuration available for ClientHello: &{CipherSuites:[10794 4867 4865 4866 52393 52392 49195 49199 49196 49200 49171 49172 156 157 47 53] ServerName:brightingsols.dialerhosting.com SupportedCurves:[CurveID(39578) X25519 CurveP256 CurveP384] SupportedPoints:[0] SignatureSchemes:[ECDSAWithP256AndSHA256 PSSWithSHA256 PKCS1WithSHA256 ECDSAWithP384AndSHA384 PSSWithSHA384 PKCS1WithSHA384 PSSWithSHA512 PKCS1WithSHA512] SupportedProtos:[h2 http/1.1] SupportedVersions:[56026 772 771] Conn:0xc000158780 config:0xc00030b800 ctx:0xc00070c4b0}
2023/08/09 18:42:48.919 ^[[31mERROR^[[0m        caddy.listeners.trojan  read prefix error, not io, rewind and let normal caddy deal with it: no server TLS configuration available for ClientHello: &{CipherSuites:[27242 4867 4865 4866 52393 52392 49195 49199 49196 49200 49171 49172 156 157 47 53] ServerName:brightingsols.dialerhosting.com SupportedCurves:[CurveID(6682) X25519 CurveP256 CurveP384] SupportedPoints:[0] SignatureSchemes:[ECDSAWithP256AndSHA256 PSSWithSHA256 PKCS1WithSHA256 ECDSAWithP384AndSHA384 PSSWithSHA384 PKCS1WithSHA384 PSSWithSHA512 PKCS1WithSHA512 PKCS1WithSHA1] SupportedProtos:[h2 http/1.1] SupportedVersions:[23130 772 771] Conn:0xc000158a00 config:0xc00030b800 ctx:0xc00070c5a0}
`

**Comment by lxhao61** [comment]
https://github.com/imgk/caddy-trojan/issues/55

**Comment by houmie** [comment]
I don't think that's related. #55 is about `.lock: Empty lockfile (EOF)` I don't see that in my error messages.
My error message is about the cipher in Trojan.

I will now try your Xray(M+F+B+D+G+A)+Caddy(N) where Trojan configuration is on the side of Xray instead of Caddy. Maybe the problem goes away. I will report back if you like.

**Comment by houmie** [comment]
Ok, Today I have tried your other example [Xray(M+F+B+D+G+A)+Caddy(N)](https://github.com/lxhao61/integrated-examples/tree/main/Xray(M%2BF%2BB%2BD%2BG%2BA)%2BCaddy(N)) and I think Trojan works better with it, because I don't seem to get those Cipher errors. There is one drawback it's a pity that it's not possible to use Trojan + WS. But I think it's ok.

Everything else works with the exception of ShadowSocks, where I created a [new discussion.](https://github.com/lxhao61/integrated-examples/discussions/174).

I think I close this issue then, because I don't think you can fix those cipher errors with Trojan on Caddy.
