### ISSUE TITLE
v2ray/xray ds可能有性能问题

### ISSUE THREAD

**Issue by heheheaa** [lxhao61/integrated-examples#18]
https://github.com/badO1a5A90/Performance/blob/main/performance_test/DS/20201030.md

**Comment by lxhao61** [comment]
看了一下，没明白他的测试环境及目的与实际场景有多大关联。
若没有问题，理论上DS应该比环路处理更好。另外我目前实际使用中，没有发现如他测试那样糟糕，反而是符合理论及预期的。
另外此处是示例配置优化，若软件有问题也只能等待开发解决了。
