### ISSUE TITLE
grpc相关模板中的 传递方式 监听进程，是不能成功的

### ISSUE THREAD

**Issue by chika0801** [lxhao61/integrated-examples#18]
https://github.com/lxhao61/integrated-examples/blob/main/v2ray(vless%5Cvmess%2Bgrpc)%2Bcaddy%5Cnginx/2_nginx.conf

比如在上面的模板中
grpc_pass grpc://unix:/dev/shm/vgrpc.sock; #转发给本机vless+grpc或vmess+grpc监听进程

xray的配置文件也参考你给出的模板

是按你的格式写的配置。启动后，实际情况是会失败。

**Comment by chika0801** [comment]
nginx改为端口            grpc_pass grpc://127.0.0.1:8001;
xray 对就修改，就可以成功。

**Comment by lxhao61** [comment]
> https://github.com/lxhao61/integrated-examples/blob/main/v2ray(vless%5Cvmess%2Bgrpc)%2Bcaddy%5Cnginx/2_nginx.conf
> 
> 比如在上面的模板中
> grpc_pass grpc://unix:/dev/shm/vgrpc.sock; #转发给本机vless+grpc或vmess+grpc监听进程
> 
> xray的配置文件也参考你给出的模板
> 
> 是按你的格式写的配置。启动后，实际情况是会失败。

你肯定没有考虑Unix Domain Socket（dev/shm/vgrpc.sock）权限问题。

**Comment by chika0801** [comment]
> > https://github.com/lxhao61/integrated-examples/blob/main/v2ray(vless%5Cvmess%2Bgrpc)%2Bcaddy%5Cnginx/2_nginx.conf
> > 比如在上面的模板中
> > grpc_pass grpc://unix:/dev/shm/vgrpc.sock; #转发给本机vless+grpc或vmess+grpc监听进程
> > xray的配置文件也参考你给出的模板
> > 是按你的格式写的配置。启动后，实际情况是会失败。
> 
> 你肯定没有考虑Unix Domain Socket连接（dev/shm/vgrpc.sock）权限问题。监听进程与转发进程两者权限不一致。

谢谢解答。是这样的原因。我xray的用户是nobody。请问NGINX的用户是在配置文件里 user nginx; 这一项把nginx改成nobody名字就行了吗？

**Comment by chika0801** [comment]
感谢你的帮助。我谷歌了一下找到解决方法了。
xray用的官方脚本，用户是nobody。要在nginx的配置文件里，它默认的是user nginx;
我改为了user nobody nogroup;

就能使用 传递方式 进程了。

**Comment by aglent** [comment]
我也遇到这个问题，但是进程和端口都无效。
我几乎按照这个模板配置，vless+xtls和trojan+xtls和网站都正常，只有grpc不通，客户端提示【app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection closed] > common/retry: all retry attempts failed】
