### ISSUE TITLE
caddy 的四层转发

### ISSUE THREAD

**Issue by ixxmu** [lxhao61/integrated-examples#19]
大佬编译的caddy支持四层转发么，支持的话能否些个示例配置，谢谢

**Comment by lxhao61** [comment]
已编译支持上传，配置见相关示例。

**Comment by ixxmu** [comment]
> 编译支持的已上传。配置见相关示例。
感谢大佬！！！
有兴趣的可以从大佬的这个配置开始
https://github.com/lxhao61/integrated-examples/blob/master/v2ray(vless%26trojan%2Btcp%26ws%2Btls)%2Bcaddy2/4_caddy.json

再次感谢大佬的无私和辛苦才！
