### ISSUE TITLE
大佬中秋节快乐  请教grpc的问题

### ISSUE THREAD

**Issue by liaoweiliao521** [lxhao61/integrated-examples#19]
大佬  使用v2ray(E+B+C+D+G+A)+caddy(N+T)示例除了grpc连不上  其他的基本都可以链接  请教大佬 应该怎么设置啊

**Comment by liaoweiliao521** [comment]
试了试单独grpc  caddy的配置示例  并且caddy和xray的用户组都是root  还是连不上

**Comment by liaoweiliao521** [comment]
大佬  我的设置错了  示例没问题  相当好用

**Comment by lxhao61** [comment]
谢谢，一样，同乐！
照抄！注意：Xray/V2ray的gRPC应用中serviceName不能带特殊符号！如'/'等！
