### ISSUE TITLE
服务端使用v2ray(vless&trojan+tcp&ws+tls)+nginx -->1_v2ray_config.json配置，客户端使用vless+tls+ws，经常出现报错

### ISSUE THREAD

**Issue by C222l** [lxhao61/integrated-examples#20]
服务端使用v2ray(vless&trojan+tcp&ws+tls)+nginx -->1_v2ray_config.json配置，客户端使用这个配置的vless+tls+ws，会经常出现报错，求大佬解答~！

1、客户端使用v2rayN，报错如下：

2021/01/18 15:23:50 [Warning] [1853737880] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://我的域名/我的path):  > read tcp 192.168.19.53:58185->服务器ip:443: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://我的域名/我的path):  > dial tcp: operation was canceled] > common/retry: all retry attempts failed

2、access.log错误日志如下：

2021/01/18 07:23:50 127.0.0.1:50066 rejected  proxy/vless/encoding: failed to read request version > websocket: close 1000 (normal)
2021/01/18 07:23:51 127.0.0.1:50072 rejected  proxy/vless/encoding: failed to read request version > websocket: close 1000 (normal)

**Comment by lxhao61** [comment]
若你严格参考本示例，配置没有错误。服务端与客户端核心版本完全兼容。无服务端同步日志下，初步判断应该是网络不稳定造成的。

**Comment by C222l** [comment]
> 若你严格参考本示例，配置没有错误。服务端与客户端（核心）版本完全兼容，无服务端同步日志下，初步判断应该是网络不稳定造成的。
> 其它建议：检查一下服务端与客户端（核心）版本是否一致。

多谢大佬回复，我刚才又测了下，应该是网络不稳定造成的，早上网络好没有出现这种问题了，可能是公司网络太渣渣
