### ISSUE TITLE
沃沃沃槽，这个项目太NB了，感激作者

### ISSUE THREAD

**Issue by MhcII** [lxhao61/integrated-examples#21]
虽然我知道不应该在这发，但是还是忍不住发一下，解决了我好久的困扰，感谢作者

**Comment by hedsbj** [comment]
同感

**Comment by lochuan** [comment]
同感，特别是caddy相关的配置

**Comment by qiqiqiao** [comment]
今天啥情况，疯狂提示项目更新。。

**Comment by pengs361** [comment]
感谢作者

**Comment by idavailable** [comment]
非常感谢作者大佬

**Comment by MINGERTAI** [comment]
非常感谢作者大佬
    希望大佬出个Caddyfile分流配置文件
         --with github.com/RussellLuo/caddy-ext/layer4
分流插件地址：https://github.com/RussellLuo/caddy-ext/tree/master/layer4
                                   感谢作者大佬

**Comment by lxhao61** [comment]
> 非常感谢作者大佬 希望大佬出个Caddyfile分流配置文件 --with github.com/RussellLuo/caddy-ext/layer4 分流插件地址：https://github.com/RussellLuo/caddy-ext/tree/master/layer4 感谢作者大佬

https://github.com/lxhao61/integrated-examples/issues/119
