### ISSUE TITLE
手机客户端连不上trojan协议 麻烦帮我看看配置

### ISSUE THREAD

**Issue by aglent** [lxhao61/integrated-examples#22]
我按照这个配置模板 https://github.com/lxhao61/integrated-examples/blob/master/v2ray(vless%26trojan%2Btcp%26ws%2Btls)%2Bnginx/3_v2ray_config.json
实现vless+trojan+h2
电脑端 vless、trojan和https网站正常访问
手机端小火箭 圈x 都无法连接trojan协议
不知道问题出在哪里 能指点下吗？

```json
{
    "log": {
        "loglevel": "none"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "xxxxxx",
                        "flow": "xtls-rprx-direct"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "alpn": "h2",
                        "dest": "@trojan-tcp"
                    },
                    {
                        "dest": "/dev/shm/nginx_unixsocket/default.sock"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "minVersion": "1.2",
                    "cipherSuites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
                    "certificates": [
                        {
                            "certificateFile": "xxxxxx",
                            "keyFile": "xxxxxx",
                            "ocspStapling": 3600
                        }
                    ]
                }
            }
        },
        {
            "listen": "@trojan-tcp",
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password": "xxxxxx",
                        "level": 0,
                        "email": "love@example.com"
                    }
                ],
                "fallbacks": [
					{
						"dest": "/dev/shm/nginx_unixsocket/h2.sock"
					}
				]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "none",
                "tcpSettings": {
                    "acceptProxyProtocol": false
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}

**Comment by lxhao61** [comment]
你配置是参考是配置2（Xray配置），不是配置3，且强制使用服务端密码套件中协议加密（无模板 "preferServerCipherSuites": true,参数）。
1、核实现手机客户端软件是否支持Xray的trojan协议！此处Xray不是v2ray。如支持请补上"preferServerCipherSuites": true,
2、如不支持Xray的trojan协议，支持v2ray的trojan协议。服务端删除Xray独有的相关参数。
3、如现手机客户上述都不支持，换支持trojan的客户端。服务端删除Xray独有的相关参数。

**Comment by aglent** [comment]
按照你的建议，我在上面的配置里添加了"preferServerCipherSuites"语句，还是不能用。
但我把inbound里改成trojan+h2是小火箭是可以使用的。看起来小火箭应该是支持xray的trojan
``json
{
    "log": {
        "loglevel": "none"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password": "110372762",
                        "flow": "xtls-rprx-direct"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "alpn": "h2",
                        "dest": "/dev/shm/nginx_unixsocket/h2.sock"
                    },
                    {
                        "dest": "/dev/shm/nginx_unixsocket/default.sock"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "minVersion": "1.2",
                    "cipherSuites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
                    "certificates": [
                        {
                            "certificateFile": "/usr/local/nginx/certs/cnzj.win.cer",
                            "keyFile": "/usr/local/nginx/certs/cnzj.win.key",
                            "ocspStapling": 3600
                        }
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}

**Comment by lxhao61** [comment]
> 按照你的建议，我在上面的配置里添加了"preferServerCipherSuites"语句，还是不能用。
> 但我把inbound里改成trojan+h2，小火箭是可以使用的。看起来小火箭应该是支持xray的trojan
> 比如下面的配置小火箭是可用的，只是没有了vless，我需要vless和trojan共存。
> 
> ```json
> {
>     "log": {
>         "loglevel": "none"
>     },
>     "inbounds": [
>         {
>             "port": 443,
>             "protocol": "trojan",
>             "settings": {
>                 "clients": [
>                     {
>                         "password": "xxxxxx",
>                         "flow": "xtls-rprx-direct"
>                     }
>                 ],
>                 "decryption": "none",
>                 "fallbacks": [
>                     {
>                         "alpn": "h2",
>                         "dest": "/dev/shm/nginx_unixsocket/h2.sock"
>                     },
>                     {
>                         "dest": "/dev/shm/nginx_unixsocket/default.sock"
>                     }
>                 ]
>             },
>             "streamSettings": {
>                 "network": "tcp",
>                 "security": "xtls",
>                 "xtlsSettings": {
>                     "alpn": [
>                         "h2",
>                         "http/1.1"
>                     ],
>                     "minVersion": "1.2",
>                     "cipherSuites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
>                     "certificates": [
>                         {
>                             "certificateFile": "xxxxxx",
>                             "keyFile": "xxxxxx",
>                             "ocspStapling": 3600
>                         }
>                     ]
>                 }
>             }
>         }
>     ],
>     "outbounds": [
>         {
>             "protocol": "freedom"
>         }
>     ]
> }
> ```

此配置回落无法成功，参考注意事项。

>                 "xtlsSettings": {
>                     "alpn": [
>                         "h2",
>                         "http/1.1"
>                     ],
如上删除"http/1.1"，仅保留"h2",试试就知道了问题了：
1、若正常，之前配置删除"level": 0,就可以了。
2、若不正常，就是你现手机客户端不支持h2连接。换客户端，或仅http/1.1套娃，或SNI分流，trojan http/1.1连接。

另外vless和trojan共存建议采用SNI分流模式才能发挥各自性能。套娃方式trojan不支持xtls。

**Comment by aglent** [comment]
好的 能否给个vless+trojan+nginx的sni分流模板链接
我看的眼花了
