### ISSUE TITLE
请问Nginx前置会比直接xray前置降低多少性能

### ISSUE THREAD

**Issue by gcphym** [lxhao61/integrated-examples#22]
请问像模板这样配置Nginx前置 会比直接xray前置降低多少性能

**Comment by lxhao61** [comment]
取决于你服务器性能，服务器性能越强，对比差距越小。
另外Nginx前置有两种情况，Nginx SNI分流前置及xray前置与Nginx 方向代理前置。反正xray前置肯定优于Nginx前置。
