### ISSUE TITLE
caddy(N+T)下 forwardproxy 功能不正常

### ISSUE THREAD

**Issue by choicky** [lxhao61/integrated-examples#23]
我新开了一个vps，只保留 forwardproxy 的设置，依然不正常，不知道是我的问题，还是因为插件作者不愿意适配caddy v2了。

**Comment by lxhao61** [comment]
请参考对应示例，仔细检查配置！
仅forwardproxy应用，就参考[naiveproxy(caddy+forwardproxy)](https://github.com/lxhao61/integrated-examples/tree/main/naiveproxy(caddy%2Bforwardproxy))应用。
另外本人提供的caddy程序本来就是caddy2集成forwardproxy插件，根本不存在插件作者不愿意适配caddy v2了!

**Comment by choicky** [comment]
> 请参考对应示例，仔细检查配置！不懂就完全参考示例，仅修改注释部分。 仅forwardproxy应用，参考[naiveproxy(caddy+forwardproxy)](https://github.com/lxhao61/integrated-examples/tree/main/naiveproxy(caddy%2Bforwardproxy))应用。 另外本人提供的caddy程序本来就是caddy2集成forwardproxy插件，根本不存在插件作者不愿意适配caddy v2了!

感谢指导。你提供的链接的配置 https://github.com/lxhao61/integrated-examples/blob/main/naiveproxy(caddy%2Bforwardproxy)/naive_caddy.json 是正常的；但我之前参考的是 https://github.com/lxhao61/integrated-examples/blob/main/caddy(N%2BT)/caddy.json ，后者的配置文件我跑不起来。

刚才对比了一下，前者在 `"servers"` 里面的是 `"naive"` ，而后者在  `"servers"` 里面的是 `"https"` 。

**Comment by lxhao61** [comment]
> > 请参考对应示例，仔细检查配置！不懂就完全参考示例，仅修改注释部分。 仅forwardproxy应用，参考[naiveproxy(caddy+forwardproxy)](https://github.com/lxhao61/integrated-examples/tree/main/naiveproxy(caddy%2Bforwardproxy))应用。 另外本人提供的caddy程序本来就是caddy2集成forwardproxy插件，根本不存在插件作者不愿意适配caddy v2了!
> 
> 感谢指导。你提供的链接的配置 https://github.com/lxhao61/integrated-examples/blob/main/naiveproxy(caddy%2Bforwardproxy)/naive_caddy.json 是正常的；但我之前参考的是 https://github.com/lxhao61/integrated-examples/blob/main/caddy(N%2BT)/caddy.json ，后者的配置文件我跑不起来。
> 
> 刚才对比了一下，前者在 `"servers"` 里面的是 `"naive"` ，而后者在 `"servers"` 里面的是 `"https"` 。

两个标记不同不影响使用，只要配置中无重复即可！
猜测应该是你caddy2无caddy-trojan插件，而参考有caddy-trojan插件配置示例。
