### ISSUE TITLE
请教nginx sni分流到各协议和网站的问题

### ISSUE THREAD

**Issue by aglent** [lxhao61/integrated-examples#24]
https://github.com/lxhao61/integrated-examples/blob/master/v2ray(complete%2Btrojan)%2Bnginx/3_nginx.conf
https://github.com/lxhao61/integrated-examples/blob/master/v2ray(complete)%2Bnginx%2Btrojan/2_nginx.conf
我对比了这两个配置文件 区别在于trojan的转发和 传递IP上
是不是只有xray里的trojan监听才支持进程和PROXY protocol？
另外独立的trojan和xray里的trojan 哪个效率更高呢？

**Comment by lxhao61** [comment]
是的，只有xray里的trojan监听才支持进程和PROXY protocol。
效率不好说。效率应该是：trojan-go>xray（trojan+tcp+xtls）>trojan>xray（trojan+tcp+tls）

**Comment by malikshi** [comment]
Somehow I am using cloak > trojan> vmess. It's work with same port. You can try how different performance will you get. I did try with nginx too the usage of RAM for nginx really high.

**Comment by aglent** [comment]
使用PROXY protocol后 nginx的location块内还需要添加 proxy_set_header X-Real-IP 和  proxy_set_header Host 吗？

**Comment by lxhao61** [comment]
完全按照模板设置即可。

**Comment by aglent** [comment]
我还有一事不明 请指点
https://github.com/lxhao61/integrated-examples/blob/master/v2ray(complete%2Btrojan)%2Bnginx/3_nginx.conf
nginx模板里有一段server，监听80端口，然后重定向到https://$host$request_uri，如果我输入zv.xx.yy域名，会访问https://zv.xx.yy，我测试了会提示连接错误，ERR_CONNECTION_CLOSED。这样子会不会影响到代理域名的伪装效果？
如何让两个代理的二级域名也能重定向到/var/www/html页面呢？
