### ISSUE TITLE
求指导：3个域名xray sni分流范例

### ISSUE THREAD

**Issue by leon7786** [lxhao61/integrated-examples#25]
事情来源：
我还在用haproxy基于域名分流trojan和xray，然后看到v1.22 xray升级档说支持sni分流了
但google搜索sni分流，几乎全网都是nginx haproxy分流。
无法找到xray sni分流范例供参考

我看到贵站 sni分流白皮书那种精要缩略讲解，难度太高 怎么都操作不成功~
如果有个从能运行机器复制下载的三域名sni分流范例，复制下来给我们小白参考下，入门难度会大大降低

**Comment by lxhao61** [comment]
你所谓xray sni应该指的是Xray fallbacks SNI shunt吧，但你知道这个实现及原理不？这个跟标准SNI分流没有关系，只是基于名称（域名）判定分流（回落）而已，属于行为描述名词借用，跟你想实现trojan和xray共存无毛关系！
Xray fallbacks SNI shunt无论VLESS fallbacks SNI shunt（对应vless+tcp+tls方式），还是trojan fallbacks SNI shunt（对应trojan+tcp+tls方式），都是解除tls后Xray（vless+tcp+tls或trojan+tcp+tls）进行的name（域名）分流（回落）。
故你怎么实现trojan和xray共存？
另外实际存在v2ray 或 Xray SNI 分流，是通过参数集实现，很麻烦，不推荐。参考链接：https://github.com/lxhao61/integrated-examples/tree/master/v2ray(other%20configuration)
最后若想减少haproxy实现SNI分流，可用WEB服务器nginx或caddy2兼职实现即可，具体参考对应示例即可。

**Comment by leon7786** [comment]
我就是什么都不懂才问能不能替代haproxy sni分流啊，不过我觉得我是问错人了
