### ISSUE TITLE
caddy forward_proxy 提示 json: unknown field "auth_pass"

### ISSUE THREAD

**Issue by meziberry** [lxhao61/integrated-examples#26]
如题 用的你编译的caddy 2.3.0 。配置的forwardproxy. 好像不识别auth_pass字段。不知为什么？搜索未能找到相关的解决方案。

**Comment by lxhao61** [comment]
仔细看下载文件说明！

**Comment by meziberry** [comment]
> 注意此版naiveproxy应用的json配置参数：auth_user改成auth_user_deprecated、auth_pass改成auth_pass_deprecated，否则无法启动。

多谢提醒。谢谢。
