### ISSUE TITLE
xray 0 RTT 无法通过caddy转发的websocket

### ISSUE THREAD

**Issue by ixxmu** [lxhao61/integrated-examples#27]
经过caddy转发的即caddy+vmess/vless+websocket+tls，无法正常使用xray1.4的0 RTT 设置，表现为 在path 后加上?ed=2048就无法连接了。 客户端 服务端全部为1.4 xray。
猜测为caddy 转发到后端websocket时丢失参数？ 
大佬可否看看？ 
谢谢

**Comment by lxhao61** [comment]
已测试无问题。
检查你自己配置，你确定严格参考本人示例的？

**Comment by ixxmu** [comment]
参考配置为[ v2ray(vless\vmess+ws)+caddy2\nginx ](https://github.com/lxhao61/integrated-examples/tree/master/v2ray(vless%5Cvmess%2Bws)%2Bcaddy2%5Cnginx) 中的 1_Caddyfile 或者 1_caddy.json，添加
`?ed=2048`参数后，都无法正常连接。

**Comment by lxhao61** [comment]
cadd2中参数alpn的http/1.1与h2顺序调整一下，试试。

**Comment by ixxmu** [comment]
破案了，是ed 后面的数字太大了，可能caddy的默认header长度不够大，也试着 设置max_header_bytes参数，依旧不能调大header数值。 试了试 ?ed=200 以及以下可以了。

**Comment by lxhao61** [comment]
> 破案了，是ed 后面的数字太大了，可能caddy的默认header长度不够大，也试着 设置max_header_bytes参数，依旧不能调大header数值。 试了试 ?ed=200 以及以下可以了。

那你更新caddy2版本（本人 github中最新版），再试试。我测试没有问题。
另外你配置path是否太长？

**Comment by ixxmu** [comment]
Caddy 不解密TLS直接SNI分流到xray的ws配置没有任何问题，Caddy 解密TLS之后通过path路径分流到xray的ws有问题，在调低ed参数之后200以内可以正常了。 以上确保 caddy 来自大佬你的release最新分支，alpn设置 h2 放在前面。 不纠结了，应该是caddy header的长度问题。 前者ws处理在xray，后者ws经过了caddy的解析后转发。
 谢谢大佬的配文件置示例和编译的caddy，非常清楚的示范。
关闭这个issue了
