### ISSUE TITLE
建议增加gRPC示例

### ISSUE THREAD

**Issue by XMD0718** [lxhao61/integrated-examples#28]
Xray-core的1.4.0版本引入了对 gRPC Transport 的试验性支持，这是第二个能过CDN的传输方式，建议增加相关示例

**Comment by lxhao61** [comment]
https://github.com/lxhao61/integrated-examples/tree/master/v2ray(vless%5Cvmess%2Bgrpc)%2Bcaddy2

**Comment by zytk5142** [comment]
大佬. Xray+xtls.用cloudreve网盘伪装.这个反代配置文件如何与nginx融合？
location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://127.0.0.1:5212;

xray的配置文件是参考您的示例. h1h2端口回落. nginx也是参考您的示例.
谢谢！

lxhao61 ***@***.***> 于 2021年3月19日周五 06:03写道：

**Comment by lxhao61** [comment]
> 大佬. Xray+xtls.用cloudreve网盘伪装.这个反代配置文件如何与nginx融合？ location / { proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header Host $http_host; proxy_redirect off; proxy_pass http://127.0.0.1:5212; xray的配置文件是参考您的示例. h1h2端口回落. nginx也是参考您的示例. 谢谢！

没折腾cloudreve应用。觉得有如下四个办法实现你的应用：
1、cloudreve不要启用tls模块，由nginx提供tls及反代到cloudreve即可。
2、cloudreve不要启用web模块及tls模块，此部分由nginx提供。
上两个具体百度。
3、用SNI域名分流来实现，各自完全独立。
4、用caddy2来实现webdav应用，类似cloudreve应用。

**Comment by zytk5142** [comment]
谢谢大佬

lxhao61 ***@***.***> 于 2021年3月19日周五 13:50写道：
