### ISSUE TITLE
请教vless+ws相关配置

### ISSUE THREAD

**Issue by aglent** [lxhao61/integrated-examples#28]
https://github.com/lxhao61/integrated-examples/blob/main/v2ray(E%2BB%2BF%2BC%2BG%2BA)%2Bnginx/3_v2ray_config.json
我参考这个xray模板，里面有vless+ws相关配置，路径是 /HALdGZ9k，但是我在nginx配置文件里并没有找到 location /HALdGZ9k 这段代码，请问nginx里是否不需要servicename 与xray配置里相对应？

**Comment by lxhao61** [comment]
> https://github.com/lxhao61/integrated-examples/blob/main/v2ray(E%2BB%2BF%2BC%2BG%2BA)%2Bnginx/3_v2ray_config.json 我参考这个xray模板，里面有vless+ws相关配置，路径是 /HALdGZ9k，但是我在nginx配置文件里并没有找到 location /HALdGZ9k 这段代码，请问nginx里是否不需要servicename 与xray配置里相对应？

nginx里不需要servicename 与xray配置里相对应。此vless+ws采用的是回落/分流方式实现的。
