### ISSUE TITLE
关于trojan单一配置回落端口

### ISSUE THREAD

**Issue by kvmb** [lxhao61/integrated-examples#29]
作者您好，我在服务器部署trojan时，发现示例中回落用了81和82端口，如果在trojan服务端remote server填80端口，是否已经实现了http/1.1回落？有必要再单独弄个81端口来给http/1.1回落吗？我的想法是trojan服务端remote server填80，alpn_port_override填81,Nginx监听80端口的http和内网81端口的http2，这么配置是否有问题？同理，如果用caddy，h1和h2c能直接回落80端口吗？

**Comment by lxhao61** [comment]
> 作者您好，我在服务器部署trojan时，发现示例中回落用了81和82端口，如果在trojan服务端remote server填80端口，是否已经实现了http/1.1回落？有必要再单独弄个81端口来给http/1.1回落吗？我的想法是trojan服务端remote server填80，alpn_port_override填81,Nginx监听80端口的http和内网81端口的http2，这么配置是否有问题？同理，如果用caddy，h1和h2c能直接回落80端口吗？

回落端口不用80端口是为了nginx或caddy监听80，实现http自动跳转https，让网站看起来更真实。否则只能https或http与https并存，不符合实际与安全。

**Comment by kvmb** [comment]
> > 作者您好，我在服务器部署trojan时，发现示例中回落用了81和82端口，如果在trojan服务端remote server填80端口，是否已经实现了http/1.1回落？有必要再单独弄个81端口来给http/1.1回落吗？我的想法是trojan服务端remote server填80，alpn_port_override填81,Nginx监听80端口的http和内网81端口的http2，这么配置是否有问题？同理，如果用caddy，h1和h2c能直接回落80端口吗？
> 
> 回落端口不用80端口是为了nginx或caddy监听80，实现http自动跳转https，让网站看起来更真实；否则网站只能https或http与https并存与分离，不符合实际与安全。

回落与跳转在同个端口会冲突吗？不能实现在回落的同时跳转？

**Comment by lxhao61** [comment]
> > > 作者您好，我在服务器部署trojan时，发现示例中回落用了81和82端口，如果在trojan服务端remote server填80端口，是否已经实现了http/1.1回落？有必要再单独弄个81端口来给http/1.1回落吗？我的想法是trojan服务端remote server填80，alpn_port_override填81,Nginx监听80端口的http和内网81端口的http2，这么配置是否有问题？同理，如果用caddy，h1和h2c能直接回落80端口吗？
> > 
> > 
> > 回落端口不用80端口是为了nginx或caddy监听80，实现http自动跳转https，让网站看起来更真实；否则网站只能https或http与https并存与分离，不符合实际与安全。
> 
> 回落与跳转在同个端口会冲突吗？不能实现在回落的同时跳转？

冲突。实现在回落的同时跳转虽然可以，但把简单问题复杂化，不觉得有什么实际意义！
