### ISSUE TITLE
v2ray(vless+tcp+tls+ws+trojan)+nginx 传递请求的真实来源 IP ,"xver":2  的话我这边得不到真实ip

### ISSUE THREAD

**Issue by charley008** [lxhao61/integrated-examples#3]
经过几次测试,发现按你这个来配置得不到真实ip.
然后 我改了一下就可以得到真实ip.

        "fallbacks": [
          {
            "dest": 80, 
            "xver": 0  (2变0就成功了)
          }

**Comment by lxhao61** [comment]
你nginx版本低于1.13.11吧？

**Comment by charley008** [comment]
1.18. 好神奇这个情况.

**Comment by lxhao61** [comment]
> 1.18. 好神奇这个情况.

你具体参考的是配置几？xver为0是不启用proxy protoco，故不可能传递请求的真实来源 IP。除非xver你选1或2开启，1与2表示proxy protoco的版本。理论上版本2应该兼容最好。
