### ISSUE TITLE
使用 hysteria 的问题

### ISSUE THREAD

**Issue by weew2** [lxhao61/integrated-examples#37]
您好，我在使用 hysteria  的 ACME_config.json 配置时，会提示run: loading initial config: loading new config: json: unknown field "acme"，请问如何解决这个问题？

**Comment by lxhao61** [comment]
长时间没有关注，现发现官方修改了认证参数。现在修订好了，重新参考修订好的配置示例试试。如果还有错误，检查服务器的防火墙80/443端口是否放行可入，且没有被其它应用占用。
