### ISSUE TITLE
v2ray(vless+tcp+tls+ws+trojan)+nginx配置之后有异常

### ISSUE THREAD

**Issue by 3kwes** [lxhao61/integrated-examples#4]
PC端V2RAYNG，clash可以正常使用，但是在手机端的v2rayNG,CLASH,Igniter都无法使用，出现io:read/write on closed pipe,服务器则提示v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/trojan: failed to read first request > remote error: tls: bad certificate，相关配置如下：套用5_nginx.conf与5_v2ray_config.json
nginx conf:
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}
stream {
    map $ssl_preread_server_name $backend_name {
        n.518.la trojan;
        y.518.la v2ray;
    }
    upstream trojan {
        server 127.0.0.1:2006;
    }
    upstream v2ray {
        server 127.0.0.1:8443;
    }
    server {
        listen 443 reuseport;
        listen [::]:443 reuseport;
        proxy_pass  $backend_name;
        proxy_protocol on;
        ssl_preread on;
    }
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;
    server_tokens off;
    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    include /etc/nginx/conf.d/*.conf;
	
    server {
        listen 127.0.0.1:80 proxy_protocol;
		listen 127.0.0.1:88 http2 proxy_protocol;
		set_real_ip_from 127.0.0.1;
		charset utf-8;
		location / {
		    root /usr/share/nginx/html;
		    index index.html index.php;
        }
		location ~ \.php$ {
		    fastcgi_pass    127.0.0.1:9000;
		    include         fastcgi_params;
		    fastcgi_param   SCRIPT_FILENAME    $document_root$fastcgi_script_name;
		    fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
	    }
    }
}

v2ray config
{
  "log": {
    "error": "/var/log/v2ray/error.log",
    "access": "/var/log/v2ray/access.log",
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "port": 8443,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "2ed73485-e194-4872-bc8f-808349bcc861",
            "flow": "xtls-rprx-origin"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 80,
            "xver": 2
          },
          {
            "alpn": "h2",
            "dest": 88,
            "xver": 2
          },
          {
            "path": "/HALdGZ9k",
            "dest": 2001,
            "xver": 0
          }
        ]
      },
      "streamSettings": {
        "security": "xtls",
        "xtlsSettings": {
          "alpn":[
            "h2",
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/usr/local/etc/518.la.cer",
              "keyFile": "/usr/local/etc/518.la.key"
            }
          ]
        },
        "network": "tcp",
        "tcpSettings": {
          "acceptProxyProtocol": true
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    },
    {
      "port": 2001,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "2ed73485-e194-4872-bc8f-808349bcc861"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "security": "none",
        "network": "ws",
        "wsSettings": {
          "path": "/HALdGZ9k"
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    },
    {
      "port": 2006,
      "listen": "127.0.0.1",
      "protocol": "trojan",
      "settings": {
        "clients": [
          {
            "password":"TrojanAbc123$"
          }
        ],
        "fallbacks": [
          {
            "dest": 80,
            "xver": 2
          }
        ]
      },
      "streamSettings": {
        "security": "tls",
        "tlsSettings": {
          "alpn":[
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/usr/local/etc/518.la.cer",
              "keyFile": "/usr/local/etc/518.la.key"
            }
          ]
        },
        "network": "tcp",
        "tcpSettings": {
          "acceptProxyProtocol": true
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "blocked"
      }
    ]
  }
}
请大神有空的时候帮忙看看，谢谢

**Comment by 3kwes** [comment]
抱歉，忘记说是手机端使用trojan连接有问题，xtls就都正常

**Comment by lxhao61** [comment]
> 抱歉，忘记说是手机端使用trojan连接有问题，xtls就都正常

查看你配置及告知情况来判断，觉得应该是你域名、服务版本或trojan手机客户端问题。你要知道，v2ray trojan也是刚刚支持，手机客户端很多还不支持，或仅测试版刚支持。
解决办法：
1、检查对应trojan域名解析配置没？
2、服务器是最新版本没？
3、选择正确手机客户端，如选v2rayNG客户端，请选最新测试版。或选用trojan官方客户端等

**Comment by 3kwes** [comment]
嗯嗯，是的，非常抱歉，是证书问题，使用fullchain.cer就没有问题了
