### ISSUE TITLE
关于caddy2 proxy_protocol问题

### ISSUE THREAD

**Issue by guigeng** [lxhao61/integrated-examples#4]
sni分流，我设置了"proxy_protocol":"v2"反而不行，这一条不加反而正常
编译的时候是加了这个module的。
不知道问题出在哪里。

**Comment by lxhao61** [comment]
PROXY protocol应用分发端与接收端，一旦启用，必须同时启用。

**Comment by guigeng** [comment]
搞定了。谢谢你分享的配置
