### ISSUE TITLE
Caddy 做前端，转发grpc到v2ray，log里很多error 记录

### ISSUE THREAD

**Issue by Remonli** [lxhao61/integrated-examples#46]
log里面一堆这种错误，
```
{"level":"error","ts":1650916197.6527233,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"stream error: stream ID 31; CANCEL"}
{"level":"error","ts":1650916197.6527958,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream error: stream ID 31; CANCEL"}
```
我搜了一下，caddy作者说这个没办法解决，https://caddy.community/t/aborting-with-incomplete-response/10990 ,
请问把grpc换成h2c的话，有没有类似报错了？

**Comment by lxhao61** [comment]
一样，caddy反代gRPC是基于h2c的。
可调整日志级别为PANIC或排除http.handlers.reverse_prox。

**Comment by Remonli** [comment]
好吧，我调整设置 exclude http.handlers.reverse_proxy 排除算了，不然一堆err实在是不好看。

另外我看你更新文件把order reverse_proxy before map 改成 order reverse_proxy before route,
这个有什么性能区别吗？

**Comment by lxhao61** [comment]
嗯，是的。
没有区别，仅标识容易理解些。
