### ISSUE TITLE
大佬 trojan-ws xui得配置怎么写

### ISSUE THREAD

**Issue by RatedR9** [lxhao61/integrated-examples#48]
xui默认模板无trojan-ws

**Comment by lxhao61** [comment]
x-ui面板？若没有你只能找x-ui作者。

**Comment by lxhao61** [comment]
首先你自己检查docker配置问题，然后检查是否与示例一一致。

**Comment by RatedR9** [comment]
大佬 有tg吗我用无docker试了一下 配置用的是https://raw.githubusercontent.com/lxhao61/integrated-examples/main/v2ray(trojan%2BWS)%2Bcaddy%5Cnginx/1_v2ray_config.json
nginx 用的是对应得
但是还是连不上

**Comment by RatedR9** [comment]
感谢大佬
