### ISSUE TITLE
haproxy-caddy-xray第一次获取证书的问题

### ISSUE THREAD

**Issue by guigeng** [lxhao61/integrated-examples#5]
haproxy监听443，sni转发
caddy监听88接受回落，80做301跳转，7443做https站点
xray使用unix socket
那么第一次获取证书的时候，是不是通过普通配置的caddy监听80 443端口来获取证书？

搞得有点糊涂了。

**Comment by lxhao61** [comment]
caddy 监听80（80做301跳转）来回去证书的。

**Comment by guigeng** [comment]
那请问一下，80做了跳转是否影响http方式获取证书？

**Comment by lxhao61** [comment]
不影响。
