### ISSUE TITLE
虚心求教 caddy 与 xray 的配置

### ISSUE THREAD

**Issue by choicky** [lxhao61/integrated-examples#52]
首先感谢大佬分享的配置，这几年我都是参考你的配置在用。这期间，也有一些疑问自己解决不了，汇总一下在这里请教。

### 我的架构
因为有三个网站 `a.example.com` `b.example.com`  `c.example.com`，所以我是 `caddy` 前置，`xray` 在后端。

因为想尝试 `xtls` ，所以 `caddy` 最初按照 [1_SNI_caddy.json](https://github.com/lxhao61/integrated-examples/blob/main/caddy(other%20configuration)/1_SNI_caddy.json) 的方式做了sni 分流：`a.example.com` 分流到 `xray`，`b.example.com` 和 `c.example.com` 分流到 `7443` 的 https web 服务。

我对 `json` 不熟，所以我习惯先写好 `Caddyfile` ，然后使用 `caddy adapt --config /path/to/Caddyfile` 去转换成 `json`, 然后取 `http` 部分的内容去替换借到 [1_SNI_caddy.json](https://github.com/lxhao61/integrated-examples/blob/main/caddy(other%20configuration)/1_SNI_caddy.json) 的对应部分。

 `Caddyfile` 中，写了 `https://a.example.com:7443 { }` 这种毫无内容的 `block` ，目的是让 `caddy` 自动获取 `a.example.com` 证书给 `xray` 使用。

### 关于 xray 回落后的网站
我的 `xray` 会回落到 `a.example.com` 的 http 网站，端口88。配置是参考 [1_Caddyfile](https://github.com/lxhao61/integrated-examples/blob/main/v2ray(vless%5Ctrojan%2Btcp%2Btls)%2Bcaddy/1_Caddyfile) （用 caddy adapt  转成 `json` ），但是，我必须在头部的全局配置中增加 `http_port 88` ，否则访问不了 `a.example.com` 网站，不知道原因是什么，这是想请教的第一个问题。

此外，我发现删除 `auto_https off` 也能跑，所以我的全局配置中没有 `auto_https off` 。  `auto_https off` 作用究竟是什么呢？这是第二个想请教的问题。

### 关于 Unix Socket 的监听
据说 Unix Socket 性能更好，为了心里舒服，我参考 [2_SNI_caddy.json](https://github.com/lxhao61/integrated-examples/blob/main/caddy(other%20configuration)/2_SNI_caddy.json) 把 `a.example.com` 分流道 `unix//dev/shm/vless.sock` ，这一部分能正常跑。但是，另外两个网站分流到 `unix//dev/shm/https.sock` 的话，就不正常了，访问不了。即使我参考 [shunt_Caddyfile](https://github.com/lxhao61/integrated-examples/blob/main/caddy(other%20configuration)/shunt_Caddyfile)  的方式分别搞了 `@host1` 对应 `b.example.com` 、 `@host2` 对应 `c.example.com` 也不行。所以，第三个问题是，caddy 能不能把两个域名 sni 分流到  `unix//dev/shm/https.sock` ？

### 网站下面的 forward_proxy 和 reverse_proxy
我曾经参考 [3_naive_Caddyfile](https://github.com/lxhao61/integrated-examples/blob/f90fdcfeb256708a242c54c51dbbae3f01b37066/v2ray(E%2BB%2BC%2BD%2BG%2BA)%2Btrojan%2Bnaiveproxy%2Bnginx%5Chaproxy/3_naive_Caddyfile)  之类的配置， 想在 `b.example.com` 和 `c.example.com` 中附加跑  `forward_proxy` 和 `reverse_proxy` ；但是， `forward_proxy` 和 `reverse_proxy`  没有 `同时` 成功过。后来在 `order reverse_proxy first` 的粗暴调序下成功跑了 `reverse_proxy` ，也就是 `gRPC` 。想请教的第四个问题就是，我的配置究竟是哪里出了问题... 

### @开头的 Unix Socket
我见 [2_v2ray_config](https://github.com/lxhao61/integrated-examples/blob/main/v2ray(E%2BB%2BC%2BG%2BA)%2Bnginx/2_v2ray_config.json) 中有些  Unix Socket 是 `"@vless-ws` 这样的，不知其与 `/dev/shm/h1.sock` 这样的差异在哪？我之前搜索，没搜到相关内容，可能是关键词没用对。

**Comment by lxhao61** [comment]
看了你求教信息，发现你最大的问题是没有仔细看说明及标识，从而造成选择参考示例的方法不对。
如：caddy SNI 分流目前仅支持使用 json 配置；[caddy SNI 分流的配置方法](https://github.com/lxhao61/integrated-examples/tree/main/caddy(other%20configuration)专门提示了“相关示例已配置 caddy SNI 分流共用端口，此配置仅备份及参考等。”。

针对“我的架构”你参考 https://github.com/lxhao61/integrated-examples/tree/main/v2ray(E%2BB%2BF%2BC%2BD%2BG%2BA)%2Bnaiveproxy 示例即可。

针对“关于 xray 回落后的网站”：auto_https off 已标识禁用自动https，与你增加 http_port 88 改88端口为默认http端口从而也实现禁用自动https。不同方法实现相同作用，但不推荐（影响自动跳转）。

针对“关于 Unix Socket 的监听”问题见上针对“我的架构”参考示例，分流域名可以多个的。

针对“网站下面的 forward_proxy 和 reverse_proxy”问题，它们有执行先后顺序的，且 forward_proxy 插件是外部插件需要定义执行点。另外 forward_proxy  插件不支持匹配器限制等，如域名等。

针对“@开头的 Unix Socket”问题这个是Unix domain socket的abstract应用，不必考虑绝对路径，作用一样。见 https://xtls.github.io/config/features/fallback.html#fallbackobject 与 https://xtls.github.io/config/inbound.html#inboundobject 。

**Comment by choicky** [comment]
@lxhao61 
感谢回复，虽然我还是没找到解决问题的答案  😋

我知道 sni分流只支持json，我也是使用json的，只是有一些json中 http 这个block 的内容是Caddyfile 转换过来的而已。

"sni": ["b.example.com","c.example.com"] 这个写法我知道，只是后续 caddy 从 https.sock 接受数据后，好像就不对了，总之是没办法访问 b 和 c 这两个网站。

**Comment by choicky** [comment]
目前，我通过 "sni": ["b.example.com","c.example.com"]  分流到 7443 端口，这种情况下， caddy 监听 7443 端口是能正常跑 b 和c 两种网站的。但是，如果分流到  https.sock ，就不正常了。

**Comment by lxhao61** [comment]
检查caddy的HTTPS服务监听进程采用Unix Domain Socket是否开启了HTTP/3，这个是冲突的；必须关闭或删除此项参数。

**Comment by lxhao61** [comment]
> @lxhao61 感谢回复，虽然我还是没找到解决问题的答案  yum
> 
> 我知道 sni分流只支持json，我也是使用json的，只是有一些json中 http 这个block 的内容是Caddyfile 转换过来的而已。
> 
> "sni": ["b.example.com","c.example.com"] 这个写法我知道，只是后续 caddy 从 https.sock 接受数据后，好像就不对了，总之是没办法访问 b 和 c 这两个网站。

严格参考示例，没有解决不了问题！除非还是认为 Caddyfile 转换的就是对的。
