### ISSUE TITLE
您好博主大哥.

### ISSUE THREAD

**Issue by rianjskis** [lxhao61/integrated-examples#56]
可以来个xray内核的.vless+tcp+xtls +trojan+tcp+tls  +nginx的分流回落配置吗， 我弄了好多次nginx都没法强制跳转https，哈哈哈

**Comment by lxhao61** [comment]
参考如下两者之一即可。
[以套娃方式兼顾各应用的综合应用](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(E%2BB%2BC%2BF%2BA)%2Bnginx)
[以nginx SNI兼顾各应用的综合应用](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(E%2BB%2BF%2BC%2BG%2BA)%2Bnginx)

**Comment by rianjskis** [comment]
> 参考如下两者之一即可。 [以套娃方式兼顾各应用的综合应用](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(E%2BB%2BC%2BF%2BA)%2Bnginx) [以nginx SNI兼顾各应用的综合应用](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(E%2BB%2BF%2BC%2BG%2BA)%2Bnginx)

感谢，

**Comment by rianjskis** [comment]
[1_nginx.conf](https://github.com/lxhao61/integrated-examples/blob/main/v2ray(E%2BB%2BC%2BF%2BA)%2Bnginx/1_nginx.conf)
[1_v2ray_config.json](https://github.com/lxhao61/integrated-examples/blob/main/v2ray(E%2BB%2BC%2BF%2BA)%2Bnginx/1_v2ray_config.json)
您好作者老哥，当我按照这2个模版配置后，nginx跟xray启动正常，但是我依然可以用IP访问域名内容，http访问域名也没有跳转https.使用81端口也是进入域名，82拒绝连接，https直接进入才是400.请教下如何解决

**Comment by rianjskis** [comment]
是不是我之前申请证书的问题，这台机子，当时是用的默认的acme+nginx申请的证书

**Comment by lxhao61** [comment]
不推荐反向代理本身域名的伪装网站，会造成科学上网IP与伪装网站的IP不一致。
nginx不支持h2/h2c proxy，无法实现。
caddy支持h2/h2c proxy，可以实现。

**Comment by rianjskis** [comment]
好的感谢
