### ISSUE TITLE
通过 Github Actions 编译 Caddy

### ISSUE THREAD

**Issue by Johnshall** [lxhao61/integrated-examples#58]
请问是否可以通过 Github Actions 编译和发布 Caddy？
如果可以的话，我可以完成编译、上传的 workflow 的工作。

**Comment by lxhao61** [comment]
可以，你折腾吧。

**Comment by Johnshall** [comment]
请问是否可以提供一下构建的指令呀？

**Comment by lxhao61** [comment]
linux
xcaddy build --output caddy --with github.com/mholt/caddy-l4 --with github.com/mholt/caddy-dynamicdns --with github.com/caddy-dns/alidns --with github.com/caddy-dns/cloudflare --with github.com/caddy-dns/dnspod --with clevergo.tech/caddy-dnspodcn --with github.com/caddy-dns/duckdns --with github.com/mastercactapus/caddy2-proxyprotocol --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive --with github.com/imgk/caddy-trojan@509ea098182a5d3a0e9a0e3a5417b1b25ea15c40 --with github.com/mholt/caddy-webdav

windows
xcaddy build --with github.com/mholt/caddy-l4 --with github.com/mholt/caddy-dynamicdns --with github.com/caddy-dns/alidns --with github.com/caddy-dns/cloudflare --with github.com/caddy-dns/dnspod --with clevergo.tech/caddy-dnspodcn --with github.com/caddy-dns/duckdns --with github.com/mastercactapus/caddy2-proxyprotocol --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive --with github.com/imgk/caddy-trojan@509ea098182a5d3a0e9a0e3a5417b1b25ea15c40 --with github.com/mholt/caddy-webdav

**Comment by Johnshall** [comment]
> Aoooo, 7z能不能换成zip或者tar呀，7z命令不常用

https://github.com/lxhao61/integrated-examples/pull/60
宠粉不？

**Comment by azoway** [comment]
--with github.com/imgk/caddy-trojan@509ea098182a5d3a0e9a0e3a5417b1b25ea15c40 \

@lxhao61 
为啥没用最新的构建呢：
--with github.com/imgk/caddy-trojan

**Comment by lxhao61** [comment]
> --with github.com/imgk/caddy-trojan@509ea098182a5d3a0e9a0e3a5417b1b25ea15c40 \
> 
> @lxhao61 为啥没用最新的构建呢： --with github.com/imgk/caddy-trojan

最新构建的配置无条理及繁琐，已提建议希望作者改进。
