### ISSUE TITLE
nginx-xray unix socket方式的问题

### ISSUE THREAD

**Issue by guigeng** [lxhao61/integrated-examples#6]
使用nginx sni分流方式的时候，开启proxy protocol会出现证书的问题
采用端口转发启用proxy protocol正常。

nginx版本是mainline版本，nginx1.21

不知道问题出在哪里。

**Comment by lxhao61** [comment]
没明白你问的问题与你描述的情况有什么对应？无法判定你什么情况。
我猜测你可能因为权限问题，造成的unix socket连接不通问题。
另外建使用nginx1.20版，我就nginx sni分流，unix socket连接且开启开启proxy protocol，无问题。

**Comment by guigeng** [comment]
nginx.conf里面的user设置的是root。权限应该没问题。
我再测试1.20版本试试

**Comment by lxhao61** [comment]
> nginx.conf里面的user设置的是root。权限应该没问题。
> 我再测试1.20版本试试

unix socket权限还需考虑接受方。
