### ISSUE TITLE
您好作者.请问使用如下xray配置配置Caddy进行回落反代别的网站参考那个配置。

### ISSUE THREAD

**Issue by rianjskis** [lxhao61/integrated-examples#63]
{
    "log": {
        "access": "",
        "error": "",
        "loglevel": "warning"
    },
    "dns": {
        "servers": [
            "https+local://1.1.1.1/dns-query"
        ],
        "queryStrategy": "UseIPv4"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "block"
            }
        ]
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": ""
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": "81",
                        "xver": 1
                    },
                    {
                        "path": "/vmess",
                        "dest": "83",
                        "xver": 1
                    },
                    {
                        "alpn": "h2",
                        "dest": "84",
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "rejectUnknownSni": true,
                    "minVersion": "1.2",
                    "certificates": [
                        {
                            "certificateFile": "",
                            "keyFile": ""
                        }
                    ]
                }
            }
        },
        {
            "listen": "127.0.0.1",
            "port": 83,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": ""
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "/vmess"
                },
                "sockopt": {
                    "acceptProxyProtocol": true
                }
            }
        },
        {
            "listen": "127.0.0.1",
            "port": 84,
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password": ""
                    }
                ],
                "fallbacks": [
                    {
                        "dest": "82",
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "sockopt": {
                    "acceptProxyProtocol": true
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIPv4"
            },
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "settings": {
                "response": {
                    "type": "http"
                }
            },
            "tag": "block"
        }
    ]
}

**Comment by lxhao61** [comment]
没有反代别的网站示例，也不推荐。

最接近你的需求参考如下示例：
1、[由套娃方式实现的综合应用](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(E%2BB%2BC%2BF%2BA)%2Bcaddy)
2、[由caddy兼顾SNI分流实现的综合应用](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(E%2BB%2BF%2BC%2BD%2BG%2BA)%2Bnaiveproxy)

以上反代别的网站方法：
原配置：
```
            {
              "handler": "file_server",
              "root": "/var/www/html" //修改为自己存放的WEB文件路径
            }]
```
修改为如下：
```
            {
              "handler": "reverse_proxy",
              "transport": {
                "protocol": "http",
                "tls": {}
              },
              "headers": {
              	"request": {
                  "set": {
                    "Host": ["{http.reverse_proxy.upstream.hostport}"]
                  }
              	}
              },
              "upstreams": [{
                "dial": "xz.yz:443" //xz.yz为别的https网站。注意：此网站需支持http/1.1与http/2，如caddy开启了http/3，还需支持支持http/3。
              }]
            }]
```

**Comment by rianjskis** [comment]
> 没有反代别的网站示例，也不推荐（反代别的网站，会造成科学上网IP与伪装网站的IP不一致。）。
> 
> 最接近你的需求参考如下示例： 1、[由套娃方式实现的综合应用](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(E%2BB%2BC%2BF%2BA)%2Bcaddy) 2、[由caddy兼顾SNI分流实现的综合应用](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(E%2BB%2BF%2BC%2BD%2BG%2BA)%2Bnaiveproxy)
> 
> 以上反代别的网站方法： 原配置：
> 
> ```
>             {
>               "handler": "file_server",
>               "root": "/var/www/html" //修改为自己存放的WEB文件路径
>             }]
> ```
> 
> 修改为如下：
> 
> ```
>             {
>               "handler": "reverse_proxy",
>               "transport": {
>                 "protocol": "http",
>                 "tls": {}
>               },
>               "headers": {
>               	"request": {
>                   "set": {
>                     "Host": ["{http.reverse_proxy.upstream.hostport}"]
>                   }
>               	}
>               },
>               "upstreams": [{
>                 "dial": "xz.yz:443" //xz.yz为别的https网站
>               }]
>             }]
> ```
> 
> 注意： 1、xz.yz网站需支持http/1.1与http/2。如caddy开启了http/3，还需xz.yz网站支持http/3。 2、如xz.yz网站已经支持HSTS，那么需要删除caddy开启HSTS配置。

感谢您的解答，您配置中的反代是本机自建的伪装网站吧，请问caddy可以把http跟h2分开写吗，看您的配置都是合并在一起，如果可以的话，请问该如何写😂😂

**Comment by lxhao61** [comment]
本机自建伪装网站不需要反代！这个反代是别人https网站！
caddy不需要HTTP/1.1跟h2c分开！caddy 支持 HTTP/1.1 server 与 H2C server 共用一个端口或一个进程。

**Comment by rianjskis** [comment]
> 这个机器自建反伪装另一个网站不需要反代！ caddy不需要HTTP/1.1跟H2C！caddy支持HTTP/1.1服务器和H2C服务器共用一个或者端口一个进程。

如上述我想实现的那个xray配置中http与h2使用端口不一致，该如何在caddy实现，😂😂

**Comment by lxhao61** [comment]
> > 这个机器自建反伪装另一个网站不需要反代！ caddy不需要HTTP/1.1跟H2C！caddy支持HTTP/1.1服务器和H2C服务器共用一个或者端口一个进程。
> 
> 如上述我想实现的那个xray配置中http与h2使用端口不一致，该如何在caddy实现，joyjoy

你使用caddy就不要用nginx对应的xray配置来折腾！你参考caddy对应配置即可！那里来的粉末倒置，无语！！

**Comment by rianjskis** [comment]
> > > 这个机器自建反伪装另一个网站不需要反代！ caddy不需要HTTP/1.1跟H2C！caddy支持HTTP/1.1服务器和H2C服务器共用一个或者端口一个进程。
> > 
> > 
> > 如上述我想实现的那个xray配置中http与h2使用端口不一致，该如何在caddy实现，joyjoy
> 
> 你使用caddy就不要用nginx对应的xray配置来折腾！你参考caddy对应配置即可！把配置复杂化，无语！！

好的感谢，😂

**Comment by rianjskis** [comment]
> > > 这个机器自建反伪装另一个网站不需要反代！ caddy不需要HTTP/1.1跟H2C！caddy支持HTTP/1.1服务器和H2C服务器共用一个或者端口一个进程。
> > 
> > 
> > 如上述我想实现的那个xray配置中http与h2使用端口不一致，该如何在caddy实现，joyjoy
> 
> 你使用caddy就不要用nginx对应的xray配置来折腾！你参考caddy对应配置即可！把配置复杂化，无语！！

抱歉老哥，属实是本末倒置了我，nginx不支持http1跟h2为一个端口跟进程，分开的http1跟h2还容易变成全http，caddy完美支持了二合一，我还想给他拆开，属实走远了，所以来和老哥道个歉，给你整闷了😂😂
