### ISSUE TITLE
大佬，Caddy v2.5.3 为什么突然找不到了

### ISSUE THREAD

**Issue by SQLimit** [lxhao61/integrated-examples#64]
我记得前几天是有2.5.3版本的下载的，为什么找不到了，Caddy官网也只有2.5.2，是我记忆出现错乱了吗。想使用Caddy反代进程转发gRPC，但一定要2.5.3版本。

**Comment by lxhao61** [comment]
官方caddy最新源码（master）即正在开发的2.5.3源码，Caddyfile配置有bug，且HTTP/3与H2C Server配置启用参数有调整，故删除了等待正式2.5.3版本出来（希望无bug了）。

**Comment by SQLimit** [comment]
> 官方caddy最新源码（master）即正在开发的2.5.3源码当前还不成熟：Caddyfile配置有bug，且H2C与HTTPS/3 Server配置启用参数有调整；故删除等待正式2.5.3版本出来（希望无bug）。 2.5.3版本只是解决了H2C Proxy 的UDS转发，建议当前先使用2.5.2版本。

明白了，谢谢大佬！

**Comment by lxhao61** [comment]
向caddy官方报告bug了，官方计划v2.6.0-beta.1版本修复。

**Comment by lxhao61** [comment]
bug已经修复，可以去本人Releases中下载[caddy_v2.6.0-beta.3](https://github.com/lxhao61/integrated-examples/releases/tag/20220916)测试。

**Comment by SQLimit** [comment]
> bug已经修复，可以去本人Releases中下载[caddy_v2.6.0-beta.3](https://github.com/lxhao61/integrated-examples/releases/tag/20220916)测试。

已下载，谢谢大佬！

**Comment by lxhao61** [comment]
不好意思，编译少加一个master参数，老源码编译了。等下重新下载最新版本。

**Comment by Remonli** [comment]
@lxhao61 v2ray 5 开始好像要切换到新格式v5的配置文件，有没有计划迁移到v5的配置格式？

**Comment by lxhao61** [comment]
> @lxhao61 v2ray 5 开始好像要切换到新格式v5的配置文件，有没有计划迁移到v5的配置格式？

没有。除非v2ray v5核心亮点超过Xray。
