### ISSUE TITLE
v2ray(trojan+ws)+caddy2\nginx－手机端用v2RayNG可以ping通，但是无法联网

### ISSUE THREAD

**Issue by iKira** [lxhao61/integrated-examples#7]
我按照 v2ray(trojan+ws)+caddy2\nginx 里的模板配置了，手机端用Android版v2RayNG连接，测试可以ping通，但就是无法联网（国内外网站都不行），请帮我排查下是什么原因，谢谢。

**### 下面是v2Ray服务端配置：**

{

	"log": {
		"error": "xxxx",
		"access": "xxxx",
		"loglevel": "warning"
     },

	"stats": {},
	"api": {
		"tag": "api",
		"services": [
			"HandlerService",
			"LoggerService",
			"StatsService"
		]
	},

	"policy": {
		"levels": {
			"0": {
				"statsUserUplink": true,
				"statsUserDownlink": true
			},
			"1": {
				"statsUserUplink": true,
				"statsUserDownlink": true
			}
		},
		"system": {
			"statsInboundUplink": true,
			"statsInboundDownlink": true
		}
	},

	"inbounds": [
		{
			"listen": "127.0.0.1",
			"port": 8888,
			"protocol": "trojan",
			"settings": {
				"clients": [
					{
						"password":"hhhhhhhhhhhhhh",
						"email": "xxxxxxxx"
					}
				]
			},

			"streamSettings": {
				"security": "none",
				"network": "ws",
				"wsSettings": {
					"path": "/ffffffffffff/"
				}
			},
			
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			}
		},

		{
			"listen": "127.0.0.1",
			"port": xxxxx,
			"protocol": "dokodemo-door",
			"settings": {
				"address": "127.0.0.1"
			},
			"tag": "api"
		}
	],

	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {}
		}
	],

	"routing": {
		"domainStrategy": "IPIfNonMatch",
		"settings": {
			"rules": [
				{
					"inboundTag": [
						"api"
					],
					"outboundTag": "api",
					"type": "field"
				}
			]
		},
		"strategy": "rules"
	}
}

**### 下面是nginx配置：**

server {
	server_name www.xxx.com;
	listen 443 ssl;
	ssl_certificate /xxxx/cert/www.xxx.com/ssl.pem;
	ssl_certificate_key /xxxx/cert/www.xxx.com/ssl.key;
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
	ssl_prefer_server_ciphers off;
	ssl_session_timeout 1d;
	ssl_session_cache shared:MozSSL:10m;
	ssl_session_tickets off;
		location / {
			root /xxxx/web/www.xxx.com;
			index index.html;
		}
		location = /ffffffffffff/ {
			proxy_redirect off;
			proxy_pass http://localhost:8888;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $http_host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		}
}

**### 下面是v2RayNG客户端配置：**

{
	"log": {
		"loglevel": "none"
	},

	"inbounds": [
		{
			"port": xxxx,
			"listen": "127.0.0.1",
			"protocol": "socks",
			"settings": {
				"udp": true
			}
		}
	],
	
	"outbounds": [
		{
			"protocol": "trojan",
			"settings": {
				"servers": [
					{
						"address": "www.xxx.com",
						"port": 443,
						"password": "hhhhhhhhhhhhhh"
					}
				]
			},
			
			"streamSettings": {
				"network": "ws",
				"security": "tls",
				"tlsSettings": {
					"allowInsecure": false,
					"allowInsecureCiphers": true,
					"serverName": "www.xxx.com"
				},
				"wsSettings": {
					"headers": {
						"Host": ""
					},
					"path": "/ffffffffffff/"
				}
			},
			
			"mux": {
				"enabled": false,
				"concurrency": -1
			}
		}
	]

}

**Comment by lxhao61** [comment]
仔细看介绍！此配置是兼容trojan-go的ws的配置！使用trojan-go客户端！你确定v2rayNG客户端支持trojan-go应用？！

**Comment by lxhao61** [comment]
另外v2rayNG客户端配置也有问题，应该如下：
{
"log": {
	"loglevel": "none"
},

"inbounds": [
	{
		"port": xxxx,
		"listen": "127.0.0.1",
		"protocol": "socks",
		"settings": {
			"auth": "noauth",
			"udp": true
		}
	}
],

"outbounds": [
	{
		"protocol": "trojan",
		"settings": {
			"servers": [
				{
					"address": "www.xxx.com",
					"port": 443,
					"password": "hhhhhhhhhhhhhh"
				}
			]
		},
		
		"streamSettings": {
			"security": "tls",
			"network": "ws",
			"wsSettings": {
				"path": "/ffffffffffff/"
			}
		},
		
		"mux": {
			"enabled": false,
			"concurrency": -1
		}
	},
	{
		"protocol": "freedom",
	}
]
}

**Comment by lxhao61** [comment]
另外使用v2ray客户端，含v2rayNG客户端只有你自己测试了。

**Comment by iKira** [comment]
> 仔细看介绍！此配置是兼容trojan-go的ws的配置，使用trojan-go客户端！你确定v2rayNG客户端支持trojan-go应用了？！

这么理解的话，是不是服务端也要用trojan-go才行？原版trojan要监听443端口处理TLS，服务端即便要用trojan-go的话是不是也要用关闭TLS处理的版本？

**Comment by lxhao61** [comment]
完全不明白你的逻辑！你先搞清出原版trojan与trojan-go差异！本配置是兼容trojan-go的WebSocket服务端配置！仔细看介绍！

此配置为v2ray新增trojan协议，以ws(WebSocket) 方式传输，实现了兼容trojan-go的ws(WebSocket) 模式，即直接使用trojan-go客户端连接。
另外通过 caddy2 或 nginx 前置 v2ray server 实现 ws 反向代理，tls 由 caddy2 或 nginx 提供及处理。
原理图： trojan-go client <------ ws+tls ------> caddy2\nginx <- ws -> v2ray server

**Comment by lxhao61** [comment]
> > 仔细看介绍！此配置是兼容trojan-go的ws的配置，使用trojan-go客户端！你确定v2rayNG客户端支持trojan-go应用了？！
> 
> 这么理解的话，是不是服务端也要用trojan-go才行？原版trojan要监听443端口处理TLS，服务端即便要用trojan-go的话是不是也要用关闭TLS处理的版本？

完全不明白你的逻辑！你先搞清出原版trojan与trojan-go差异！本配置是兼容trojan-go的WebSocket服务端配置！仔细看介绍！

此配置为v2ray新增trojan协议，以ws(WebSocket) 方式传输，实现了兼容trojan-go的ws(WebSocket) 模式，即直接使用trojan-go客户端连接。
另外通过 caddy2 或 nginx 前置 v2ray server 实现 ws 反向代理，tls 由 caddy2 或 nginx 提供及处理。
原理图： trojan-go client <------ ws+tls ------> caddy2\nginx <- ws -> v2ray server
