### ISSUE TITLE
用后还能捆绑网站吗？PHP如何使用呢？

### ISSUE THREAD

**Issue by alan21j** [lxhao61/integrated-examples#7]
在Caddyfile如何设定php，尝试过原始方法，发现网站的图片css等都不能正常读取，期盼帮助。

**Comment by lxhao61** [comment]
https://caddyserver.com/docs/caddyfile/directives/php_fastcgi

**Comment by alan21j** [comment]
版主，不想当伸手党，但真的看不明白。

这个xray naiveproxy共生的技术很高超，其实已经看不明白，盼望版主高手能指点迷津，

在caddyfile others上面也可以加入php的添加办法，方便各位技术不够的朋友为自己的机场增添战斗力。

**Comment by lxhao61** [comment]
> 版主，不想当伸手党，但真的看不明白。
> 
> 这个xray naiveproxy共生的技术很高超，其实已经看不明白，盼望版主高手能指点迷津，
> 
> 在caddyfile others上面也可以加入php的添加办法，方便各位技术不够的朋友为自己的机场增添战斗力。

对于PHP具体配置，我帮不了你，我对这个无研究（跟科学上网无关）。何况你仅概念需求，参考官方此参数介绍及配置示例即可，无法指点。
