### ISSUE TITLE
版本v2.5.2后前面protocol及allow_h2c与experimental_http3配置调整为：protocols h1 h2c h2 h3 运行报错

### ISSUE THREAD

**Issue by hedsbj** [lxhao61/integrated-examples#71]
run: adapting config using caddyfile: parsing caddyfile tokens for 'servers': /etc/caddy/Caddyfile:21 - Error during parsing: unrecognized servers option 'protocols'

原来配置
protocol {
			allow_h2c #开启h2c server支持，caddy-trojan插件应用必须启用。
			experimental_http3 #开启http3 server支持
		} #版本v2.5.2后前面protocol及allow_h2c与experimental_http3配置调整为：protocols h1 h2c h2 h3
新的配置
protocols h1 h2c h2 h3

是不是姿势 不对？

感谢大佬第一时间更新

**Comment by lxhao61** [comment]
无问题。
是否下载最新的版本，另外仔细检查配置。

**Comment by hedsbj** [comment]
多谢您及时回复，已经是最新版本，但还有两处的配置没有改，我再试一下（总共有三处，我是用的三件套 grpc naiveproxy和trojan)

**Comment by lxhao61** [comment]
改一处肯定报错，必须全部修改。

**Comment by hedsbj** [comment]
{
	order trojan before route
	order forward_proxy before trojan
	order reverse_proxy before forward_proxy
	admin off
	log {
		output file /var/log/caddy/access.log {
			roll_size 2Mib
			roll_keep 2
		}
		format json {
			time_format "iso8601"
		}
		level ERROR
		exclude http.handlers.reverse_proxy
	}
	servers :443 {
		listener_wrappers {
			trojan
		}
		protocols h1 h2c h2 h3
	}
	trojan {
		caddy
		no_proxy
		users diy443
	}
}
:443, xxx.xxx.xxx {
	tls {
		ciphers TLS_AES_256_GCM_SHA384 TLS_AES_128_GCM_SHA256 TLS_CHACHA20_POLY1305_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
		curves x25519 secp521r1 secp384r1 secp256r1
		alpn h2 http/1.1
	}
	@grpc {
		protocol grpc
		path /xxxxxx/*
	}

	reverse_proxy @grpc 127.0.0.1:2009 {
		transport http {
			versions h2c 2
		}
		flush_interval -1
		header_up X-Real-IP {remote_host}
	}
	forward_proxy {
		basic_auth xxxxxx "xxxxxxx"
		hide_ip
		hide_via
		probe_resistance
	}
	trojan {
		connect_method
		websocket
	}
	@host {
		host xxxx.xxxxx
	}
	route @host {
		header {
			Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		}
		file_server {
			root /usr/share/caddy
		}
	}
}

**Comment by lxhao61** [comment]
不好意思，编译少加一个master参数，老源码编译了。等下重新下载最新版本。

**Comment by hedsbj** [comment]
哈哈，多谢，找到原因就好，耽误 您时间了，再次感谢您的这个项目，非常好用，简单的配置完成三件工作，非常nice
