### ISSUE TITLE
您好作者，请问在vless/vmess、ws中的 nginx配置ssl_ciphers与ssl_ecdh_curve 

### ISSUE THREAD

**Issue by rianjskis** [lxhao61/integrated-examples#74]
我选用的这个配置https://github.com/lxhao61/integrated-examples/blob/main/v2ray(vless%5Cvmess%2BWS)%2Bcaddy%5Cnginx/1_nginx.conf   然后在琢磨其中的ssl_ciphers与ssl_ecdh_curve 生成。在网上找到了openssl ciphers用于生成ciphers,但与您配置中有些不太一样,请问这些您是如何选择的,  sll_ecdh_curve没找到生成的命令,网上搜了一圈,没看到特别详细的解释,所以来请教一下,

**Comment by lxhao61** [comment]
首先ssl_ciphers与ssl_ecdh_curve是控制使用那些参数，不是生成！控制是在你“生成”范围选用部分参数，实现优化。
为什么这么优化是参考nginx官方资料及相关知识综合取舍，简单及核心就是去除TLS1.2下ssl_ciphers下无用过时ciphers，及对应curve匹配。

**Comment by rianjskis** [comment]
> 首先ssl_ciphers与ssl_ecdh_curve是控制使用那些参数，不是生成！“生成”实际上在你使用 [OpenSSL ](https://www.openssl.org/)版本已经确定（支持那些参数）。控制是在“生成”范围选用部分参数实现优化。 这么优化是参考nginx官方资料及相关知识综合取舍：简单及核心就是去除TLS1.2下ssl_ciphers中无用过时的ciphers，并对应匹配curve，用顺序控制参数优先级。

原来如此，感谢解答，谢谢，

**Comment by lxhao61** [comment]
> 我后续做了点改动没有加上ssl_ciphers与ssl_ecdh_curve ，而是直接只用了下面这两个数据，请问会有不好的后果吗，在网上看到ssl_prefer_server_ciphers 打开就会选择我咨询的两个选项的tls等级与加密方式，关闭的话有风险吗smile ssl_protocols TLSv1.2 TLSv1.3; ssl_prefer_server_ciphers off;

没有绝对，风险取决你的底线。反正你怎样配置就是由客户端控制加密等级及加密方式。

**Comment by rianjskis** [comment]
> > 我后续做了点改动没有加上ssl_ciphers与ssl_ecdh_curve ，而是直接只用了下面这两个数据，请问会有不好的后果吗，在网上看到ssl_prefer_server_ciphers 打开就会选择我咨询的两个选项的tls等级与加密方式，关闭的话有风险吗smile ssl_protocols TLSv1.2 TLSv1.3; ssl_prefer_server_ciphers off;
> 
> 风险取决你的底线，没有绝对。反正你当前配置就是由客户端控制加密等级及加密方式。

好的，我看这样设置后没报错了，怕不安全来咨询下，哈哈哈，感谢作者老哥

**Comment by rianjskis** [comment]
> > 我后续做了点改动没有加上ssl_ciphers与ssl_ecdh_curve ，而是直接只用了下面这两个数据，请问会有不好的后果吗，在网上看到ssl_prefer_server_ciphers 打开就会选择我咨询的两个选项的tls等级与加密方式，关闭的话有风险吗smile ssl_protocols TLSv1.2 TLSv1.3; ssl_prefer_server_ciphers off;
> 
> 风险取决你的底线，没有绝对。反正你当前配置就是由客户端控制加密等级及加密方式。

[crit] 140500#140500: *3469 SSL_do_handshake() failed (SSL: error:0A00006C:SSL routines::bad key share) while SSL handshaking, client: 67.205.137.197, server: 0.0.0.0:443
老哥，今天nginx error.log出现这个报错，请问是nginx没配置好吗🙂

**Comment by lxhao61** [comment]
> > > 我后续做了点改动没有加上ssl_ciphers与ssl_ecdh_curve ，而是直接只用了下面这两个数据，请问会有不好的后果吗，在网上看到ssl_prefer_server_ciphers 打开就会选择我咨询的两个选项的tls等级与加密方式，关闭的话有风险吗smile ssl_protocols TLSv1.2 TLSv1.3; ssl_prefer_server_ciphers off;
> > 
> > 
> > 风险取决你的底线，没有绝对。反正你当前配置就是由客户端控制加密等级及加密方式。
> 
> [crit] 140500#140500: *3469 SSL_do_handshake() failed (SSL: error:0A00006C:SSL routines::bad key share) while SSL handshaking, client: 67.205.137.197, server: 0.0.0.0:443 老哥，今天nginx error.log出现这个报错，请问是nginx没配置好吗slightly_smiling_face

分析67.205.137.197归属即可。
