### ISSUE TITLE
caddy插件版trojan-go是不是不支持smux啊？

### ISSUE THREAD

**Issue by Pacio** [lxhao61/integrated-examples#76]
https://github.com/lxhao61/integrated-examples/tree/main/trojan-go(caddy%2Bcaddy-trojan)
我目前客户端用的是op上的bypass集成的xray,之前我自己docker的trojan-go设置了mux参数都是可以连通的，用了这个插件版的以后发现不能设置了，一设置就不通

**Comment by lxhao61** [comment]
是的，caddy插件版trojan-go不支持smux。
另外caddy已经优先HTTP/2了，个人觉得再smux无意义。

**Comment by Pacio** [comment]
> 是的，caddy插件版trojan-go不支持smux。 另外caddy优先H2了，个人觉得再smux无意义。

ok，了解😊

**Comment by Pacio** [comment]
> caddy插件版trojan-go不支持smux。 另外caddy优先H2了，个人觉得再smux无意义。

不知道为什么，昨晚睡觉前重装了一下vps的系统，今天早上重新部署的时候报错了，access.log提示：x509: certificate signed by unknown authority
这是什么情况？重装前的签证还在？

**Comment by Pacio** [comment]
晚上回来找到了解决方案,执行了apt install ca-certificates以后证书问搞定，但是日志还是有报错~请问什么原因
![QQ截图20220922220755](https://user-images.githubusercontent.com/6836705/191770330-0c6fbcff-1b50-423b-a2ee-a49c17e22561.png)
