### ISSUE TITLE
v2fly不支持grpc的UDS

### ISSUE THREAD

**Issue by git-earth** [lxhao61/integrated-examples#77]
![image](https://user-images.githubusercontent.com/110875504/191648343-998f8537-7912-4759-bbd4-9077a3128b61.png)

**Comment by lxhao61** [comment]
应该支持。[v2fly v4.36.0+之后才有gRPC](https://www.v2fly.org/config/transport/grpc.html)。

**Comment by git-earth** [comment]
我测试发现，caddy配置没有更改，v2fly切换到xray，"listen": "/dev/shm/vgrpc.sock,0666" 才正常。
也有可能是权限问题，
因为v2fly "listen": "/dev/shm/vgrpc.sock,0666"会在/dev/shm/下新建vgrpc.sock,0666.lock文件。。。

**Comment by lxhao61** [comment]
v2fly应该无支持直接对UDS路径设置权限（0666）。

**Comment by git-earth** [comment]
V2fly用"listen": "/dev/shm/vgrpc.sock" 不通才尝试设置权限，但是设置权限也跑不通，才切换到xray。xray不设置权限也不通，设置权限之后才行。

**Comment by lxhao61** [comment]
晕，难道不知道统一V2ray与Caddy用户运行！如都root运行。

**Comment by git-earth** [comment]
哈哈，人懒，还要去找两个软件的systemctl，干脆直接卸载安装更快，反正配置通用

**Comment by Remonli** [comment]
v2ray 的uds 是有问题的，配合caddy，监听在/run/shm/下，启动会有两个文件一个是xxx.socket,另一个是xxx.socket.lock,这时候正常工作。但是几个小时之后，这俩文件就不见了，但ss可以看到实际还在监听，网也是通的，不过有几率手机上网络不通。

不知道是caddy的问题，还是v2ray的问题。

**Comment by lxhao61** [comment]
> v2ray 的uds 是有问题的，配合caddy，监听在/run/shm/下，启动会有两个文件一个是xxx.socket,另一个是xxx.socket.lock,这时候正常工作。但是几个小时之后，这俩文件就不见了，但ss可以看到实际还在监听，网也是通的，不过有几率手机上网络不通。
> 
> 不知道是caddy的问题，还是v2ray的问题。

UDS监听路径改在/dev/shm/下试试。

**Comment by Remonli** [comment]
试过，一样的，而且/run/shm 就是/dev/shm的符号链接。
```
 8 Sep 23 00:42 shm -> /dev/shm
```

**Comment by lxhao61** [comment]
> 试过，一样的，而且/run/shm 就是/dev/shm的符号链接。
> 
> ```
>  8 Sep 23 00:42 shm -> /dev/shm
> ```

V2ray V4还是V5?

**Comment by Remonli** [comment]
5.1.0 preview，还真没试过v4有没有这问题。我先试试，如果v4没问题，我去提个issue。

**Comment by Remonli** [comment]
事实上v4也是一样，而且error log 也看不出什么时候丢的，只有启动的信息。
```
2022/09/25 00:25:42 [Debug] app/log: Logger started
2022/09/25 00:25:42 [Debug] app/proxyman/inbound: creating unix domain socket worker on /run/shm/v2ray.sock
```

**Comment by lxhao61** [comment]
> 事实上v4也是一样，而且error log 也看不出什么时候丢的，只有启动的信息。
> 
> ```
> 2022/09/25 00:25:42 [Debug] app/log: Logger started
> 2022/09/25 00:25:42 [Debug] app/proxyman/inbound: creating unix domain socket worker on /run/shm/v2ray.sock
> ```

我使用Xray没有发现此问题。若你严格参考示例的，那么排除caddy的问题，就只能是V2ray自身UDS问题了。
