### ISSUE TITLE
望增加arm版本caddy

### ISSUE THREAD

**Issue by liaoweiliao521** [lxhao61/integrated-examples#8]
希望大神可以增加arm版本的caddy编译文件  麻烦了  谢谢了

**Comment by lxhao61** [comment]
arm硬件与系统细分版本不少，性能参差不齐，且总体使用本来就不多，增加意义不大。

**Comment by liaoweiliao521** [comment]
谢谢回复 主要是甲骨文最近增加了arm的配置 😂😂

**Comment by liaoweiliao521** [comment]
大神 如果走纯ipv6 caddy还更改配置文件么

**Comment by lxhao61** [comment]
> 谢谢回复 主要是甲骨文最近增加了arm的配置

caddy_linux_arm64.tar.gz已增加。

**Comment by lxhao61** [comment]
> 大神 如果走纯ipv6 caddy还更改配置文件么

不必修改。除非你服务器对内也仅IPV6。

**Comment by liaoweiliao521** [comment]
谢谢大神重新编译 另外  我是把甲骨文的ipv4关了用的纯ipv6 安装的您编译的naiveproxy caddy 可以联网
