### ISSUE TITLE
Caddy2 使用json配置

### ISSUE THREAD

**Issue by zhoupingxiao** [lxhao61/integrated-examples#8]
看到大部分使用到Caddy的，都是说使用json配置模式，Caddy要怎么设置json格式

**Comment by lxhao61** [comment]
完全与调用Caddyfile配置一样，只是把Caddyfile改成caddy.json即可！
例如caddy.service文件调用配置。
[Unit]
Description=Caddy
Documentation=https://caddyserver.com/docs/
After=network.targett

[Service]
User=root
ExecStart=/usr/local/bin/caddy/caddy run --environ --config /usr/local/etc/caddy/caddy.json
ExecReload=/usr/local/bin/caddy/caddy reload --config /usr/local/etc/caddy/caddy.json
TimeoutStopSec=5s
LimitNOFILE=1048576
LimitNPROC=512
PrivateTmp=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
