### ISSUE TITLE
证书续签问题

### ISSUE THREAD

**Issue by yaak63** [lxhao61/integrated-examples#80]
请教一事：由于是cloudflare免费域名托管，现在不能够自动续签，有什么办法解决吗？

**Comment by lxhao61** [comment]
首先不明白你的意思。“cloudflare免费域名托管”什么意思？“不能够自动续签”什么意思？
我所知道是cloudflare是DNS解析商及CDN提供商，可托管域名（含免费域名）。
另外证书是否自动续签我没有觉得跟你说的“cloudflare免费域名托管”有什么关系？

**Comment by yaak63** [comment]
抱歉，我没有说清楚。我是免费域名，在cloudflare上不能够用API方式自动续签证书，请问还有别的办法可以用吗？

**Comment by lxhao61** [comment]
晕，明白了。是免费域名，在cloudflare上不能够用API方式自动签发证书。不是续签！
方法见duckdns配置示例(挑战委托模式)[https://github.com/lxhao61/integrated-examples/tree/main/caddy(other%20configuration)]。

**Comment by yaak63** [comment]
谢谢，不善于表达，且试试看，多谢指教。
