### ISSUE TITLE
您好作者，参考如下配置启用了CDN，访问域名时报错，节点也不通，请问是什么原因

### ISSUE THREAD

**Issue by rianjskis** [lxhao61/integrated-examples#81]
https://github.com/lxhao61/integrated-examples/blob/main/v2ray(vless%5Cvmess%2BWS)%2Bcaddy%5Cnginx/1_nginx.conf
我的xray配置：[xray配置.txt](https://github.com/lxhao61/integrated-examples/files/9661392/xray.txt)
我的nginx配置：[nginx.txt](https://github.com/lxhao61/integrated-examples/files/9662363/nginx.txt)

**Comment by lxhao61** [comment]
1、请参考相关示例仔细检查配置（配置有错误），建议一个个WS配置检查及调试。
2、nginx配置有“include”外部引用，确定是否引用正确。
3、先不启用CDN调试，若正常再启用CDN。注意：启用CDN需要开启WS支持。如cloudflare的SSL/TLS 加密模式为选完全（严格）等。

**Comment by rianjskis** [comment]
> 1、请对照示例仔细检查配置（配置有错误），建议一个个WS配置检查及调试。 2、nginx配置有“include”外部引用，确定是否引用正确。 3、先不启用CDN调试，若正常再启用CDN。注意：启用CDN需要开启WS支持。如cloudflare的SSL/TLS 加密模式为选完全（严格）等。

[xray.txt](https://github.com/lxhao61/integrated-examples/files/9662531/xray.txt)
[nginx.txt](https://github.com/lxhao61/integrated-examples/files/9662532/nginx.txt)
![123](https://user-images.githubusercontent.com/86937445/192716371-d4b5e3d6-e8d4-448e-bc79-fa5ec210e6ba.png)
我去完全照抄也没通过，

**Comment by lxhao61** [comment]
> > 1、请对照示例仔细检查配置（配置有错误），建议一个个WS配置检查及调试。 2、nginx配置有“include”外部引用，确定是否引用正确。 3、先不启用CDN调试，若正常再启用CDN。注意：启用CDN需要开启WS支持。如cloudflare的SSL/TLS 加密模式为选完全（严格）等。
> > ![123](https://user-images.githubusercontent.com/86937445/192716659-fba2a260-2beb-41ef-8b1f-169ce7b1b09e.png)
> > [xray.txt](https://github.com/lxhao61/integrated-examples/files/9662543/xray.txt)
> > [nginx.txt](https://github.com/lxhao61/integrated-examples/files/9662545/nginx.txt)
> > 尝试用您写好的配置单独弄一次，可惜还是没法ping通跟访问伪装网页。防火墙是开放了端口的.我使用的是aws的cdn加速。在尝试之前我关闭了CDN加速。

检查TLS证书是否正常！从你现在描述及截图来看，跟Xray与nginx配置无关了。

**Comment by rianjskis** [comment]
好的，我尝试一下
