### ISSUE TITLE
Hello,naiveproxy的文件如何配置非443端口呢

### ISSUE THREAD

**Issue by Git-Apt** [lxhao61/integrated-examples#84]
我在使用中naiveproxy的443端口被封现在只能使用非443端口，我在网上找了很久都是无法使用的方法，希望能添加2个非443端口的配置文件。和 reverse_proxy反代功能这样就不用开启个web页面里。谢谢啦在线等待。

**Comment by lxhao61** [comment]
JSON配置：
1、非443端口。直接参考本项目示例，修改"listen": 参数为非443端口即可。
2、反代别的网站参考 https://github.com/lxhao61/integrated-examples/issues/63

**Comment by lxhao61** [comment]
请仔细看对应示例及介绍，你的问题都可以得到解答。
另你想安全，建议伪装网站弄得跟真网站一样。

**Comment by Git-Apt** [comment]
您好我将所有的内容都看到了也理解了您的意思，文中未提及证书部分，我该如何将使用CF的证书呢，可以给一个编辑好的试例吗？谢谢您啦。如果使用CF15年的证书会存在问题吗？

**Comment by Git-Apt** [comment]
> 请仔细看看答案及解释，你的问题都可以得到解答的。 另外你想安全，建议伪装网站弄得跟真网站
您好我将所有的内容都可以看到也了您的英文，文未理解的部分证书，我该如何使用 CF 的证书呢，如果给一个编辑好的尝试使用吗？ CF15年的证书会存在问题吗？

**Comment by lxhao61** [comment]
晕，你无相关基础知识！
你可以使用CF免费证书，且只能启用CDN下使用。
CF的DN模式免费仅支持WebSocket、gRPC连接源服务器，故不支持naiveproxy应用。

**Comment by Git-Apt** [comment]
是的唉我学习了下是这样的然后443端口比其他非标标准安全更有流量迷惑性吗？

**Comment by lxhao61** [comment]
是的。

**Comment by Git-Apt** [comment]
我搞成功了然后我也部署了hysteria，他和naiveproxy好像不一样，但是他是基于UDP的可以和hysteria公用443端口一个走TCP一个走UDP，我的问题是hysteria用非443端口安全吗？比如6443这样的端口，我看到很多人的hysteria443端口被封掉了，最后呢就是用您的脚本成功啦，但是不知道申请的SSL证书在什么位置，哈哈因为hysteria也要用到证书。所以我想让它一起用。谢谢您不辞辛苦的解答我的疑惑，我也会这样去帮助别人，并且把他整理成文章发给更多人

**Comment by lxhao61** [comment]
hysteria无必要公用443端口。hysteria目前不支持伪装成网站流量（无反代、无回落等）。

**Comment by Git-Apt** [comment]
好的我学习下，辛苦，想请教下有群吗？

**Comment by Git-Apt** [comment]
我是用您 https://github.com/lxhao61/integrated-examples/blob/main/naiveproxy(caddy%2Bforwardproxy)/naive_Caddyfile 这里的代码申请的里面没有证书路径，所以不清楚它把证书到底放在那里了，我看了/etc/ssl目录没有新的证书。

**Comment by lxhao61** [comment]
> 我是用您 https://github.com/lxhao61/integrated-examples/blob/main/naiveproxy(caddy%2Bforwardproxy)/naive_Caddyfile 这里的代码申请的里面没有证书路径，所以不清楚它把证书到底放在那里了，我看了/etc/ssl目录没有新的证书。

它自己用，当然不需要指定证书路径。默认好像在/root里。
把如下代码加入全局块中即可，
```
	storage file_system {
		root /home/tls #存放证书及密钥的基本路径
	}
	cert_issuer acme #acme表示从Let's Encrypt申请证书及密钥，zerossl表示从ZeroSSL申请证书及密钥。必须acme与zerossl二选一（固定证书及密钥的目录便于引用）。注意：版本不小于v2.4.1才支持。
```

**Comment by lxhao61** [comment]
> 

可Telegram中Project X或#v2fly联系我。

**Comment by lxhao61** [comment]
> 好的我学习下，辛苦，想请教下有群吗？

可Telegram中Project X或#v2fly联系我。

**Comment by Git-Apt** [comment]
{
	order forward_proxy before route
	admin off
	log {
		output file /var/log/caddy/access.log
		level ERROR
	}
                 storage file_system {
		root /etc/ssl/caddy
	}
                 cert_issuer zerossl
	servers :443 {
		protocols h1 h2 h3
	}
}

:443, xx.xxx.com {
	tls {
		ciphers TLS_AES_256_GCM_SHA384 TLS_AES_128_GCM_SHA256 TLS_CHACHA20_POLY1305_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
		curves x25519 secp521r1 secp384r1 secp256r1
		alpn h2 http/1.1
	}

	forward_proxy {
		basic_auth xxx xxx
		hide_ip
		hide_via
		probe_resistance
	}

	@host {
		host xx.xxx.com
	}
	route @host {
		header {
			Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		}
		file_server {
			root /usr/share/caddy
		}
	}
}

您看下这样对吗，格式对不对，有没有少什么}

**Comment by Git-Apt** [comment]
>

**Comment by Git-Apt** [comment]
> > 好我学习下，辛苦了，想请教下有群吗？
> 
> 可Telegram中Project X或#v2fly联系我。

您的Tg多少我联系您，我没有加这样的群，我的是～ @makelazarus
