### ISSUE TITLE
我这种安装caddy插件版的方式是错误的吧？

### ISSUE THREAD

**Issue by palwoo** [lxhao61/integrated-examples#86]
系统是纯净的Ubuntu 22.04。登录之后这样操作：

```
wget https://github.com/lxhao61/integrated-examples/releases/download/20220927/caddy-linux-amd64.tar.gz

tar zxvf caddy-linux-amd64.tar.gz

apt install caddy
```
然后得到的提示是：

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package caddy
```

**Comment by lxhao61** [comment]
Go语言文件压缩包不需安装，解压、授予执行权限后直接运行即可。

**Comment by palwoo** [comment]
非常感谢您的解答。看您写的说明文字：“naiveproxy 服务端是以 caddy 源码加改进版 forwardproxy 插件编译而成，基于 HTTP/2 或 HTTP/3 代理实现科学上网。注意：1、使用本人 Releases 中编译好的 caddy 文件，可支持 naiveproxy 等应用。”  不知我这样理解对不对：使用您 Releases 中编译好的 caddy 文件，再加上https://github.com/lxhao61/integrated-examples/tree/main/naiveproxy(caddy%2Bforwardproxy)等适当的设置，就已经支持naiveproxy了，无需再到 https://github.com/klzgrad/naiveproxy/ 进行其他安装，例如[cronet](https://github.com/klzgrad/naiveproxy/releases/download/v106.0.5249.91-1/cronet-v106.0.5249.91-1-win-x86.zip)。我的目的是使用naiveproxy翻墙。

**Comment by lxhao61** [comment]
是的。
你仅需从naiveproxy下载客户端而已（若你使用他提供的）。

**Comment by palwoo** [comment]
设置文件从 https://github.com/lxhao61/integrated-examples/tree/main/naiveproxy(caddy%2Bforwardproxy) 下载并修改域名和用户密码等信息，在protocol部分修改成这样

```
servers :8443 {
		protocol {
			 h1 h2 h3  #开启HTTP/3 server支持
		} #版本v2.5.2后配置调整为：protocols h1 h2 h3
	}
```

然后执行  /usr/bin/caddy run --config /etc/caddy/Caddyfile

得到的错误提示：
```
root@localhost:~# /usr/bin/caddy run --config /etc/caddy/Caddyfile
2022/10/08 05:52:34.824 INFO    using provided configuration    {"config_file": "/etc/caddy/Caddyfile", "config_adapter": ""}
2022/10/08 05:52:34.826 WARN    caddyfile       DEPRECATED: protocol sub-option will be removed soon
Error: adapting config using caddyfile: parsing caddyfile tokens for 'servers': /etc/caddy/Caddyfile:10 - Error during parsing: unrecognized protocol option 'h1'
```

改用json格式，只改动了必须改动的如域名、用户和密码，把“"experimental_http3": true //开启HTTP/3 server支持。版本v2.5.2后配置调整为："protocols": ["h1","h2","h3"]”修改为
`"protocols": ["h1","h2","h3"]，`

然后执行 root@localhost:/etc/caddy# /usr/bin/caddy run --config /etc/caddy/naive_caddy.json
得到的错误提示：
2022/10/08 05:43:24.084 INFO    using provided configuration    {"config_file": "/etc/caddy/naive_caddy.json", "config_adapter": ""}
Error: loading initial config: decoding request body: invalid character '/' looking for beginning of object key string

**Comment by lxhao61** [comment]
Caddyfile配置中修改端口，必须如下完全一致。
servers :8443
:8443, xx.yy:8443

**Comment by palwoo** [comment]
多谢提醒。已按建议在域名后面也加了端口号。但错误的提示是在第10行： /etc/caddy/Caddyfile:10 - Error during parsing: unrecognized protocol option 'h1' ，这个协议部分是否我改错了？
`servers :8443 {
		protocol {
			 h1 h2 h3  
		} 
	}`

**Comment by lxhao61** [comment]
> 多谢提醒。已按建议在域名后面也加了端口号。但错误的提示是在第10行： /etc/caddy/Caddyfile:10 - Error during parsing: unrecognized protocol option 'h1' ，这个协议部分是否我改错了？ `servers :8443 { protocol { h1 h2 h3 } }`

晕，不自动你怎么理解的！是如下：
···
servers :8443 {
		protocols h1 h2 h3
	}
···

**Comment by palwoo** [comment]
> 然后执行 root@localhost:/etc/caddy# /usr/bin/caddy run --config /etc/caddy/naive_caddy.json 得到的错误提示：
> 
> ```
> 2022/10/08 05:43:24.084 INFO    using provided configuration    {"config_file": "/etc/caddy/naive_caddy.json", "config_adapter": ""}
> Error: loading initial config: decoding request body: invalid character '/' looking for beginning of object key string
> ```

错误原因找到：json文件不允许有注释，把您提供的注释内容以及“//”删除即可。

**Comment by palwoo** [comment]
> JSON配置： "protocols": ["h1","h2","h3"]，去掉‘,’。

保持原来的格式可以，去掉逗号之后不能运行。

**Comment by lxhao61** [comment]
> > JSON配置： "protocols": ["h1","h2","h3"]，去掉‘,’。
> 
> 保持原来的格式可以，去掉逗号之后不能运行。

去掉是最后边逗号。即"protocols": ["h1","h2","h3"]

**Comment by palwoo** [comment]
现在的进展，用您编译的文件和参数，无论是caddyfile还是caddy.json，都可以用带端口的方式正常访问网站。但是在本地机运行naiveproxy提供的客户端之后，本地机彻底不能上网，无论是被墙的网站还是原本可以正常访问的网站。naiveproxy.exe的运行提示是：[1009/082749.817:INFO:naive_proxy.cc(192)] Connection 82 closed: ERR_SOCKS_CONNECTION_FAILED。把代理服务器上caddy的log的level调到INFO, 打开access.log文件，没发现异常。

**Comment by lxhao61** [comment]
> 现在的进展，用您编译的文件和参数，无论是caddyfile还是caddy.json，都可以用带端口的方式正常访问网站。但是在本地机运行naiveproxy提供的客户端之后，本地机彻底不能上网，无论是被墙的网站还是原本可以正常访问的网站。naiveproxy.exe的运行提示是：[1009/082749.817:INFO:naive_proxy.cc(192)] Connection 82 closed: ERR_SOCKS_CONNECTION_FAILED。把代理服务器上caddy的log的level调到INFO, 打开access.log文件，没发现异常。

晕，你改了默认443端口。你客户端域名后需加上改的端口。

**Comment by palwoo** [comment]
当然加了新的端口号。客户端的config.json中关于proxy是这样设置的：

 "proxy": "https://我的用户名:我的密码@域名:新的端口号"

**Comment by lxhao61** [comment]
> 当然加了新的端口号。客户端的config.json中关于proxy是这样设置的：
> 
> "proxy": "[https://我的用户名:我的密码@域名:新的端口号](https://%E6%88%91%E7%9A%84%E7%94%A8%E6%88%B7%E5%90%8D:%E6%88%91%E7%9A%84%E5%AF%86%E7%A0%81@%E5%9F%9F%E5%90%8D:%E6%96%B0%E7%9A%84%E7%AB%AF%E5%8F%A3%E5%8F%B7)"

嗯。那无问题了。检查端口是否开放。

**Comment by palwoo** [comment]
出现错误的原因有可能是客户端的问题，当时是直接用naiveproxy官方提供的dos窗口下运行的exe文件进行测试，提示错误，不能正常使用。现在服务器端用naiveproxy官方提供的编译安装方式，客户端用Qv2ray，已经可以正常使用。非常感谢您花时间解答。
