### ISSUE TITLE
Caddy 2.6.1 makes "allow_h2c" depreciated

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [lxhao61/integrated-examples#87]
Latest Caddy removes experimental setting: "allow_h2c"

See https://github.com/caddyserver/caddy/releases/tag/v2.6.0

EDIT: Can you update the caddyfile/caddy.json according to this change?

**Comment by lxhao61** [comment]
早就更新了！见示例中对应备注（说明）。
