### ISSUE TITLE
naiveproxy http3

### ISSUE THREAD

**Issue by liaoweiliao521** [lxhao61/integrated-examples#9]
大神  下载的您编译的caddy和配置文件 naIve设置quic无法连接

**Comment by liaoweiliao521** [comment]
大佬 我看了您之前和naive作者的对话  现在编译caddy时还需要用到quick go么

**Comment by lxhao61** [comment]
> 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接

应该是naiveproxy源码问题。

**Comment by lxhao61** [comment]
> 大佬 我看了您之前和naive作者的对话 现在编译caddy时还需要用到quick go么

之前需要quick go，后来不需要了。现在不知道了，没有看到naive作者对这个信息告知。

**Comment by lgj83** [comment]
https://github.com/lxhao61/integrated-examples/blob/main/v2ray(E%2BB%2BC%2BD%2BG%2BA)%2Bnaiveproxy/3_naive_caddy.json
大佬，这个配置daddy不能experimental_http3": true吗？

**Comment by lxhao61** [comment]
> https://github.com/lxhao61/integrated-examples/blob/main/v2ray(E%2BB%2BC%2BD%2BG%2BA)%2Bnaiveproxy/3_naive_caddy.json
> 大佬，这个配置daddy不能experimental_http3": true吗？

这个示例对naiveproxy来说是套娃，不支持http/3。经过vless+tcp+tls处理后，不支持UDP.。

**Comment by liaoweiliao521** [comment]
> > 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接
> 
> 检查防火墙放行naiveproxy应用的UDP端口没？如443 UDP端口。

大佬 防火墙是检查甲骨文vps上的  还是本地客户端的

**Comment by lxhao61** [comment]
> > > 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接
> > 
> > 
> > 检查防火墙放行naiveproxy应用的UDP端口没？如443 UDP端口。
> 
> 大佬 防火墙是检查甲骨文vps上的 还是本地客户端的

两边防火墙都需要放行呀。http/3 TCP与UDP端口都要。如在443端口上进行naiveproxy应用，那么 UDP 443端口、TCP 443端口都需要开启。

**Comment by liaoweiliao521** [comment]
> > > > 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接
> > > 
> > > 
> > > 检查防火墙放行naiveproxy应用的UDP端口没？如443 UDP端口。
> > 
> > 
> > 大佬 防火墙是检查甲骨文vps上的 还是本地客户端的
> 
> vps上防火墙放行呀。http/3 TCP与UDP端口都要用。如在443端口上进行naiveproxy http/3应用，那么443 UDP端口、 443 TCP端口都需要开启。

vps上防火墙我都删了  入站和出站规则是协议和端口全部打开

**Comment by lxhao61** [comment]
> > > > > 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接
> > > > 
> > > > 
> > > > 检查防火墙放行naiveproxy应用的UDP端口没？如443 UDP端口。
> > > 
> > > 
> > > 大佬 防火墙是检查甲骨文vps上的 还是本地客户端的
> > 
> > 
> > vps上防火墙放行呀。http/3 TCP与UDP端口都要用。如在443端口上进行naiveproxy http/3应用，那么443 UDP端口、 443 TCP端口都需要开启。
> 
> vps上防火墙我都删了 入站和出站规则是协议和端口全部打开

嗯，还需采用支持aiveproxy http/3示例才行。

**Comment by liaoweiliao521** [comment]
> > > > > > 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接
> > > > > 
> > > > > 
> > > > > 检查防火墙放行naiveproxy应用的UDP端口没？如443 UDP端口。
> > > > 
> > > > 
> > > > 大佬 防火墙是检查甲骨文vps上的 还是本地客户端的
> > > 
> > > 
> > > vps上防火墙放行呀。http/3 TCP与UDP端口都要用。如在443端口上进行naiveproxy http/3应用，那么443 UDP端口、 443 TCP端口都需要开启。
> > 
> > 
> > vps上防火墙我都删了 入站和出站规则是协议和端口全部打开
> 
> 嗯，还需采用支持aiveproxy http/3示例才行。

大佬 我试了 vps可以连通udp  caddy的配置文件用的就是您的支持h3的 caddy.json ，caddy也是您最新编译的2.4.1 naive总是连不上

**Comment by lxhao61** [comment]
> > > > > > > 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接
> > > > > > 
> > > > > > 
> > > > > > 检查防火墙放行naiveproxy应用的UDP端口没？如443 UDP端口。
> > > > > 
> > > > > 
> > > > > 大佬 防火墙是检查甲骨文vps上的 还是本地客户端的
> > > > 
> > > > 
> > > > vps上防火墙放行呀。http/3 TCP与UDP端口都要用。如在443端口上进行naiveproxy http/3应用，那么443 UDP端口、 443 TCP端口都需要开启。
> > > 
> > > 
> > > vps上防火墙我都删了 入站和出站规则是协议和端口全部打开
> > 
> > 
> > 嗯，还需采用支持aiveproxy http/3示例才行。
> 
> 大佬 我试了 vps可以连通udp caddy的配置文件用的就是您的支持h3的 caddy.json ，caddy也是您最新编译的2.4.1 naive总是连不上

编译caddy的无问题！我自己就在用！检查示例配置及使用环境，受限条件不是所有示例都支持http/3！

**Comment by liaoweiliao521** [comment]
> > > > > > > > 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接
> > > > > > > 
> > > > > > > 
> > > > > > > 检查防火墙放行naiveproxy应用的UDP端口没？如443 UDP端口。
> > > > > > 
> > > > > > 
> > > > > > 大佬 防火墙是检查甲骨文vps上的 还是本地客户端的
> > > > > 
> > > > > 
> > > > > vps上防火墙放行呀。http/3 TCP与UDP端口都要用。如在443端口上进行naiveproxy http/3应用，那么443 UDP端口、 443 TCP端口都需要开启。
> > > > 
> > > > 
> > > > vps上防火墙我都删了 入站和出站规则是协议和端口全部打开
> > > 
> > > 
> > > 嗯，还需采用支持aiveproxy http/3示例才行。
> > 
> > 
> > 大佬 我试了 vps可以连通udp caddy的配置文件用的就是您的支持h3的 caddy.json ，caddy也是您最新编译的2.4.1 naive总是连不上
> 
> 编译的caddy http/3无问题！我自己就在用！仔细检查自己的配置是否与示例完全一致，受限条件不是所有caddy示例都支持http/3！
> 你参考那个示例？
就是您的integrated-examples/naiveproxy(caddy+forwardproxy)/naive_caddy.json这个示例

**Comment by liaoweiliao521** [comment]
> > > > > > > > > > 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 检查防火墙放行naiveproxy应用的UDP端口没？如443 UDP端口。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 大佬 防火墙是检查甲骨文vps上的 还是本地客户端的
> > > > > > > 
> > > > > > > 
> > > > > > > vps上防火墙放行呀。http/3 TCP与UDP端口都要用。如在443端口上进行naiveproxy http/3应用，那么443 UDP端口、 443 TCP端口都需要开启。
> > > > > > 
> > > > > > 
> > > > > > vps上防火墙我都删了 入站和出站规则是协议和端口全部打开
> > > > > 
> > > > > 
> > > > > 嗯，还需采用支持aiveproxy http/3示例才行。
> > > > 
> > > > 
> > > > 大佬 我试了 vps可以连通udp caddy的配置文件用的就是您的支持h3的 caddy.json ，caddy也是您最新编译的2.4.1 naive总是连不上
> > > 
> > > 
> > > 编译的caddy http/3无问题！我自己就在用！仔细检查自己的配置是否与示例完全一致，受限条件不是所有caddy示例都支持http/3！
> > > 你参考那个示例？
> > > 就是您的integrated-examples/naiveproxy(caddy+forwardproxy)/naive_caddy.json这个示例
> 
> 没道理，这个是支持http/3的。 你没有进行SNI分流吧？

手机客户端用的sagernet 电脑端用的q2ray 都是输入账号密码域名 选择quic后保存 无法上网  但是选择https协议没问题

**Comment by lxhao61** [comment]
> > > > > > > > > > > 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 检查防火墙放行naiveproxy应用的UDP端口没？如443 UDP端口。
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 大佬 防火墙是检查甲骨文vps上的 还是本地客户端的
> > > > > > > > 
> > > > > > > > 
> > > > > > > > vps上防火墙放行呀。http/3 TCP与UDP端口都要用。如在443端口上进行naiveproxy http/3应用，那么443 UDP端口、 443 TCP端口都需要开启。
> > > > > > > 
> > > > > > > 
> > > > > > > vps上防火墙我都删了 入站和出站规则是协议和端口全部打开
> > > > > > 
> > > > > > 
> > > > > > 嗯，还需采用支持aiveproxy http/3示例才行。
> > > > > 
> > > > > 
> > > > > 大佬 我试了 vps可以连通udp caddy的配置文件用的就是您的支持h3的 caddy.json ，caddy也是您最新编译的2.4.1 naive总是连不上
> > > > 
> > > > 
> > > > 编译的caddy http/3无问题！我自己就在用！仔细检查自己的配置是否与示例完全一致，受限条件不是所有caddy示例都支持http/3！
> > > > 你参考那个示例？
> > > > 就是您的integrated-examples/naiveproxy(caddy+forwardproxy)/naive_caddy.json这个示例
> > 
> > 
> > 没道理，这个是支持http/3的。 你没有进行SNI分流吧？
> 
> 手机客户端用的sagernet 电脑端用的q2ray 都是输入账号密码域名 选择quic后保存 无法上网 但是选择https协议没问题

晕！使用官方naiveproxy客户端测试。

**Comment by liaoweiliao521** [comment]
> > > > > > > > > > > > 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 检查防火墙放行naiveproxy应用的UDP端口没？如443 UDP端口。
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 大佬 防火墙是检查甲骨文vps上的 还是本地客户端的
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > vps上防火墙放行呀。http/3 TCP与UDP端口都要用。如在443端口上进行naiveproxy http/3应用，那么443 UDP端口、 443 TCP端口都需要开启。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > vps上防火墙我都删了 入站和出站规则是协议和端口全部打开
> > > > > > > 
> > > > > > > 
> > > > > > > 嗯，还需采用支持aiveproxy http/3示例才行。
> > > > > > 
> > > > > > 
> > > > > > 大佬 我试了 vps可以连通udp caddy的配置文件用的就是您的支持h3的 caddy.json ，caddy也是您最新编译的2.4.1 naive总是连不上
> > > > > 
> > > > > 
> > > > > 编译的caddy http/3无问题！我自己就在用！仔细检查自己的配置是否与示例完全一致，受限条件不是所有caddy示例都支持http/3！
> > > > > 你参考那个示例？
> > > > > 就是您的integrated-examples/naiveproxy(caddy+forwardproxy)/naive_caddy.json这个示例
> > > 
> > > 
> > > 没道理，这个是支持http/3的。 你没有进行SNI分流吧？
> > 
> > 
> > 手机客户端用的sagernet 电脑端用的q2ray 都是输入账号密码域名 选择quic后保存 无法上网 但是选择https协议没问题
> 
> 晕！使用官方naiveproxy客户端测试。

大佬  vps端需要安装naiveproxy客户端不

**Comment by lxhao61** [comment]
> > > > > > > > > > > > > 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > 检查防火墙放行naiveproxy应用的UDP端口没？如443 UDP端口。
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 大佬 防火墙是检查甲骨文vps上的 还是本地客户端的
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > vps上防火墙放行呀。http/3 TCP与UDP端口都要用。如在443端口上进行naiveproxy http/3应用，那么443 UDP端口、 443 TCP端口都需要开启。
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > vps上防火墙我都删了 入站和出站规则是协议和端口全部打开
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 嗯，还需采用支持aiveproxy http/3示例才行。
> > > > > > > 
> > > > > > > 
> > > > > > > 大佬 我试了 vps可以连通udp caddy的配置文件用的就是您的支持h3的 caddy.json ，caddy也是您最新编译的2.4.1 naive总是连不上
> > > > > > 
> > > > > > 
> > > > > > 编译的caddy http/3无问题！我自己就在用！仔细检查自己的配置是否与示例完全一致，受限条件不是所有caddy示例都支持http/3！
> > > > > > 你参考那个示例？
> > > > > > 就是您的integrated-examples/naiveproxy(caddy+forwardproxy)/naive_caddy.json这个示例
> > > > 
> > > > 
> > > > 没道理，这个是支持http/3的。 你没有进行SNI分流吧？
> > > 
> > > 
> > > 手机客户端用的sagernet 电脑端用的q2ray 都是输入账号密码域名 选择quic后保存 无法上网 但是选择https协议没问题
> > 
> > 
> > 晕！使用官方naiveproxy客户端测试。
> 
> 大佬 vps端需要安装naiveproxy客户端不

晕，VPS安装什么naiveproxy客户端！你一点不懂电脑/网络知识？

**Comment by liaoweiliao521** [comment]
> > > > > > > > > > > > > > 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 检查防火墙放行naiveproxy应用的UDP端口没？如443 UDP端口。
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > 大佬 防火墙是检查甲骨文vps上的 还是本地客户端的
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > vps上防火墙放行呀。http/3 TCP与UDP端口都要用。如在443端口上进行naiveproxy http/3应用，那么443 UDP端口、 443 TCP端口都需要开启。
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > vps上防火墙我都删了 入站和出站规则是协议和端口全部打开
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 嗯，还需采用支持aiveproxy http/3示例才行。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 大佬 我试了 vps可以连通udp caddy的配置文件用的就是您的支持h3的 caddy.json ，caddy也是您最新编译的2.4.1 naive总是连不上
> > > > > > > 
> > > > > > > 
> > > > > > > 编译的caddy http/3无问题！我自己就在用！仔细检查自己的配置是否与示例完全一致，受限条件不是所有caddy示例都支持http/3！
> > > > > > > 你参考那个示例？
> > > > > > > 就是您的integrated-examples/naiveproxy(caddy+forwardproxy)/naive_caddy.json这个示例
> > > > > 
> > > > > 
> > > > > 没道理，这个是支持http/3的。 你没有进行SNI分流吧？
> > > > 
> > > > 
> > > > 手机客户端用的sagernet 电脑端用的q2ray 都是输入账号密码域名 选择quic后保存 无法上网 但是选择https协议没问题
> > > 
> > > 
> > > 晕！使用官方naiveproxy客户端测试。
> > 
> > 
> > 大佬 vps端需要安装naiveproxy客户端不
> 
> 晕，VPS安装什么naiveproxy客户端！你一点不懂电脑/网络知识？

我都被quic搞的晕了  各种试  naive的windows端quic和https都无法连接 只有q2ray和sagernet的https协议能用

**Comment by liaoweiliao521** [comment]
> > > > > > > > > > > > > > > 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 检查防火墙放行naiveproxy应用的UDP端口没？如443 UDP端口。
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 大佬 防火墙是检查甲骨文vps上的 还是本地客户端的
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > vps上防火墙放行呀。http/3 TCP与UDP端口都要用。如在443端口上进行naiveproxy http/3应用，那么443 UDP端口、 443 TCP端口都需要开启。
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > vps上防火墙我都删了 入站和出站规则是协议和端口全部打开
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 嗯，还需采用支持aiveproxy http/3示例才行。
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 大佬 我试了 vps可以连通udp caddy的配置文件用的就是您的支持h3的 caddy.json ，caddy也是您最新编译的2.4.1 naive总是连不上
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 编译的caddy http/3无问题！我自己就在用！仔细检查自己的配置是否与示例完全一致，受限条件不是所有caddy示例都支持http/3！
> > > > > > > > 你参考那个示例？
> > > > > > > > 就是您的integrated-examples/naiveproxy(caddy+forwardproxy)/naive_caddy.json这个示例
> > > > > > 
> > > > > > 
> > > > > > 没道理，这个是支持http/3的。 你没有进行SNI分流吧？
> > > > > 
> > > > > 
> > > > > 手机客户端用的sagernet 电脑端用的q2ray 都是输入账号密码域名 选择quic后保存 无法上网 但是选择https协议没问题
> > > > 
> > > > 
> > > > 晕！使用官方naiveproxy客户端测试。
> > > 
> > > 
> > > 大佬 vps端需要安装naiveproxy客户端不
> > 
> > 
> > 晕，VPS安装什么naiveproxy客户端！你一点不懂电脑/网络知识？
> 
> 我都被quic搞的晕了 各种试 naive的windows端quic和https都无法连接 只有q2ray和sagernet的https协议能用

cloudflare的quic开关打开了  vps只建了一个实例 用的您编译的caddy和示例 caddy正常运行状态 chrome的quic功能打开的 防火墙和端口也是全部打开的 本地电脑端我也打开了tcp和udp 443端口  就是连不上 搞得晕头转向

**Comment by liaoweiliao521** [comment]
> > > > > > > > > > > > > > > > 大神 下载的您编译的caddy和配置文件 naIve设置quic无法连接
> > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > 检查防火墙放行naiveproxy应用的UDP端口没？如443 UDP端口。
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 大佬 防火墙是检查甲骨文vps上的 还是本地客户端的
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > vps上防火墙放行呀。http/3 TCP与UDP端口都要用。如在443端口上进行naiveproxy http/3应用，那么443 UDP端口、 443 TCP端口都需要开启。
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > vps上防火墙我都删了 入站和出站规则是协议和端口全部打开
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 嗯，还需采用支持aiveproxy http/3示例才行。
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 大佬 我试了 vps可以连通udp caddy的配置文件用的就是您的支持h3的 caddy.json ，caddy也是您最新编译的2.4.1 naive总是连不上
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 编译的caddy http/3无问题！我自己就在用！仔细检查自己的配置是否与示例完全一致，受限条件不是所有caddy示例都支持http/3！
> > > > > > > > > 你参考那个示例？
> > > > > > > > > 就是您的integrated-examples/naiveproxy(caddy+forwardproxy)/naive_caddy.json这个示例
> > > > > > > 
> > > > > > > 
> > > > > > > 没道理，这个是支持http/3的。 你没有进行SNI分流吧？
> > > > > > 
> > > > > > 
> > > > > > 手机客户端用的sagernet 电脑端用的q2ray 都是输入账号密码域名 选择quic后保存 无法上网 但是选择https协议没问题
> > > > > 
> > > > > 
> > > > > 晕！使用官方naiveproxy客户端测试。
> > > > 
> > > > 
> > > > 大佬 vps端需要安装naiveproxy客户端不
> > > 
> > > 
> > > 晕，VPS安装什么naiveproxy客户端！你一点不懂电脑/网络知识？
> > 
> > 
> > 我都被quic搞的晕了 各种试 naive的windows端quic和https都无法连接 只有q2ray和sagernet的https协议能用
> 
> cloudflare的quic开关打开了 vps只建了一个实例 用的您编译的caddy和示例 caddy正常运行状态 chrome的quic功能打开的 防火墙和端口也是全部打开的 本地电脑端我也打开了tcp和udp 443端口 就是连不上 搞得晕头转向

大佬  刚才看了下caddy的运行状态 出现了这个2021/06/09 15:56:30 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffe

**Comment by liaoweiliao521** [comment]
大佬  我输入sysctl -w net.core.rmem_max=2500000这个命令后重启了caddy  然后就可以使用quic协议了  谢谢大佬的关心回复

**Comment by lxhao61** [comment]
> 大佬 我输入sysctl -w net.core.rmem_max=2500000这个命令后重启了caddy 然后就可以使用quic协议了 谢谢大佬的关心回复

晕，原来UDP接收缓冲区大小问题。

**Comment by liaoweiliao521** [comment]
> > 大佬 我输入sysctl -w net.core.rmem_max=2500000这个命令后重启了caddy 然后就可以使用quic协议了 谢谢大佬的关心回复
> 
> 晕，原来UDP接收缓冲区大小问题。

是啊 谢谢大佬 不过使用quic后感觉没有h2快 是不是quic还是不太完善啊

**Comment by lxhao61** [comment]
另外更新了caddy 编译，测试发现naiveproxy的quic应用速度与https应用速度无差别了。

**Comment by liaoweiliao521** [comment]
大佬您又更新了？ 我用的就是您编译的最新的2.4.1 估计我的网不行

**Comment by lxhao61** [comment]
> 大佬您又更新了？ 我用的就是您编译的最新的2.4.1 估计我的网不行

嗯，仅更新了程序文件。

**Comment by liaoweiliao521** [comment]
下载了 您咋又忘了arm版本类

**Comment by liaoweiliao521** [comment]
> 下载了 您咋又忘了arm版本类

我没看到  有arm版

**Comment by liaoweiliao521** [comment]
前几天只有naiveproxy能用 xray trojan heroku端口都被feng了

**Comment by lxhao61** [comment]
> > 下载了 您咋又忘了arm版本类
> 
> 我没看到 有arm版

arm版是一个大类！caddy_linux_arm64.tar.gz不是你需要的arm版嘛！

**Comment by liaoweiliao521** [comment]
> > > 下载了 您咋又忘了arm版本类
> > 
> > 
> > 我没看到 有arm版
> 
> arm版是一个大类！caddy_linux_arm64.tar.gz不是你需要的arm版嘛！！！

恩 看到了  这个今天也更新了？

**Comment by lxhao61** [comment]
> > > > 下载了 您咋又忘了arm版本类
> > > 
> > > 
> > > 我没看到 有arm版
> > 
> > 
> > arm版是一个大类！caddy_linux_arm64.tar.gz不是你需要的arm版嘛！！！
> 
> 恩 看到了 这个今天也更新了？

嗯。

**Comment by liaoweiliao521** [comment]
谢大佬  我下载装机去
