### ISSUE TITLE
trojan\trojan-go+caddy2\nginx示例，caddy2\nginx未包含h2c server配置。

### ISSUE THREAD

**Issue by ssbty** [lxhao61/integrated-examples#9]
server {
        listen 127.0.0.1:80; #http/1.1 server 监听本地80端口

        charset utf-8;

        access_log logs/access.log main;

        location / {
            root /var/www/html; #修改成自己存放的web文件路径
        }

        error_page  404              /404.html;

        error_page 500 502 503 504 /50x.html;
    }

**Comment by lxhao61** [comment]
配置无错误，是你认识错误。
trojan或trojan-go是https（http/1.1+tls）应用，不包含https/2应用。故回落仅h1回落即可，不需要h2回落，当然就不需要配置回落web服务器支持h2c server。

**Comment by ssbty** [comment]
trojan配置内
"alpn_port_override": {
       "h2": 81
},

官网解释是
alpn_port_override：如果ALPN匹配到，则将远程端口覆盖为指定值。对于在不同端口上运行带有HTTP / 1.1和HTTP / 2明文的NGINX很有用。

这是不是包含https/2应用的意思？

**Comment by lxhao61** [comment]
> trojan配置内
> "alpn_port_override": {
> "h2": 81
> },
> 
> 官网解释是
> alpn_port_override：如果ALPN匹配到，则将远程端口覆盖为指定值。对于在不同端口上运行带有HTTP / 1.1和HTTP / 2明文的NGINX很有用。
> 
> 这是不是包含https/2应用的意思？

不好意思。我之前解释错误，https包含http/2应用。
模板配置，仅alpn配置了http/1.1，故回落配置是没有问题的。
针对trojan配置内 "alpn_port_override": { "h2": 81 }，应该是alpn配置h2后，解决回落web服务器h2c server与http/1.1 server不能共端口问题，即h2c server端口为81。

**Comment by lxhao61** [comment]
另外针对alpn配置h2及回落，我测试后，根据情况考虑是否更新修订。

**Comment by ssbty** [comment]
谢谢，期待大佬的h2配置。

**Comment by lxhao61** [comment]
> 谢谢，期待大佬的h2配置。

已经更新增加了h2连接及回落。
