### ISSUE TITLE
naiveproxy 在苹果手机，shadowrocket 上协议选择http2可以正常运行，选https不可

### ISSUE THREAD

**Issue by hedsbj** [lxhao61/integrated-examples#95]
在梅林科学上网插件（3.0.4）新增的naive中https和quic都不能正常运行

**Comment by lxhao61** [comment]
不知道你的标题及内容主要对什么寻求帮助？
就字面意思来看：第三方客户端问题非本项目可以解决，请提供客户端的寻求帮助。
